### ISSUE TITLE
unit test for CR -> proto conversion

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1035]
# Proposed Feature

We keep getting tripped up on hard to detect bugs, caused by our hand-written conversion code of CRs to protos. 

See: https://github.com/akuity/kargo/issues/708.

Until we figure out a way to stop doing this conversion, we need unit tests to fail when we add/remove to one data structure and not the other.

# Motivation

Bugs.

# Suggested Implementation

The test should:
* Reflect on CRD data structure to create a dot notation map of all fields (recursively)
* Reflect on Proto data structure to create a second dot notation map of all fields (recursively)
* Verify the two maps are equal

**Comment by krancour** [comment]
Random thought I had...

I wonder how much success we might have doing conversions just by marshaling the input type to JSON and then umarshaling to the output type.

Off the top of my head, I don't think we're doing anything complicated enough to stop that from working.

**Comment by krancour** [comment]
I'm closing this since we agree that we're going to fix the root problem of having to write conversion functions manually.
