### ISSUE TITLE
add api server endpoint for manually qualifying a piece of freight

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1073]
Depends on #1033 

This would enable hotfixes _without_ cluttering stage DAGs with subscriptions from prod (on the far right) to a warehouse (on the far left).

**Comment by rbreeze** [comment]
Explicitly adding 2 requirements for this endpoint so they aren't forgotten:

1. Verify stage exists
2. For Stage delete endpoint, remove the entry in `approvedFor` for that stage
