### ISSUE TITLE
ui support for freight aliases

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1077]
Follow up to #1072 / #1076 

The UI needs to:

1. Show human-readable names instead of shas1 when possible (while keeping id/sha readily accessible).

2. Provided a way to rename/re-label a piece of freight.

**Comment by krancour** [comment]
@rbreeze now that #1097 is merged, there is at least a default alias for every piece of Freight.

Any thoughts about how to incorporate this? You are far more expert at this than I am, but my initial thought was something like showing the alias instead of the SHA (if it has one, that is; someone _could_ manually remove that label, after all), but then making the SHA visible my mousing over or something...

You can probably beat this idea. 😉 

Feel free to re-assign. Just wanted to have someone on point.

**Comment by krancour** [comment]
#1180 does the display half of this.

**Comment by rbreeze** [comment]
Fixed by https://github.com/akuity/kargo/pull/1180

**Comment by rbreeze** [comment]
Oh, I missed your earlier comment @krancour. I implemented by simply replacing the SHA in the UI with the alias if the alias exists; I figured that to see the SHA a user can click on the Stage details.
