### ISSUE TITLE
GitHub Token displayed in Clear Text on the UI

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#1107]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

```shell
$ kargo version 
Client Version: v0.2.0
Server Version: v0.2.0
```

# Proposed Feature

When there's an error having to do with Github, the GitHub token is displayed in clear text.

![image](https://github.com/akuity/kargo/assets/10502863/8c125e4c-4d43-4dd1-a3a1-9cdd2f206a29)

The proposal is to obfuscate the GitHub Token on the UI

# Motivation

We shouldn't display the token in the UI (in the logs is fine for debugging purposes but don't bubble that up in the UI)

# Suggested Implementation

@rbreeze suggested that it should be done on the API side

**Comment by krancour** [comment]
I can tackle this in the controller.
