### ISSUE TITLE
The "truck" icon does nothing

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#1108]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

The "truck" icon (that's supposed to promote subscribers) doesn't work in v0.2.0. When you press the button, the "yes/no" promotion dialog doesn't appear.

# Screenshots

![image](https://github.com/akuity/kargo/assets/10502863/b3f4bd3f-c30c-4268-b130-3811f1f29adf)

# Steps to Reproduce

1. Install v0.2.0
2. Create a warehouse with some stages
3. Try and use the "Truck" icon to promote

# Version

```
Client Version: v0.2.0
Server Version: v0.2.0
```

**Comment by krancour** [comment]
This was fixed in v0.2.x by #1126 and in main by #1127
