### ISSUE TITLE
Autopromotion doesn't work when a Stage is subscribed to another stage

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#1111]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Looks like: `warehouse` ~> `stage` autopromotion works as expected when a promotion policy is in place.

However, when doing a `Stage` to `Stage` autopromotion doesn't seem to work even when a promotion policy is in place.

# Steps to Reproduce

1. Create a promotion policy of autopromotion being `true`
2. Subscribe a `Stage` to another `Stage`
3. Promote the upstream stage
4. The autopromotion doeesn't work

# Version

```
$ kargo version 
Client Version: v0.2.0
Server Version: v0.2.0
```

# Logs

Didn't see much in the logs but this is what I saw

```
$ k logs -l app.kubernetes.io/component=controller -n kargo
time="2023-11-15T01:46:40Z" level=debug msg="Promotion already exists for Freight" freight=b8088e76c4a05dc72470f23550ef7f500985ec26 namespace=kargo-demo stage=uat
time="2023-11-15T01:46:40Z" level=debug msg="done reconciling Stage" namespace=kargo-demo stage=uat
time="2023-11-15T01:46:40Z" level=debug msg="reconciling Stage" namespace=kargo-demo stage=test
time="2023-11-15T01:46:40Z" level=debug msg="found Stage" namespace=kargo-demo stage=test
time="2023-11-15T01:46:40Z" level=debug msg="Stage health assessed" freight=b8088e76c4a05dc72470f23550ef7f500985ec26 health=Healthy namespace=kargo-demo stage=test
time="2023-11-15T01:46:40Z" level=debug msg="Freight already qualified for Stage" freight=b8088e76c4a05dc72470f23550ef7f500985ec26 namespace=kargo-demo stage=test
time="2023-11-15T01:46:40Z" level=debug msg="Stage is eligible for auto-promotion; checking if it is permitted..." namespace=kargo-demo stage=test
time="2023-11-15T01:46:40Z" level=debug msg="no PromotionPolicy is associated with the Stage" namespace=kargo-demo stage=test
time="2023-11-15T01:46:40Z" level=debug msg="auto-promotion is not permitted for the Stage" namespace=kargo-demo stage=test
time="2023-11-15T01:46:40Z" level=debug msg="done reconciling Stage" namespace=kargo-demo stage=test
```

**Comment by krancour** [comment]
Issue was introduced by #1103...

To fix #1101, it _doesn't_ auto-promote if a Promotion already exists that references the Freight.

It _should have_ checked for a Promotion that already exists that references the Freight _and_ Stage.
