### ISSUE TITLE
Auto Promotion Takes long time after a new freight is created

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#1155]
# Checklist

* [v] I've searched the issue queue to verify this is not a duplicate bug report.
* [v] I've included steps to reproduce the bug.
* [v] I've pasted the output of `kargo version`.
* [v] I've pasted logs, if applicable.

# Description

After A new freight is created by the warehouse, it takes a long time for the auto-promote mechanism to trigger and promote to the relevant stage.

it takes around 10 min to auto promote a new freight

# Screenshots

Current State:
![image](https://github.com/akuity/kargo/assets/97454240/aa0b9e31-5004-4038-a577-a56fdd78fe71)

New frieght detected:
![image](https://github.com/akuity/kargo/assets/97454240/4197b111-c8ad-462c-be46-d1ee7887381f)

auto promote happened:
![image](https://github.com/akuity/kargo/assets/97454240/5982dc2e-9341-40ab-87b8-217ae915bba1)

# Steps to Reproduce

# Logs

[kargo-controller-74bdd7d5c5-kx7gr-controller (1).log](https://github.com/akuity/kargo/files/13425062/kargo-controller-74bdd7d5c5-kx7gr-controller.1.log)

**Comment by krancour** [comment]
Thanks @tal-hason!

**Comment by krancour** [comment]
Closing this in favor of #1157 which describes both the issue and fix succinctly and classifies this as an enhancement rather than a bug.
