### ISSUE TITLE
make it more obvious WHY freight is available to a stage

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1158]
See #1153 

Some message or other visual means of making the user more aware of what Freight is considered "available" to each Stage might clear up confusion for anyone who has been misled into thinking the two promote buttons on each Stage follow strict push/pull semantics.

For example (lifted from #1153):

> It could be something as simple as a thin banner that appears above the freightline during promotion, saying something like, "These Freight have all qualified in the Stages immediately upstream from `x`." I'm no UI expert though. I defer to @rbreeze for better ideas of how me might visually clear up this confusion.

**Comment by rbreeze** [comment]
@krancour I agree that a simple banner with more explanation would probably clear up the confusion.

I'll work on this, and once it is implemented if we continue to see confusion we can revisit
