### ISSUE TITLE
Warehouse did not detect new image automatically (without manual refresh)

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1192]
# Description

I had a new image in my container registry sitting there for 5 hours. But Kargo did not detect the new image automatically. It took a manual refresh before it showed up. See attached video where I had pushed a v0.0.35 image 5 hours ago, went to check kargo UI to look for it, but it did not show up until I clicked refresh on the warehouse.

# Screenshots

https://github.com/akuity/kargo/assets/12677113/68adbd0e-5df0-41b3-9cc1-2944e8e2f2d7

# Steps to Reproduce

Push a new image to a monitored registry. Wait N minutes (or however long we expect it to resync).

# Version

Main as of today (d342b0d9bffc8acc53334fe47d82ff32e916b176).

# Logs

```
Paste any relevant application logs here.
```

**Comment by krancour** [comment]
I feel as if I have recently seen even manual refresh fail to detect a new image, but I not entirely certain.

@jessesuen if you see this happen again, would you mind looking at logs to see if the warehouse is reconciling periodically when left to its own devices?

It's a debug level message. (idk if you have debug enabled in the kargo.demo.akuity.io instance or not.)

**Comment by jessesuen** [comment]
> I feel as if I have recently seen even manual refresh fail to detect a new image, but I am not entirely certain.

Manual refreshes always work for me. It indicates the time-based reconciliations are not happening.

**Comment by krancour** [comment]
@jessesuen do you still see this happening? If so, was there anything revealing in the debug logs?
