### ISSUE TITLE
Misleading `promote subscribers: not_found` error

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1199]
# Description

I tried to promote a freight that was not verified properly in an upstream Stage. The error I get back is: `no available Freight "2d109e3b80ef548a12486fa9079c5419f2bc773e" found in namespace "kargo-guestbook"`

```
$ kargo stage promote-subscribers --freight 2d109e3b80ef548a12486fa9079c5419f2bc773e kargo-guestbook prod-us
Error: promote subscribers: not_found: no available Freight "2d109e3b80ef548a12486fa9079c5419f2bc773e" found in namespace "kargo-guestbook"
```

However, the freight does exist:

```
$ kargo get freight --project kargo-guestbook 2d109e3b80ef548a12486fa9079c5419f2bc773e
NAME                                       AGE
2d109e3b80ef548a12486fa9079c5419f2bc773e   59m
```

I think this is because of the logic here:
https://github.com/akuity/kargo/blob/d639370af93816234caba2cee3366e119ce0b9c3/internal/api/promote_subscribers_v1alpha1.go#L77-L84

Instead of returning "Not Found", we need to return an invalid argument error saying that it's not verified appropriately

# Screenshots

# Steps to Reproduce

Try to promote a freight that is not been verified in upstream.

# Version

```
Paste the output from `kargo version` here.
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by krancour** [comment]
Yep... totally misleading...

In my head it was parsed like:

```
(no available Freight "2d109e3b80ef548a12486fa9079c5419f2bc773e") found in namespace "kargo-guestbook"
```

This can 100% be improved.
