### ISSUE TITLE
UI: Surface promotion status in DAG

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#1207]
When a promotion fails, it should be obvious from the DAG view

**Comment by rbreeze** [comment]
Discussed with @jessesuen and decided that we will add a new field `status.lastPromotion` to accomplish this

**Comment by krancour** [comment]
I need to revisit the back end changes needed to enable this. They're not a high priority for me atm, but I wanted to note that it hasn't been forgotten. Assigning myself as co-owner of this issue with @rbreeze since progress is blocked on me.
