### ISSUE TITLE
Make project a flagged arg instead of a positional arg

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1209]
# Proposed Feature

Today, promoting CLI is like:

```
kargo stage promote kargo-guestbook dev --freight=abc123
```

Instead of project being a positional CLI arg, it should be a `--project` flag so that it's consistent with other commands. Also, we now support a project in the kargo context.

# Motivation

CLI would be simpler. I could do this instead:

```
kargo config set project kargo-guestbook
kargo stage promote dev --freight=abc123
```

# Suggested Implementation

**Comment by krancour** [comment]
:100:

I hate positional args in general because it's a burden to remember argument order.
