### ISSUE TITLE
Get available freight per stage, for all stages in QueryFreight API

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#1210]
Right now, when using the QueryFreight endpoint you can either get all freight in a project, or get available freight for one specified stage. We should support calling this endpoint once to get all available freight grouped by the stages they are available for. This would allow for eliminating API calls in the UI when going into promotion mode.

**Comment by krancour** [comment]
Something similar to this was discussed when implementing drag 'n' drop promotions and we came to the conclusion that a query such as this will perform too poorly as to be practical, and since we're getting by well without it, I'm going to close.
