### ISSUE TITLE
Support for Self signed https git repo

### ISSUE THREAD

**Issue by geowalrus4gh** [akuity/kargo#1224]
# Proposed Feature

Currently, kargo supports only https secure git repositories. In an air-gapped environment, insecure self-signed https endpoints may be required. 

# Motivation

For testing Kargo in air-gapped environments.

**Comment by krancour** [comment]
@jessesuen my first thought is to make this an opt-in at at the subscription level within the Warehouse resource type.

**Comment by jessesuen** [comment]
Yep that is the right place IMO
