### ISSUE TITLE
use cache for helm chart pulls

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1252]
This issue follows up on https://github.com/akuity/kargo-render/pull/225

Kargo almost never pulls charts. The _only_ scenario in which is does is if a warehouse is subscribed to a chart and a promotion mechanism is updating an "umbrella chart's" Chart.yaml with a reference to the new chart. In this one case, a `helm dependency update` command is executed and that does pull charts and could benefit from a chart cache.

That cache usually exists in a user's home dir.

The promotion mechanism, like most, does its work in a temporary directory, with `HOME` set to that directory. This means any cache that gets created is discarded when the promotion mechanisms completes its work. This strategy has also insulated use from the possibility that multiple `helm dependency update` processes running concurrently might encounter cache-related race conditions. (It is not clear whether this is a safe thing to do or not.)

https://github.com/akuity/kargo-render/pull/225 was a nice attempt by @Brightside56 to bring Helm's chart cache back into the picture, but being unaware of the nuances described about, it would not have had the desired affect.

This issue suggests a different approach to achieving the effect https://github.com/akuity/kargo-render/pull/225 was intended to bring about.

1. Mount a persistent volume to the controller at a location something like `/var/kargo/cache`.

1. Set `XDG_CACHE_HOME` to `/var/kargo/cache` when executing `helm dependency update`.

1. Due to uncertainty over the safety of multiple processes concurrently reading from / writing to that cache, employ a mutex to make execution of `/var/kargo/cache` a critical section of code.

Thank you to @Brightside56 for making me aware of this issue.

**Comment by jessesuen** [comment]
Increased to `size/medium` since I think shared cache dir between all tenants wont address the security concerns I have.

**Comment by jessesuen** [comment]
> Due to uncertainty over the safety of multiple processes concurrently reading from / writing to that cache, employ a mutex to make execution of /var/kargo/cache a critical section of code.

FWIW, this was a concern in Argo CD as well, and so we also tried protecting it with a lock. But I think we recently concluded that helm CLI might do the right thing and a lock was not necessary. But I might be mixing things up so we should test once again to make sure.

**Comment by Brightside56** [comment]
Discussion from https://github.com/akuity/kargo-render/pull/225 moved here. So:

1. Adding optional `persistence` (PV claim in chart)
2. Common cache dir (how about to `COPY --from` binaries from kargo-render image instead using it as base for Kargo docker image?)

right?

**Comment by krancour** [comment]
> Common cache dir (how about to COPY --from binaries from kargo-render image instead using it as base for Kargo docker image?)

@Brightside56 can you elaborate on what that would accomplish?

**Comment by Brightside56** [comment]
@krancour 
Kargo is a full-fledged application, while kargo-render is a dependency that performs its narrow function. I find strange that Dockerfile of Kargo extends Dockerfile of kargo-render.

I think Dockerfile and Helm chart of Kargo should be a source of truth for runtime (user, cache locations e.t.c.), then it may take binaries of kargo-render and use it as dependency

At the same time, the kargo-render can have its own minimalistic independent docker image can be used separately according its use cases, like CI job runs, in `COPY --from ...` purposes

It would be more straightforward and simpler. Or what am I missing?

**Comment by krancour** [comment]
> Kargo is a full-fledged application, while kargo-render is a dependency that performs its narrow function. I find strange that Dockerfile of Kargo extends Dockerfile of kargo-render.

Yes. I can see that may seem strange. It's just sort of how this evolved. Kargo Render was originally just part of Kargo. Later it was extracted into its own project. Kargo used to call Kargo Render as a library instead of a binary. Eventually, for reasons that aren't worth diving into here, we decided it was best to invoke the Kargo Render executable instead. At some point this odd decision was made because it was expedient at the time.

My question is really about connecting the dots between that change and any kind of Helm chart cache that Kargo can use.

**Comment by Brightside56** [comment]
@krancour I thought it's not supposed to connect the all dots now, but just to provide a possibility to have working cache directory with proper permissions to make Helm somehow working, and then security/tenant isolation concerns will be addressed on the side of application

I didn't managed to find any Kargo cache other than Helm cache (which resides in `/home/nonroot/.cache/helm`) and `/tmp` directory (which contents I think produced by kargo-render). Is there separate Kargo-specific cache directory?

**Comment by krancour** [comment]
@Brightside56 

> The promotion mechanism, like most, does its work in a temporary directory, with HOME set to that directory. This means any cache that gets created is discarded when the promotion mechanisms completes its work.

The only cache is completely ephemeral, as `HOME` points to a temporary directory during a promotion.

**Comment by Brightside56** [comment]
@krancour then I think I don’t have enough knowledge of the internals. But... Helm charts are just templates which normally shouldn't contain any sensitive info. If user relying to Kargo for orchestrating Helm charts, then he/she trusts Kargo from this point (storing Helm chart contents somewhere in container). Also this can be parametrized. Taking into account that Helm chart cache is something immutable, there could be HOME location for each tenant + project with scheme like `$HOME/helm/<freight_sha>/<chartname-chartversion_sha>`, where `$HOME` is somewhat like `/var/kargo/cache/<tenant_sha>/<project_sha>`. Git cache could reside in `/var/kargo/cache/<tenant_sha>/<project_sha>/git/...`

**Comment by krancour** [comment]
> Helm charts are just templates which normally shouldn't contain any sensitive info. If user relying to Kargo for orchestrating Helm charts, then he/she trusts Kargo from this point (storing Helm chart contents somewhere in container).

Ordinarily, I would agree that charts should not include sensitive information, but there can be no guarantee that users don't violate that practice.

Also, even without sensitive information in a chart, if the chart is private, there is an expectation that it's inaccessible to other parties. If a shared cache undermines that expectation, that's a problem.

Separate caches per project _does_ seem more viable.
