### ISSUE TITLE
Freight filtering rules

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1270]
# Proposed Feature

Subscribing to a git repository can be, in many cases, very noisy and will produce inconsequential freight. Examples include:
* mono repos where there are other directories of unrelated apps
* changes to README.md or unrelated files

Warehouses should allow users to define rules so that only when certain paths are changed, should new freight be generated. e.g. suppose for a kustomize layout, maybe only changes to these directories should produce freight:

```
apps/
  guestbook/
    base/
    overlays/
```

# Motivation

This will improve usability and filter out noise in the Freightline

# Suggested Implementation

Warehouse API spec should introduce a new stanza on filtering rules. Before generating new Freight, it will see if the filtering rules apply and produce Freight accordingly.

NOTE: if we support git webhooks, the git webhook will have information about files that changed. This would avoid a git checkout. But I consider this an optimization and we shouldn't rely on this because we might miss a webhook.

**Comment by maksimstankevic** [comment]
@krancour @jessesuen I was looking for a new, bit bigger issue, can I pick this one? I have limited free time off work and not sure how long this will take me but if it's fine - really interested to work on this.

**Comment by krancour** [comment]
@maksimstankevic have at it. We're happy for your assistance!

If I may suggest, simply on account of this being a somewhat complex change, if @jessesuen or myself can review the additions to the Warehouse CRD before you move ahead with corresponding changes to the controller, I think it would help to make sure we're all on the same page early in the process.

**Comment by maksimstankevic** [comment]
@krancour @jessesuen could you please check and comment, https://github.com/akuity/kargo/compare/main...maksimstankevic:kargo:feature/1270. I thought we could use similar approach as with AllowTags/IgnoreTags in ImageSubscription but use list of regexps in both GitSubscription's ScanPaths and IgnorePaths for more flexibility.

**Comment by krancour** [comment]
@maksimstankevic I am so sorry for the delayed review. I think that is a good starting point.

**Comment by maksimstankevic** [comment]
@krancour, hey, I submitted https://github.com/akuity/kargo/pull/1477 for this one, please, take a look when you have a sec

**Comment by krancour** [comment]
This was closed by #1477
