### ISSUE TITLE
Remote Cluster Kargo instance integration

### ISSUE THREAD

**Issue by geowalrus4gh** [akuity/kargo#1273]
# Proposed Feature

Currently, Kargo supports in-cluster integration with ArgoCD. Kargo updates ArgoCD apps available in the local cluster only. In our organization production clusters are completely isolated from the development area. Production area has its own ArgoCD instance. In this case, only git repo can be shared across the dev and prod areas. What must be the best practice in this case? 

# Motivation

Is there any possibility of getting a complete life cycle visibility in this case?

# Suggested Implementation

Two kargo instances in two areas communicate with each other and share the freight line travel path so that a continuous line from dev to prod may be possible.

**Comment by krancour** [comment]
Hi @geowalrus4gh! 

Your use case is perfectly valid, but this proposed implementation has been brought up before and rejected on security and scalability grounds. This is a lesson learned from Argo CD -- that a hub and spoke model wherein the hub has credentials for remote clusters, although convenient, puts a large burden on a single controller and makes the hub a high value target, which, if compromised, transitively compromises the remote clusters it connects to.

What we are doing instead, which addresses your use case _without_ the scalability and security concerns, is a model wherein Kargo can be sharded, with Kargo controllers distributed 1:1 with the clusters running your Argo CD control planes. The distributed controllers use two k8s clients, one for talking to a central, remote Kargo control plane (situated in a "management cluster," perhaps), and a second for talking to the local cluster on which both it and the Argo CD control plane are situated.

We are building with this topology always in mind, but there are a few caveats:

* We haven't tested it extensively in this configuration; I'm certain there are issues that need to be addressed
* It's not easy to set up
* The team isn't in a place right now where we have the bandwidth to assist anyone who is trying to implement this topology

With all that said, anyone is, of course, welcome to experiment with running it this way. 😄
