### ISSUE TITLE
Warehouse helm subscription is not working

### ISSUE THREAD

**Issue by geowalrus4gh** [akuity/kargo#1280]
# Description

In the document, it is specified that kargo supports helm subscription for the warehouse. But when i tried this use case, freight box is detected when a new chart version comes up. But no version information is displayed. Also when promoted, stages shows promoted but no commits there in the git branch. Here is the warehouse.yaml

    apiVersion: kargo.akuity.io/v1alpha1
    kind: Warehouse
    metadata:
      name: kargo-demo
      namespace: kargo-demo
    spec:
      subscriptions:
      - chart:
          registryURL: oci://docker.io
          name: xyz/kargo-demo-app-charts
          semverConstraint: ^0.1.0

# Screenshots
![image](https://github.com/akuity/kargo/assets/33422391/b7f9dd21-27b4-4771-b508-d01fa2b5a27a)

# Version

```
v0.2.1
```

# Logs

```
No special logs
```

**Comment by krancour** [comment]
Hi @geowalrus4gh.

> freight box is detected when a new chart version comes up. But no version information is displayed.

This is a UI issue. cc @rbreeze 

> Also when promoted, stages shows promoted but no commits there in the git branch

I'd need to see what kind of promotion mechanisms you're using and whether they may be misconfigured.

**Comment by krancour** [comment]
> I'd need to see what kind of promotion mechanisms you're using and whether they may be misconfigured.

Nevermind. I see that's in #1281.

**Comment by rbreeze** [comment]
@geowalrus4gh Can you confirm that this bug is still present for you in `main` (or 0.5.0)? I see you were running `v0.2.1` when you encountered it
