### ISSUE TITLE
Add additional information to Stage History

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#1290]
**Background**
In the UI DAG view, we'd like to indicate Stages whose most recent promotions failed (see https://github.com/akuity/kargo/issues/1207). The only way to do this today is to call the `ListPromotions` API repeatedly for each Stage, which would be too resource intensive for medium- to large-scale projects.

**Solution**
Right now, the `history` field in `StageStatus` is simply an array of the 10 most recent freight. We will expand this to include information about the Promotion associated with each Freight.

**Comment by krancour** [comment]
@rbreeze wanted to confirm you still need this.

**Comment by krancour** [comment]
I've just realized this may not work. A failed Promotion won't result in a new history entry in the Stage status. This means history is just going to show successful Promotions. 🤦‍♂️ 

We may need to rethink this.

**Comment by rbreeze** [comment]
Fixed by https://github.com/akuity/kargo/pull/2109
