### ISSUE TITLE
Multiple subscriptions use case with Image and Git

### ISSUE THREAD

**Issue by geowalrus4gh** [akuity/kargo#1313]
# Description

What exactly is happening when I configure multiple subscriptions - one with image and another with git,  as given below?

      `kind: Warehouse
      metadata:
        name: kargo-demo
        namespace: kargo-demo
      spec:
        subscriptions:
        - image:
            repoURL: xyz/kargo-demo-app
            semverConstraint: ^0.1.0
        - image:
            repoURL: xyz/kargo-show-app
            semverConstraint: ^0.0.0
        - git:
            repoURL: https://github.com/xyz/kargo-demo-deploy.git`

And I have a stage promotion as follows.

      `apiVersion: kargo.akuity.io/v1alpha1
      kind: Stage
      metadata:
        name: test
        namespace: kargo-demo
      spec:
        subscriptions:
          warehouse: kargo-demo
        promotionMechanisms:
          gitRepoUpdates:
          - repoURL: https://github.com/xyz/kargo-demo-deploy.git
            writeBranch: stage/test
            helm:
              images:
                - image: xyz/kargo-demo-app
                  valuesFilePath: helm/stages/test/values.yaml
                  key: "kargo-demo-app-charts.image.tag"
                  value: Tag
                - image: xyz/kargo-show-app
                  valuesFilePath: helm/stages/test/values.yaml
                  key: "kargo-show-app-charts.image.tag"
                  value: Tag
      
          argoCDAppUpdates:
          - appName: kargo-demo-test
            appNamespace: argocd
      `
Here, updates coming to the git repository is able to promote. But when a new image is released and promoted from kargo, its not taking effect. Target 'test' branch is not getting updated with the latest released image. I suspect the update being overridden by the old version in the master branch. 

Any pointers ? or is it an invalid configuration?

# Logs

No relevant logs

**Comment by krancour** [comment]
@geowalrus4gh the keys in your values files look suspicious to me...

**Comment by geowalrus4gh** [comment]
Here is the values.yaml

# Default values for sprout-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

    globals:
      kargo-demo-app-charts:
        enabled: true
    
    kargo-demo-app-charts:
      image:
        tag: "0.1.20"
      replicaCount: 1
    kargo-show-app-charts:
      image:
        tag: "0.0.3"
      replicaCount: 1

**Comment by krancour** [comment]
@geowalrus4gh 

It's probably your semver constraints:

```yaml
    - image:
        repoURL: xyz/kargo-demo-app
        semverConstraint: ^0.1.0
    - image:
        repoURL: xyz/kargo-show-app
        semverConstraint: ^0.0.0
```

The third-party semver package was recently upgraded and they fixed a bug regarding improper interpretation of the `^` comparison operator for versions < `1.0.0`.

It is likely that with this fix, your warehouse cannot select anything newer than `xyz/kargo-demo-app:0.1.x` and `xyz/kargo-show-app:0.0.x`.

One of our own teammates was bit by this very issue just last night and that's when it came onto my radar.

References:

* How it's supposed to have worked: https://github.com/masterminds/semver#caret-range-comparisons-major

* The bug: https://github.com/Masterminds/semver/issues/180

* The fix: https://github.com/Masterminds/semver/pull/181

* Where we the fixed version made its way into Kargo: https://github.com/akuity/kargo/pull/1255

If you update those expressions, it will likely solve your problem.

Please lmk if this works.

**Comment by geowalrus4gh** [comment]
It worked after the change as below.

      spec:
        subscriptions:
        - image:
            repoURL: xyz/kargo-demo-app
            semverConstraint: ^0
        - image:
            repoURL: xyz/kargo-show-app
            semverConstraint: ^0

**Comment by krancour** [comment]
Opened https://github.com/akuity/kargo/issues/1342
