### ISSUE TITLE
Install kargo CLI not working on Mac M2

### ISSUE THREAD

**Issue by zbialik** [akuity/kargo#1333]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Followed Kargo Quickstart doc and after completing the Install CLI section, whenever I execute the kargo binary I just get the following response:
```
✗ kargo
load config: please use `kargo login` to continue: no configuration file was found at "/Users/zbialik/.config/kargo/config"
```
# Screenshots
N/A

# Steps to Reproduce

1. Follow Install CLI section on Mac M2
```
arch=$(uname -m)
[ "$arch" = "x86_64" ] && arch=amd64
curl -L -o kargo https://github.com/akuity/kargo/releases/latest/download/kargo-$(uname -s | tr '[:upper:]' '[:lower:]')-${arch}
chmod +x kargo
```
3. Attempt executing `kargo` binary

# Version

I honestly can't be sure because the download link just points to latest and there's nothing else I am seeing that would indicate a version. 
```
✗ kargo version
load config: please use `kargo login` to continue: no configuration file was found at "/Users/zbialik/.config/kargo/config"
```

# Logs
N/A

**Comment by krancour** [comment]
You were running into #1341

**Comment by zbialik** [comment]
@krancour Ahh thank you. I think I saw it had started working after I created a `Namespace` with the label required for denoting it as a Kargo `Project`.
