### ISSUE TITLE
docs: link to docs on semantic version constraint expressions

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1342]
Link from our docs to documentation on semantic version constraint expressions.

https://github.com/masterminds/semver#checking-version-constraints

**Comment by krancour** [comment]
The best places for this may comments on the applicable CRD fields (these will work their way into CRDs reference docs) and a info box below any example in the quickstart or concepts doc that uses a semver constraint.

**Comment by webstradev** [comment]
I'll pick this up.

For the info box in the docs I was thinking something like:
:::info
Kargo uses [SemVer](https://github.com/masterminds/semver#checking-version-constraints) to check handle semantic versioning constraints.
:::

below any example that includes a constraint.
