### ISSUE TITLE
cli: refactor "stage management" sub-commands

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1352]
Related to #1163, but specifically about two particular commands.

From #1163:

> Some commands are of the form `<verb>` `<resource>`, while others are of the form `<resource>` `<verb>`

The `stage` sub-command is one specific area where there is room for improvement.

The `stage` sub-command has the following sub-commands of its own:

* disable-auto-promotion
* enable-auto-promotion
* promote
* promote-subscribers

A major theme of the v0.4.0 release is "project management" and calls for both the creation of a `Project` CRD and additional `PromotionPolicy` options. (See [roadmap](https://kargo.akuity.io/roadmap#v040).

~~I foresee `PromotionPolicy` collapsing into the new `Project` CRD, in which case, dedicated `disable-auto-promotion` and `enable-auto-promotion` commands begin to make even less sense than they do already.~~ __This is done.__ The ability of `Freight` to be auto-promoted to any given `Stage`s in a given project to would simply be managed through edits to `Project` resources. i.e. These sub-commands will likely go away in this development cycle.

That leaves `promote` and `promote-subscribers`. There is room for two improvements here:

1. They could be collapsed into a single sub-command, which could be used as follows:

    `kargo promote --freight <freight> --stage <stage>`
    
    OR
    
    `kargo promote --freight <freight> --subscribers-of <stage>`
    
    Where precisely _one_ of `--stage` or `--subscribers-of` must be specified.

1. They can be lifted out from under the `stage` sub-command to fix a violation of our verb-first approach.

    Besides improving overall consistency, this also just makes more sense... promotions always involve a piece of Freight being promoted _to_ a Stage and it was arbitrary that these commands were buried under "stage management" when Freight is an equally important part of the promotion process.

**Comment by hiddeco** [comment]
> The ability of `Freight` to be auto-promoted to any given `Stage`s in a given project to would simply be managed through edits to `Project` resources. i.e. These sub-commands will likely go away in this development cycle.

Should this be removed as part of _this_ refactor, or is there something else which should go first before it can actually be removed?

**Comment by krancour** [comment]
Oh... now, looking at #1535, I am wondering if you were actually inquiring about removing the corresponding endpoints as well.

Yes... still totally fine with that.

**Comment by hiddeco** [comment]
I was _initially_ just wondering about the commands, but then figured this would result into dead endpoints which did not appear to be used anywhere -- so I took the liberty to remove those as well.
