### ISSUE TITLE
Execute `AnalysisRun` in target cluster

### ISSUE THREAD

**Issue by moensch** [akuity/kargo#1363]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Love that `AnalysisTemplate` support got added. However, the cluster our Argo CD runs on (and in the future, Kargo) doesn't necessarily have access to the in-cluster prometheus endpoint, or to in-cluster `Service` endpoints needed to run e2e tests.

It would be awesome if Analysis could be executed on the **destination** cluster instead of in the Kargo cluster/namespace. I know I could work around this by essentially invoking a Job with a kubeconfig that in turn invokes another Job on the remote cluster. But that seems... kludgy.

# Motivation

Run in-cluster end-to-end tests against deployed services. And being able to access in-cluster `Service` endpoints such as prometheus, which might not necessarily be publicly exposed via Ingress.

# Suggested Implementation

Kargo could borrow Cluster Secrets from Argo CD? Though that would make it difficult in light of future "remote argo cd support".

It'll also muddy the lines between Argo CD and Kargo even further.

Here's an alternative suggestion - add AnalysisTemplate support to Argo CD post-sync hooks :)

**Comment by krancour** [comment]
@moensch do you think https://github.com/akuity/kargo/issues/1359 would take care of your needs? I'm actually going to be working on that today.

**Comment by moensch** [comment]
I _think_ so? Or at least, it'll get us steps closer to that. I too will have to start wrapping my head around sharded controllers for a bit.
