### ISSUE TITLE
Project CRD + namespace naming prefix

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1389]
# Proposed Feature

We are very soon going to have a Project CR which will create a kargo project namespace underneath.

Because namespace name == project name, ATM users are limited on what they can name their projects and have to coordinate their project names with what's in the cluster. For example, they would never name it: `default`, `kube-system`, or collide it with maybe the name of a service in the cluster that occupied the same name, e.g. `istio`, `guestbook`.

What if kargo supported a namespace name prefix on all namespaces it created as a result of a Project. By convention, I've actually started prefixing my kargo namespaces with `kgo-`, e.g. `kgo-guestbook` as to avoid collisions with the actual workload namespace for the service `guestbook`. But what if this was formalized?

So the UX is that users may create a Project named `guestbook`, but underneath, the namepace it created was `kgo-guestbook`.

# Motivation

This would allow users more freedom to name kargo projects without worrying about existing workload namespaces

# Suggested Implementation

**Comment by gdsoumya** [comment]
Can we make it more explicit and have the prefix as `kargo-` it's 2 characters more than `kgo` but is more obvious. WDYT?

**Comment by jessesuen** [comment]
Good point. The only thought I had about that, is if `kgo-` might have less of a chance to collide with something existing if they are incorporating `kargo-` into namespaces for other purposes, such as: `GLOBAL_CREDENTIALS_NAMESPACES=kargo-global`. In this case, a project named `global` could not be created (which is fine). But I think this point is a minor one compared to which prefix is maybe more clear (which would be `kargo-`).

This does lead me to another question on whether:
1. Should a `kargo-` or `kgo-` name prefix be the default/only behavior
2. Is the prefix even configurable by users, or do we want everyone to use the same convention

There are merits to global consistency/convention across all users, and I'd like to avoid too much option/flexibility, since it can lead to a more complicated implementation and problems down the road.

**Comment by gdsoumya** [comment]
I think it makes sense to have it as a default, as the namespaces are managed by the controller I think it would be fine to be make it a standard.

**Comment by krancour** [comment]
Close it? I vote yes.

**Comment by gdsoumya** [comment]
Just an idea, I like how in argocd you can create apps and specify the project if you want to scope the permissions. What do you think about removing namespace from all other kargo resources like stages/warehouses etc. and putting the project field in there instead. Then kargo admission controller can patch the resources with proper namespace and deploy them. This goes well with the gitops approach as well because users no longer have to think at 2 levels like kargo specific Project and then k8s specific namespaces. Everything is moved to only kargo related resources even though they are tied to real k8s resources.

**Comment by krancour** [comment]
@gdsoumya I had the same thought, but then realized that there are a lot of scenarios where this would still be awkward. A good example is that it's common to put non-Kargo things like Secrets, ServiceAccounts, RoleBindings, etc. in a Project namespace. In such cases, where cannot add a Project field to the resource type, our choices would be:

* Users use the `namespace` field as usual: "Thinking at two levels" remains a problem and awareness of Kargo's naming conventions for project namespaces would be required.

* We use an annotation: Which seems like a worse UX than using the `namespace` field.

If we did decide to circle back on this someday, what you've proposed is exactly what I'd want to consider as a starting point and then see if we can resolve the problems mentioned above, but for the moment, I'm not feeling like we should pursue this.

**Comment by jessesuen** [comment]
Agree. Let's close this.
