### ISSUE TITLE
UI for managing credentials

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1444]
# Proposed Feature

Kargo needs credentials for things like:
* git repositories
* container repositories

Since they are Secrets, it becomes tricky to manage via GitOps. The UI should provide an imperative way to:
1. input credentials into a project namespace
2. view what credentials are available (not the actual sensitive content) and for which repositories

# Motivation

Although managing credentials declaratively with things like external-secrets would be preferred, having an imperative way to do this would help with people getting started with kargo, developer self-service, etc...

Plus, having visibility in the UI to what credentials are available would be useful in and of itself.

# Suggested Implementation

In the project view, have a credentials tab where this could be inputted and listed, but without exposing/returning any sensitive content.

**Comment by jessesuen** [comment]
Additional requirements:

If global credentials are set. The UI should also present this as well.

**Comment by wanghong230** [comment]
this could be a blocker for customer demo

**Comment by jessesuen** [comment]
Reopening since UI work not done

**Comment by krancour** [comment]
Sorry... it was quite by accident that I listed #1566 as closing this issue.

**Comment by krancour** [comment]
This was closed by #1710
