### ISSUE TITLE
Warehouse subscription image semverConstraint showing only very last tag

### ISSUE THREAD

**Issue by bygui86** [akuity/kargo#1465]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

In the CRD reference it's specified that kargo supports semver for the container image (looking into the code I see based on https://github.com/Masterminds/semver), but when I tried the below Warehouse I got only and always the very last tag, even if the constraint is way broader.
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - image:
      repoURL: nginx
      semverConstraint: ^1
      # or
      # allowTags: "[0-9]*.[0-9]*.[0-9]*"
```
Actually kargo should present way more tags...
Is it an expected behaviour?
What about document more the Warehouse available fields and how it works?

# Screenshots

![image](https://github.com/akuity/kargo/assets/22518997/b95079ef-2554-4491-9df2-4dba0a56baf6)

# Steps to Reproduce

I followed the kargo quick-start guide [in the documentation](https://kargo.akuity.io/quickstart).

# Version

```
Client Version: v0.3.2
Server Version: v0.3.2
```

# Logs

```
No special logs in any of the kargo pods
```

**Comment by krancour** [comment]
> but when I tried the below Warehouse I got only and always the very last tag, even if the constraint is way broader.

@bygui86 I'm not sure if I am misinterpreting you... the point of a warehouse is to select _one_ version from each artifact (image, config, chart) repo you subscribe to. The SemVer selection strategy picks _the latest_ that matches the constraint.

There are docs on all fields here:

https://doc.crds.dev/github.com/akuity/kargo

**Comment by bygui86** [comment]
@krancour you mentioned also:

> There are docs on all fields here: https://doc.crds.dev/github.com/akuity/kargo

In which is written (Warehouse > subscriptions > images > semverConstraint):

> SemverConstraint specifies constraints on what new image versions are permissible. The value in this field only has any effect when the TagSelectionStrategy is SemVer or left unspecified (which is implicitly the same as SemVer). This field is also optional. When left unspecified, (and the TagSelectionStrategy is SemVer or unspecified), there will be no constraints, which means the latest semantically tagged version of an image will always be used. Care should be taken with leaving this field unspecified, as it can lead to the unanticipated rollout of breaking changes. Refer to Image Updater documentation for more details.

`SemverConstraint specifies constraints on what new image versions are permissible.` and `This field is also optional. When left unspecified, (and the TagSelectionStrategy is SemVer or unspecified), there will be no constraints, which means the latest semantically tagged version of an image will always be used.` are in contrast to what you wrote above `the point of a warehouse is to select one version from each artifact (image, config, chart) repo you subscribe to. The SemVer selection strategy picks the latest that matches the constraint.`
So how kargo use the Masterminds/semver library?

I would like to highlight an important point: CRD reference is absolutely important, but it cannot replace a good documentation explained in a more extended way and providing examples!
Anywhere in https://kargo.akuity.io I can't find any example of how to use a Warehouse in details or any example of how to use `semverConstraint` or `allowTags` or `ignoreTags` or else...

**Comment by krancour** [comment]
> Then 1 Warehouse 1 version... then how can I subscribe for multiple versions (for example multiple container image tags)? 

I think there may be a fundamental misunderstanding about the sort of use cases Kargo is intended to address.

If what you want to do is explicitly deploy _one_ specific version of an image, you don't really need to involve Kargo. Or at least you don't need to involve it in watching images.

Kargo is for watching for new versions of images (or manifests or charts) _over time_. A semantic version constraint of `^1.24.0`, for instance, does not express an interest in _all_ versions `1.x.y`. It expresses a desire to create new freight when a _new_ version appears in the top of that range.

A meaningful comparison could be made to a `package.json` file (or the dependency manifest for pretty much any package manager). I don't believe anyone interprets`"react": "^18.2.0"` as a dependency on _all_ versions of react in the `18.x.y` range, rather, it is well understood to express a dependency on _one_ version at the top of that range.

> CRD reference is absolutely important, but it cannot replace a good documentation explained in a more extended way and providing examples!

I 100% agree, but I ask that you not lose sight of the fact that Kargo is _alpha-level_ software right now and we're not done making breaking changes. Having useful docs without overcommitting effort to things that are likely to change feels, at times, like a delicate balancing act. The situation will improve incrementally as Kargo matures. In the meantime, the CRD docs are, at least, always up to date.

**Comment by bygui86** [comment]
@krancour thanks for the explanation! Now usage of Warehouse is a bit more clear!

> Kargo is for watching for new versions of images (or manifests or charts) over time. A semantic version constraint of ^1.24.0, for instance, does not express an interest in all versions 1.x.y. It expresses a desire to create new freight when a new version appears in the top of that range.

Just to be sure, so after creating the Warehouse I can expect to grab all new container image versions once released, right?

> I 100% agree, but I ask that you not lose sight of the fact that Kargo is alpha-level software right now and we're not done making breaking changes. Having useful docs without overcommitting effort to things that are likely to change feels, at times, like a delicate balancing act. The situation will improve incrementally as Kargo matures. In the meantime, the CRD docs are, at least, always up to date.

Got it thanks. I thought kargo was in a bit more advanced stage, something like closer to beta :)

**Comment by krancour** [comment]
> Just to be sure, so after creating the Warehouse I can expect to grab all new container image versions once released, right?

After creating a new Warehouse, you can expect to immediately get one Freight containing the one image at the top of the specified range. _After_, and on an ongoing basis, you'll get a new Freight with the _new_ image at the top of the specified range each time one is pushed.

> I thought kargo was in a bit more advanced stage, something like closer to beta :)

We're inching toward that, so you can expect us to step up our docs game quite a bit very soon.

**Comment by stephaneetje** [comment]
Hello
I'm facing a similar situation, weirdly, it gets a 7 days old image, while there are about ten new since.

```
spec:
  subscriptions:
  - image:
      imageSelectionStrategy: SemVer
      repoURL: europe-docker.pkg.dev/test-infra112/ns/app
```

I only see one old image `v2.108.0-f467ee7`, and nothing else, new images have been pushed since it is running...
 
<img width="1397" alt="Capture d’écran 2024-02-28 à 20 56 35" src="https://github.com/akuity/kargo/assets/73826402/0125c71d-f17d-4818-9438-d3d400ae1b13">

You can see it is the 12th image in the list:

<img width="851" alt="Capture d’écran 2024-02-28 à 20 56 09" src="https://github.com/akuity/kargo/assets/73826402/cef4b3b7-8a02-4003-ac88-0f01464cfc21">

**Comment by krancour** [comment]
@stephaneetje you're selecting the image with the highest semantically versioned tag. That's `v2.108.0-f467ee7`, which semantically speaking, is newer than your newest image (`v2.108.0-e82fd8e`).

**Comment by stephaneetje** [comment]
I'm trying to select anything but tags ending with -$ShortSHA, i used `NewestBuild` strategy with following configuration :
```
  subscriptions:
  - image:
      imageSelectionStrategy: NewestBuild
      ignoreTags:
        - ^v.*-[0-9a-z]{7}$
```

But it keeps selecting an image with a ShortSHA, as if my ignoreTags field isn't effective.

**Comment by krancour** [comment]
> Strange it isn't supported as it is apparently for allowTags.

That's a relic of Image Updater. We used to use Image Updater as a library for selecting images. That's what they support -- regex for allow and list for ignore. I'm not sure why they did it that way.

We could think about changing that, but I wouldn't rush into that change. The way I have seen it until now is this:

1. Use a regex to say what you _allow_
2. Use ignores to make specific exceptions to the regex without needing to _complicate_ the regex

For your case, I think something like this works:

```
spec:
  subscriptions:
  - image:
      repoURL: europe-docker.pkg.dev/test-infra112/ns/app
      imageSelectionStrategy: SemVer
      allowTags: '^v\d+\.\d+\.\d+$'
```

That will select the semantically latest version from tags that _don't_ have anything after the patch version.

**Comment by stephaneetje** [comment]
Thanks for your reply!
It doesn't suit my needs, because i just want to exclude 'vx.x.x-0123456', but the other tags with `-` are still needed, for exemple i have a tag `v2.0.8-RC1`.

**Comment by krancour** [comment]
I would guess the range of acceptable patterns after the dash isn't infinite except for those resembling a short sha.

If that is so, it should be easy enough to do, right?

`allowTags: ^v\d+\.\d+\.\d+(-(ALPHA|BETA|RC)(\.\d)?)?$`
