### ISSUE TITLE
PR promotion doesn't create any PR, without any error in logs

### ISSUE THREAD

**Issue by jizusun** [akuity/kargo#1487]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
I see the PR promotion in the roadmap page, and found the PR 
https://github.com/akuity/kargo/pull/1274

I tried to follow the PR description to setup, but it doesn't create a PR
The detail can be check in the `steps to reproduce` section

# Screenshots

# Steps to Reproduce
1. change the `stage`: https://github.com/jizusun/kargo-demo/blob/05a8dc00299224af3b82795a7875fd5bd01ce1c1/kargo-manifests/stage.yml#L48-L51
2. apply the `stage`: `kubectl apply -f stage.yml`
3. promote the freight
```sh
➜  kargo-demo git:(main) kargo get freight --project kargo-demo                             
NAME/ID                                    ALIAS               AGE
9e8432ec81524f232028a0bc752bd54822fc3dcb   melting-billygoat   17h
7503447ce380195c56d640da7e9d45ecd70194c0   torpid-zorse        38m
➜  kargo-demo git:(main) echo $FREIGHT_ID                      
7503447ce380195c56d640da7e9d45ecd70194c0
➜  kargo-demo git:(main) kargo stage promote --project kargo-demo test --freight $FREIGHT_ID


Promotion Created: "test.01hpwm7w79dmy0z2m2j9xqrk2j.7503447"
```
4. The UI shows the promotion is successful
![image](https://github.com/akuity/kargo/assets/4011348/61d99b2c-9fd9-477a-8af4-10eb73175d29)

5. No PR is created: https://github.com/jizusun/kargo-demo/pulls

# Version

```
➜  git-repos kargo version
Client Version: v0.3.2
Server Version: v0.3.2```

# Logs

![image](https://github.com/akuity/kargo/assets/4011348/5591fab9-5679-4306-9f4c-06ea492adb19)


```

```

**Comment by krancour** [comment]
Hi @jizusun. Thanks for reporting this!

I glanced at your manifests and didn't see any obvious problems. I will attempt to reproduce it on Tuesday. (Monday is a US holiday.)

In the meantime, there are a couple things to try:

1. If you examine the live state of the Promotion via `kubectl`, do you see any error message somewhere under the status sub-resource? I just want to rule out the possibility that the UI is simply failing to surface an error that's described in there.

2. I know you saw no errors in the logs, but I am wondering if you happen to have debug level logging enabled for the controller? Or if not, would you be able to enable it? It might give us additional clues.

**Comment by jessesuen** [comment]
Not sure if this is the case, but if it turns out the PR generated no change, then it's automatically considered successful. This can be verified by hovering over the green checkbox icon (which perhaps probably should surface messages better).

<img width="233" alt="image" src="https://github.com/akuity/kargo/assets/12677113/53f69291-67ec-4b4e-a095-2f846a0555e2">

**Comment by krancour** [comment]
This has been open a while with no response from the OP, so I am closing, but @jessesuen's comment above is a plausible  explanation for anyone who encounters something similar. Enabling debug logs would help to confirm it.
