### ISSUE TITLE
distribution/distribution v3 deprecates packages we use

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1488]
I had to close #1461 because it breaks the build.

We use [distribution/distribution](https://github.com/distribution/distribution) for interacting with container registries.

In their upcoming v3 release, they've moved the entire `client` package and its sub-packages under `internal/`, making it now inaccessible to us.

This issue discusses:

https://github.com/distribution/distribution/issues/4119

From my reading of that issue, it may be _temporarily_ internal until it's been iteratively improved to a point where it becomes a publicly available and supported package of some future v3.x. But this is speculative.

Guidance seems to be that there is no harm in using v2 packages in the interim, but I also understand there to be a goal of EOL'ing v2 once v3 is GA. (In reality, we are actually using a "v3" that references the last commit to trunk prior to this change.)

This leaves me scratching my head as to what the official/recommended registry client is between v2 EOL and the speculative re-(re-)lease of a publicly available replacement.

I don't think there's much to do at this point other than keep an eye on the situation. If worse comes to worst, we have some options like forking it or copying their internal package into our own repo.

I just didn't want to lose track of this.

**Comment by hiddeco** [comment]
Based on reading the discussion, it seems they have ended up on agreeing to not have a client implementation in v3 _at all_, while _maybe_ adding something back in v4. Other comments in the referred issue also suggest that some dependents are in the progress of moving to the containerd implementation ([v1](https://github.com/containerd/containerd/tree/v1.7.13/remotes), [upcoming v2](https://github.com/containerd/containerd/tree/33e544e94a67e3ac5c261101885773e2593cc923/core/remotes)).

Given relying on something which is unmaintained can put you in a very bad spot at an unexpected time, I think the safer option would be to look for an implementation which is actually maintained and has a fair number of adopters. This would either probably mean the containerd implementation (which is already a dependency, and [quite actively used](https://github.com/search?q=containerd%2Fremotes&type=code), or something like [go-containerregistry](https://github.com/google/go-containerregistry) (a [popular alternative](https://github.com/search?q=go-containerregistry&type=code)).
