### ISSUE TITLE
Stage shard assignment

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1537]
@jessesuen since the UI currently only allows adding/editing Stages using a YAML editor with schema-aware context help, I'm wondering if/how we were imagining this is done any differently than by simply adding the correct label to the YAML.

Tangent...

For something this important, I don't totally love relying on a label that, let's be honest, people are going to have to _look up_... and that's if they're even aware of its existence in the first place.

I'd be in favor of a separate issue for adding a proper shard field to the StageSpec. The label is still useful for internal reasons, but we could modify the webhook to make the label always match the value in the new shard field. wdyt?

**Comment by krancour** [comment]
> I'd be in favor of a separate issue for adding a proper shard field to the StageSpec. The label is still useful for internal reasons, but we could modify the webhook to make the label always match the value in the new shard field. wdyt?

@jessesuen I had been meaning to propose the same. I will open a separate issue for it.

**Comment by krancour** [comment]
> For something this important, I don't totally love relying on a label that, let's be honest, people are going to have to look up... and that's if they're even aware of its existence in the first place.
> 
> I'd be in favor of a separate issue for adding a proper shard field to the StageSpec. The label is still useful for internal reasons, but we could modify the webhook to make the label always match the value in the new shard field. wdyt?

This was fixed in #1582 and I am wondering if it reduces _this_ issue in priority.

**Comment by jessesuen** [comment]
Yes, now that we have a shard as part of the spec, we can probably close this
