### ISSUE TITLE
Warehouse creation wizard

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1538]
Current the UI has no feature for creating a new Warehouse.

@jessesuen, "wizard" was your wording. Could we guess that initially, this isn't more than was done for creating Stages? i.e. Pop open a YAML editor with example YAML and schema-aware context help?

**Comment by jessesuen** [comment]
> @jessesuen, "wizard" was your wording. Could we guess that initially, this isn't more than was done for creating Stages? i.e. Pop open a YAML editor with example YAML and schema-aware context help?

Yes, YAML editor would be an MVP. 

That said, I think Warehouses and Projects (unlike Stages), have less options to configure, and so I do feel it's possible to create a simplified UX around it (even if it means they are unable to create more advanced Warehouses). The YAML editor will always be our escape hatch for more advanced config.

**Comment by krancour** [comment]
Agree that Stages are the main difficulty and others have potential to be bound to a form or other UI controls. YAML editor for MVP sgtm. Thank you.

**Comment by Marvin9** [comment]
I was about to create an issue for warehouse wizard. I think it would be good to have it in v1.0?
