### ISSUE TITLE
proposal: update credential storage strategy

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1546]
Argo CD has always used the label `argocd.argoproj.io/secret-type` with value `repository` or `repo-creds` on Secrets to indicate that they are either:

1. Credentials for one specific repository (`repository`)
1. Credentials multiple repositories, all starting with the same URL prefix (`repo-creds`)

The label name changed, but Kargo copied this strategy almost exactly. Even at the time I did that, I felt this was confusing and have since found that others are also confused by it.

Confusion stems from:

* _Both_ label values indicate a Secret represents credentials, but one has "creds" in its name and the other doesn't. 🤔 
* One label values indicates a Secret represents something akin to a "credential template," but nothing in the label value hints at such behavior.
* Apart from these labels, a Secret's `data.type` field is used to with a value like `git`, `helm`, or `image` to denote what kind of repository the credentials are for. Overuse of "type" contributes to confusion.

I'm sure Argo CD has rational reasons for why it is this way, but seeing the confusion it can cause at times, and given that credential management features (#1523, #1444, #1531) are currently high priorities, I think we're at the right juncture to ask whether we were wrong to blindly copy the Argo CD approach and whether we want to make a small course correction.

Note that #1483 removed the option to "borrow" credentials from Argo CD. Doing so may have eliminated the only remaining incentive for emulating Argo CD's credential strategy, oddities and all.

What I propose is:

1. Eliminating the `kargo.akuity.io/secret-type` and its two values.
2. Begin using Secret's _own_ [type field](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) with one of the following values to indicate the type of repository the credentials are for:
    * `kargo.akuity.io/git-creds`
    * `kargo.akuity.io/image-creds`
    * `kargo.akuity.io/chart-creds`
3. Support _two_ fields for specifying repository / repositories the credentials are for:
    * `repoURL` -- a single specific repository
    * `repoURLPattern` -- a regular expression identifying repositories the credentials are for

Implementation-wise, none of this is very complicated.

@jessesuen wdyt?

**Comment by jessesuen** [comment]
First, I think it's fine to rework the Secret convention for Kargo. So let's do what we want here. Especially since we may have other type of credentials (S3? AWS?)

> Begin using Secret's own [type field](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types)

There's some downsides to using the type field. I know the type field is intended for that purpose, but for whatever reason, in Kubernetes the secret type is immutable so you have to delete the secret and recreate if you want to modify the type field. 

Second, if there aren't any labels, then you also can't filter secrets by the label. I think there may be value in preserving that property, though admittedly, I'd be hard-pressed if you asked me the use case. I do know filtering by labels allows you to reduce the informer memory consumption and the contents of watch streams (not that we currently do that).

**Comment by jessesuen** [comment]
A third downside is that requiring the secret type field to be one of ours, say `kargo.akuity.io/git-creds`, means that users will not be able to "reuse" existing, well-known secret types such as `kubernetes.io/basic-auth`, and `kubernetes.io/dockerconfigjson` by applying our label to it.

I can imagine a use case where those secrets might already exist, and kargo can take advantage of them. In particular, I wonder why we couldn't ask users to label a `kubernetes.io/dockerconfigjson` Secret with:

```yaml
metadata:
  labels:
    kargo.akuity.io/secret-type: image-creds
``` 

And then we would instantly have read privileges to their container image repository without having them deal with another Secret.

**Comment by krancour** [comment]
Ok. All good points. There are definitely some details to hammer out here, some requiring some research and experimentation, but I won't change any of this without your buy-in.

**Comment by krancour** [comment]
@jessesuen and I spoke offline about this.

We won't use the built-in type field because of concerns he cited above -- not the least of which is the potential for _someday_ reading Secrets that are formatted differently than what we currently require -- image pull secrets, for instance. We're _not_ tackling that now.

The strategy I settled on takes some small steps to relieve some of the confusion of the existing strategy, but it isn't a major departure from what we already do.
