### ISSUE TITLE
add verification management endpoints

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1581]
This is half-baked, but my initial thoughts are that we _at least_ need:

* A way to re-run verification. Presumably this is for a failed verification. imho, it should be ok to re-run successful verifications, but a failed re-run should not "unverify" the Freight in that Stage, because that Freight may already have been passed downstream after the previously successful verification process.

* Abort a verification. Especially because verifications can involve user-defined processes, it is conceivable that one could get "stuck." We would benefit from the ability to manually abort.

**Comment by hiddeco** [comment]
How would we go with a scenario where the template contains an error, which is then later updated to correct the mistake?

Personally, I would assume in this case Kargo would be smart enough to re-issue a verification with the newly built AnalysisRun _without_ requiring manual user intervention. At present, this appears to not be the case.

**Comment by krancour** [comment]
I think that is something to think about...

I would not oppose the notion of reconciling AnalysisTemplates in the management controller and, on change, retrying any failed verification that depends on that template.

Since multiple Stages can all use the same AnalysisTemplate for verification, we may need to think through whether this creates the possibility of a thundering herd. At present, I don't think it does because Stages can only reference AnalysisTemplates in their own namespaces, so the number of Stages associated with a given template should be small.

This could become a problem to watch out for if we eventually open the possibility of sharing AnalysisTemplates "globally." Some orgs will have a standard verification process that they'll want to share widely across projects, so I foresee this as likely.

**Comment by jessesuen** [comment]
> A way to re-run verification

Agree we should provide a way to simply run ad-hoc verifications. For a given stage, sometimes people will want to just kick off a test/analysis just to see if that environment is working that day.

> Abort a verification.

Agree. Analysis might be an expensive K8s Job that user can't wait for it to finish.

NOTE: in argo rollouts, to terminate an AnalysisRun, `spec.terminate` just needs to be set to true.

https://github.com/argoproj/argo-rollouts/blob/master/pkg/kubectl-argo-rollouts/cmd/terminate/terminate.go#L16
