### ISSUE TITLE
Add verification for Warehouse subscription duplication

### ISSUE THREAD

**Issue by maksimstankevic** [akuity/kargo#1583]
It should not be possible to create a Warehouse with duplicate subscriptions.

Steps to reproduce:
- apply a Warehouse yaml containing 2 identical Git repo subscriptions, it gets accepted into the cluster

**Comment by krancour** [comment]
In general, I am in favor of this.

In determining what sort of urgency this might have, @maksimstankevic I am curious what unusual behaviors, if any, you observed when such a mistake is made.

**Comment by maksimstankevic** [comment]
@krancour, no unusual behaviours actually, it even worked correctly with scanPaths/ignorePaths filters, I created duplicates as a test case for those

**Comment by krancour** [comment]
> it even worked correctly with scanPaths/ignorePaths filters

I can imagine some head scratching moments at least if there were two subs to the same repo with different filters.

I don't think anyone would willfully try to do such a thing, of course.

I think it would unfold like "this sub looks good... copy... paste... modify... forget to change URL."

That of course reinforced that we _should_ enforce that repo URLs are unique among subs in a given Warehouse.

Thanks for raising this.
