### ISSUE TITLE
remove freight id field

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1601]
For as long as the CRD has existed, `Freight` has had an `id` field...

The field is automatically populated with a hash of a canonical representation of the artifacts contained within the Freight.

We created a separate field for this in part because these SHAs aren't especially human-friendly and we anticipated _someday_ allowing users to create custom Freight. At present, neither the UI nor CLI offer a method of doing so. (It _can_ be done via `kubectl`.)

For as long as this field has existed, besides setting its value in a defaulting webhook, we've _also_ been modifying `metadata.name` of new Freight to match the `id` field. I believe we thought that _someday_ when users might create their own Freight, we might remove that default `metadata.name` and proceed with any user-specified name provided.

Since then (once again, because SHAs are cumbersome for humans), we introduced Freight aliases, which are implemented as labels. There is good support for these aliased in the UI and CLI.

With aliases now as the well-established, _de facto_ method of human identification for Freight, I think we could finally settle on the defaulting webhook _continuing_ to set `metadata.name` to a SHA, and we could then deem the id field truly redundant and remove it.

In working on #1600 I had the experience of scripting quite a bit of dummy Freight generation. For every create, a placeholder `metadata.name` I used was replaced by the the correct SHA and `kubectl` reported back the real name of the Freight -- not the placeholder name.

I'm feeling satisfied at this point that the id field is truly redundant and should be removed before GA.

cc @jessesuen

**Comment by jessesuen** [comment]
First, I agree ID can be removed, but I had a question on how it would work.

> I think we could finally settle on the defaulting webhook continuing to set metadata.name to a SHA

How does this work? Does kubernetes allow a webhook to default a resource name? I always thought the controller was the one formulating the name, then calling create. If a caller created a freight with an explicit name, it would get ignored/overridden by what the webhook decided?

**Comment by krancour** [comment]
The Warehouse has been setting names on Freight, yes. But the webhook also enforces the correct name. And it may seem surprising, but yes... webhooks can change a resource's name on create.
