### ISSUE TITLE
proposal: freight should not be owned by warehouses

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1602]
While working on #1600, I stumbled on something I had forgotten...

Freight are currently owned by the Warehouse that creates them.

I don't love this, as it means that deleting a Warehouse takes all its Freight with it.

This feels too dangerous, frankly. I'm tentatively considering this a bug.

I believe we stop creating this ownership relationship between Warehouses and Freight.

Some components do index Freight by Warehouse, so we _would_ have to add an `warehouse` field to Freight to indicate where it came from.

cc @jessesuen for thoughts.

**Comment by jessesuen** [comment]
I agree. Freight, like other hash-based entities (git commits, container images), needs to be treated with some degree of permanence.

**Comment by hiddeco** [comment]
> This feels too dangerous, frankly.

Can you elaborate more on the impact, negative side-effects, etc. this could _potentially_ introduce? For future reference, and the help me continue to build up my mental model.

**Comment by krancour** [comment]
Sure. It think a lot of people would feel surprised by the behavior of a Warehouse delete cascading to every piece of Freight that Warehouse ever created. I can see someone, with good intentions, deleting and re-creating a Warehouse, unaware of the consequences. I certainly hadn't _meant_ for such deletes to cascade. I had only wanted to establish a formal relationship between Warehouses and the Freight they create, but this wasn't the right way to do it.
