### ISSUE TITLE
proposal: create freight aliases in defaulting webhook

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1604]
Currently, random Freight aliases are assigned by the Warehouse reconciler during Freight creation.

Working on #1600 today, I had the experience of scripting creation of a lot of Freight for testing purposes.

Generally, users do not create Freight yet and it is only done by the Warehouses, though we expect that may change eventually.

Having scripted Freight creation, I got no aliases and I found myself wishing the defaulting webhook had set the aliases for me.

cc @jessesuen

**Comment by jessesuen** [comment]
Makes sense to me. When we switch to this, can we be sure to allow the webhook to honor a user-defined alias (assuming there's no conflict).

**Comment by krancour** [comment]
@jessesuen  what do you think about an alias field? It would be similar to what we did with the recent addition of a shard field on Stages. With the same benefit -- spare users from looking up what the alias label is.

**Comment by hiddeco** [comment]
+1 on adding it as a field, I think this is the most preferable option when you are in full control of the API spec for UX reasons mentioned.
