### ISSUE TITLE
additional kargo config commands

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1614]
Currently we can only do `kargo config set-project <project>`.

I'd like if we also had `kargo config view` (view the whole config file) and `kargo config get-project`.

This would make it behave more like `kubectl` overall and would also stop users from having to hunt down and cat their config file just to see what their current default project is.

**Comment by hiddeco** [comment]
As we are getting close to the release, I'll pick this up to have it ready (and reviewed) on time.
