### ISSUE TITLE
add FreightReference to PromotionStatus

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1628]
Since the lifecylce of Freight and Promotions are fully decoupled from one another, it is possible that an older Promotion may stick around longer than some older piece of Freight that it references.

If we add a FreigthReference field to PromotionStatus, every Promotion will retain some details of the Freight it referenced, even with that Freight having been deleted.

This is similar to how/why we keep FreightReferences in StageStatus's History field.

**Comment by jacobnguyenn** [comment]
@krancour  can I take this one?

**Comment by krancour** [comment]
@jacobnguyenn it's yours! Thank you!
