### ISSUE TITLE
Detect changes to AnalysisTemplate 

### ISSUE THREAD

**Issue by hiddeco** [akuity/kargo#1636]
At present, changes made to AnalysisTemplate(s) used by a Stage are not recognized by the controller. Due to this, the verification process of a Stage's current Freight can not automatically recover from a (due to a misconfiguration) failing AnalysisRun without manual user intervention.

Which requires the user to:

1. Address the issue within the AnalysisTemplate(s)
2. Rerun the verification for the Stage (which is only possible since #1611 )

Based on an earlier discussion in https://github.com/akuity/kargo/issues/1581#issuecomment-1981166069 and https://github.com/akuity/kargo/issues/1581#issuecomment-1981199371, I think we should explore if detecting changes and automatically rerunning the (failed) verification is something we would like to pursue. As this would limit the steps required from the user to recover from such an error to _just_ addressing the issue with the AnalysisTemplate.

**Comment by jessesuen** [comment]
For the sake of simplicity, I think the current behavior is acceptable; that is, the existing/completed/in-flight AnalysisRuns are frozen to the version of the AnalysisTemplate at the time of run creation, and we do not attempt to re-run things automatically / unverify Stages.

Now that we have the ad-hoc ability to kick off an AnalysisRun or retry a failed AnalysisRun, we could leave the decision to rerun the most recent version as a choice for the user. Though admittedly, they may not know which template was used without inspection of the AnalysisRun yaml.

**Comment by krancour** [comment]
Tentatively closing this, but think it's something that could be revisited if the community expresses any appetite for this.
