### ISSUE TITLE
Maintain verification history for a Stage

### ISSUE THREAD

**Issue by hiddeco** [akuity/kargo#1638]
This came up during an offline discussion with @krancour while working on #1611.

Currently, a Stage only offers information about the most recent verification performed on the current Freight. However, users now have the ability to rerun verifications for a Stage. Additionally, users may also want to access historical verification information for Freight verified at a previous time.

Considering this, it might be beneficial to implement a `VerificationInfoStack` on the Stage, which would offer a history of verifications for up to N items.

**Comment by krancour** [comment]
I've always believed we needed this and really didn't add it initially because there was no re-triability yet...

I'm going to assign this to the current milestone because this seems like very important companion functionality to the retries.
