### ISSUE TITLE
Empty controllerInstanceID causes ArgoCD to always show kargo as "Out of Sync"

### ISSUE THREAD

**Issue by kastl-ars** [akuity/kargo#1644]
Hi all,

the kargo helm chart's `values.yaml` contains an empty default for the `controllerInstanceID`.

https://github.com/akuity/kargo/blob/main/charts/kargo/values.yaml#L281

In our test installation, deploying kargo using ArgoCD and its helm plugin, this causes ArgoCD to always show the kargo application to be `Out of Sync`. The diff shows that this attribute is to be added with an empty value, which for $REASONS ArgoCD cannot do.

If I understand that value's purpose correctly, setting it to empty and not defining it at all lead to the same behaviour:

`controller.rollouts.controllerInstanceID Specifies a cluster on which Jobs corresponding to an AnalysisRun (used for Freight/Stage verification purposes) will be executed. This is useful in cases where the cluster hosting the Kargo control plane is not a suitable environment for executing user-defined logic. Kargo will use this as the value of the rgo-rollouts.argoproj.io/controller-instance-id label when creating AnalysisRuns. When this is left empty/undefined, no such label will be added to AnalysisRuns.`

So I would propose to comment out this value and let the user set this, only if needed.

Or am I missing something here (which would be totally possible, as I am just starting out with kargo and ArgoCD and the likes)?

Kind Regards,
Johannes

**Comment by krancour** [comment]
@kastl-ars what version are you on? This should have been resolved already on `v0.4.4`.

**Comment by kastl-ars** [comment]
Thanks for the quick reply. We were on 0.4.3 and updated to 0.4.4 at the same time with disabling rollouts to work around this issue. :-)

**Comment by kastl-ars** [comment]
We re-enabled rollouts and the issue I described above did not reappear, so I can confirm this is fixed in 0.4.4.

Thanks a lot!
