### ISSUE TITLE
Allow Shared Namespace Ownership for Projects

### ISSUE THREAD

**Issue by isugimpy** [akuity/kargo#1654]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Allow the Project resource to share ownership of a Namespace by appending to the OwnerReferences instead of giving up.

# Motivation

As a platform owner, I've already got a managed mechanism for creation of Namespaces.  This directly conflicts with the Project implementation in Kargo because Kargo will only adopt a namespace if the OwnerReferences field has no items in it.

# Suggested Implementation

Add additional control flow to https://github.com/akuity/kargo/blob/33247fec02010a9fc28d392952f379cbf0f41397/internal/controller/management/projects/projects.go#L240-L254 to append to the OwnerReferences list if it's present.  This could potentially be gated by a boolean field on the Project resource, or a CLI flag for whichever Kargo controller implements this behavior, but the gate doesn't seem strictly necessary.

# Additional Notes

I'm willing to toss a contribution for this if it'd be accepted.  I'll openly admit, I haven't tried Kargo yet, hoping to do so yet this week, but the current behavior is a potential blocker for my organization because we manage namespaces via an in-house controller that maintains ownership.

**Comment by krancour** [comment]
@isugimpy thanks for the suggestion. I can see how this is a problem for you.

The reason for the current behavior is that it is meant to prevent "hijacking" an existing namespace.

I'd love if we could do what you're suggesting, but I'm not sure yet how we could mitigate that risk.

Happy to hear your thoughts.

**Comment by isugimpy** [comment]
The concern is totally valid!  That's actually why I suggested a gate on the CR saying that Project is allowed to share ownership of the namespace, so that it isn't the default, but rather an opt-in behavior.  I could also be fine with a label or annotation on the namespace that is a cue to Kargo to accept that shared ownership model.  That may actually be safer, because then it's preventing an unprivileged user from doing something like creating a Project that could assume ownership of kube-system or something like that.

**Comment by krancour** [comment]
> That's actually why I suggested a gate on the CR saying that Project is allowed to share ownership of the namespace, so that it isn't the default, but rather an opt-in behavior.

My concern there was that it only prevents an accidental hijacking and not an intentional one.

> I could also be fine with a label or annotation on the namespace that is a cue to Kargo to accept that shared ownership model. That may actually be safer, because then it's preventing an unprivileged user from doing something like creating a Project that could assume ownership of kube-system or something like that.

I quite like this idea. It's actually what we do for Argo CD `Application`s as well. An annotation on an `Application` indicates consent for Kargo to interact with it, provided by someone who obviously had sufficient permission to add that annotation.

> I'm willing to toss a contribution for this if it'd be accepted.

Given the revised approach -- we'd absolutely love to have you contribute that! Thank you!

**Comment by isugimpy** [comment]
Opened #1667 with the proposed solution!
