### ISSUE TITLE
Expose Workload Security Context in Helm Values File

### ISSUE THREAD

**Issue by rdelpret** [akuity/kargo#1661]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Expose workload security context via the helm values file.

# Motivation

As an operator that has OPA / gatekeeper policies on our clusters that prevent workloads without certain security context settings from being scheduled I would like to add the ability to set the security context per component. 

# Suggested Implementation

Add `{{ toYaml .Values.controller.securityContext | indent x }}` to the helm template / values file.

**Comment by krancour** [comment]
This was closed by #1662
