### ISSUE TITLE
Add the ability to Specify Arbitrary Annotations on Workload Resources via values file

### ISSUE THREAD

**Issue by rdelpret** [akuity/kargo#1663]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Add the ability to specify arbitrary annotations on workload resources via the values file. 

# Motivation

OPA gatekeeper policies require certain annotations where we are attempting to deploy kargo.

# Suggested Implementation

Incoming PR

**Comment by krancour** [comment]
This was closed by #1664
