### ISSUE TITLE
proposal: v0.4.x --> v0.5.x upgrade tool

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1681]
There are a few breaking changes in v0.5.0 that are somewhat difficult to contend with.

1. CRDs are now fully managed by the chart. This means you need to "adopt" existing CRDs. @hiddeco already wrote a script for that that's in the `hack/` dir.

1. `Freight` has lost its `ID` field. This isn't actually a problem. Corresponding to this, however, the `ID` field of the `FreightReference` type was renamed to `Name`.

1. `Freight` no longer have an ownership reference to the `Warehouse` that created them. They have a `Warehouse` field instead. This is used in building a "freight by warehouse" index that is used in several places. Notably, it's used for finding available `Freight` for any `Stage` that subscribes _directly_ to a `Warehouse`.

I propose the following to pave the way for these changes in existing Kargo installations:

1. Put the `ID` field back in the `FreightReference` type. We can allow it to co-exist with the `Name` field until v0.6.0.

1. Implement a binary to be run by the same use who run `helm upgrade`. If we assume this, then we can also assume they have sufficient permissions to permit that binary to do all of the following:

    1. Find all existing Kargo CRDs and add necessary labels and annotations to indicate that they are managed by Helm.

    1. Step through all `Stage`s cluster-wide. For each `FreightReference` (`CurrentFreight` and `History`) copy the value of the `ID` field to the `Name` field.

    1. Step through all `Freight` to copy the name of the owning `Warehouse` from the ownership reference to the new `Warehouse` field, then delete the ownership reference. The Kargo webhook server ordinarily enforces the immutability of `Freight`. The `ValidatingWebhookConfiguration` that enforces that would have to be temporarily patched.

One limitation of this approach is that it doesn't especially help anyone who is gitops'ing their Kargo installation.

To that end, a second alternative is to build most of the same functionality (CRD change wouldn't be possible) into a throwaway controller -- or even add it temporarily to the startup logic of the existing management controller since, even in a sharded topology, that controller runs exclusively on the control plane. (This would be preferable to ensuring that many distributed controllers _all_ handle upgrades of the resources they reconcile.)

__Edit:__ Since all of this work is temporary, I also believe we should perform it in the `release-0.5` branch after it diverges from `main`. This way `main` isn't polluted with these short-term concerns.

**Comment by hiddeco** [comment]
> 1. Put the `ID` field back in the `FreightReference` type. We can allow it to co-exist with the `Name` field until v0.6.0.

This SGTM.

> 2. Implement a binary to be run by the same use who run helm upgrade. If we assume this, then we can also assume they have sufficient permissions to permit that binary to do all of the following: [..]

Instead of doing this, I would instead let the controller do this for the user (minus the Custom Resource Definition related changes) using the _existing_ reconcilers (which will handle the resource kinds anyway). As I think this brings a much nicer automated and worry-free user experience.

**Comment by krancour** [comment]
Ya. That was option two. I'll go with that.

**Comment by krancour** [comment]
Yep. Your script will still have to be sued to address item no. 1.

**Comment by jessesuen** [comment]
> or even add it temporarily to the startup logic of the existing management controller since

Out of the options, I liked this one the best because it worked for all cases, and it provides a seamless experience for users.

**Comment by krancour** [comment]
This should have been closed by #1683
