### ISSUE TITLE
helm chart subscriptions should ignore tags that are not semver

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1684]
In #1678, @hoopty noted that it's possible for OCI repos being used to store Helm charts to defy the expectation that the repository only contains tags that are valid semantic versions.

When this is the case, an error like the following may result:

```
error getting latest Freight from repositories: error syncing chart repo subscriptions:
error searching for latest version of chart in repository "oci://registry-1.docker.io/bitnamicharts/rabbitmq":
error determining latest version of chart "" from repository "oci://registry-1.docker.io/bitnamicharts/rabbitmq":
error parsing version "sha256-4730c3c5fe00ed4cf6ffd139ed081f5a27342a959fbc89ef53d2b5c5341ff7af":
Invalid Semantic Version
```

This issue supersedes #1678 and calls for chart subscription logic to ignore tags that are not parsable as semantic versions.

This is a very small change right here:

https://github.com/akuity/kargo/blob/0b43b26e0d3c5e01b57b1db2914cf9e67e5408d7/internal/helm/helm.go#L176-L181

**Comment by jacobnguyenn** [comment]
@krancour can i take this one :)

**Comment by krancour** [comment]
@jacobnguyenn all yours. Thank you!
