### ISSUE TITLE
ui: new warehouse not immediately displayed

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1697]
It wasn't obvious until after #1689, but #1679 seems not to be making the view refresh after the creation of a new Warehouse.

**Comment by rbreeze** [comment]
I believe this was fixed by https://github.com/akuity/kargo/pull/1723 (I can no longer reproduce it). @krancour feel free to confirm and close this issue if it is indeed fixed

**Comment by krancour** [comment]
@rbreeze Oh great. I will double check that! Thanks!

**Comment by krancour** [comment]
@rbreeze I confirmed that this is fixed! Thanks!
