### ISSUE TITLE
Unsetting `spec.shard` has no effect

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1699]
# Description

If you add a `spec.shard`, then the corresponding label gets injected. However, the opposite is not true. If I unset `spec.shard` and save the object, the `spec.shard` will be repopulated.

Since we expect most people not to care about or manage the label, the `spec.shard` should be the source of truth and the label should always mirror that value.

# Steps to Reproduce

Attempt to unset `spec.shard`. It will save properly without error, but it will have no effect.

# Version

```
v0.5.0-unstable-20240325
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by krancour** [comment]
@jessesuen and I discussed offline. This is due to a two-way sync between the shard field and the shard label.

Field --> label is something we wish to do on an ongoing basis.

Label --> field is only to facilitate upgrade from Stages created prior to v0.5.0.

We will move the latter into #1683
