### ISSUE TITLE
bug(ui): rename alias does not work for freight without an alias

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#1722]
<img width="417" alt="Screenshot 2024-04-01 at 08 10 34" src="https://github.com/akuity/kargo/assets/6250584/949f6caf-2cb3-4c3d-80e9-64b422b8dd72">

**Comment by krancour** [comment]
@rbreeze I can't seem to reproduce this.

**Comment by rbreeze** [comment]
Confirmed that this was a local issue (old freight)
