### ISSUE TITLE
cli: add `kargo server` command

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1728]
Extracted from #1569:

> Jesse:
> * Kargo API server is not exposed in a shared manner
> * End users are given access to a portion of the cluster via kubeconfig
> * Users could still have a UI to do their thing

This would be _different_ from the bygone `--local-server` option because it only did this:

> Kent: adding --local-server to a command launches an ephemeral server that lives for the life of the command it's carrying out.

**Comment by webstradev** [comment]
Is this already done? I seem to recall seeing this command when I was last playing around with The CLI

**Comment by hiddeco** [comment]
This is still an open issue, and I kind-of documented a blueprint for what is required here in https://github.com/akuity/kargo/blob/v0.5.1/internal/cli/cmd/server/server.go#L69-L79

**Comment by krancour** [comment]
> //The server should be started with a Kubernetes client which does NOT 
//   make use of an authorization wrapper. 

This seems as if it's already taken care of.

> It should allow the user to visit the UI in their browser.

I actually solved _part_ of this problem locally and hadn't PR'ed it yet. Will open.

The rest certainly does remain outstanding...

A _big_ gotcha is the UI currently doesn't accommodate the possibility of no authn at all. I'm going to open that specific item as a separate issue.

**Comment by krancour** [comment]
Opened #1834 for the UI to hopefully gain the possibility of skipping the login page.

#1833 embeds UI assets in both the CLI and control plane binaries.

**Comment by hanshal101** [comment]
Is this still a valid issue?

**Comment by krancour** [comment]
@hanshal101 no one has really been pushing for it. I believe this is something we could still entertain if someone really wants it and wants to do the work. That said, #1833 is a pre-requisite for this and also isn't a priority, because the only real reason to tackle #1833 would be to clear the way for this. i.e. Someone would probably have to take ownership of both those issues in order for there to be some movement here.

**Comment by hanshal101** [comment]
Hey @krancour I would like to work on this. Since I'm new to this community could you please guide me on further steps?

**Comment by krancour** [comment]
@hanshal101 do you personally have a use case for this or are you just looking to grab an issue to work on?

This issue was opened to replace similar functionality (`--local-serve`) that was removed, but as I said, I haven't heard of anyone really pushing to get this issue resolved.

The thing I want to avoid is implementing this "just because."

And as I mentioned, #1833 is a prereq for this and seems to me to be a much harder issue than this one.

**Comment by hanshal101** [comment]
> @hanshal101 do you personally have a use case for this or are you just looking to grab an issue to work on?
> 
> This issue was opened to replace similar functionality (`--local-serve`) that was removed, but as I said, I haven't heard of anyone really pushing to get this issue resolved.
> 
> The thing I want to avoid is implementing this "just because."
> 
> And as I mentioned, #1833 is a prereq for this and seems to me to be a much harder issue than this one.

To be honest I'm just grabbing an issue ro work on it

**Comment by krancour** [comment]
> To be honest I'm just grabbing an issue ro work on it

Gotcha. I wouldn't suggest this one unless you personally needed it because it's not clear anymore that this feature is badly needed.

#2363 or #2271 might be better first issues.
