### ISSUE TITLE
Kargo objects should have a description field

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1733]
# Proposed Feature

When inputing/managing credentials (or other objects), I would like the ability to add some notes about the credential (e.g. expiration, URL to the site where it can be managed). Kargo should introduce a description field on credentials so users can add their notes.

# Motivation

It would be useful to have some more context about credential it refers to so it can be managed easier.

# Suggested Implementation

Our secrets can recognize annotation where we allow users to capture a description. This description is not sensitive, and would be shown in UI in our credentials tab. I prefer annotation over something in `data` because I believe some secrets types have predefined fields in `data` that do not allow for extra fields. Also, data field in secrets need to be base64 decoded before viewed.

**Comment by hiddeco** [comment]
I can imagine the same could be said for Stages, or even Projects?

**Comment by jessesuen** [comment]
> I can imagine the same could be said for Stages, or even Projects?

Great idea! Updated title

**Comment by krancour** [comment]
Note that for Stages and Projects (and Warehouses, too, for that matter) I'd rather see this be a field than an annotation.

I understand the motivations for it being an annotation on a Secret, but absent those, a field is more straightforward.

**Comment by jessesuen** [comment]
For something like AnalysisTemplates, we also can't control the spec and it would need to be an annotation. So Secrets wouldn't be the only inconsistency.

Does that change your position if we had to have Secrets/AnalysisTemplates use annotations but Warehouse, Stages, Projects use `spec.description`?

**Comment by krancour** [comment]
Very good call out @jessesuen. Yes. That changes my thinking. Annotations across the board.

Note that this is already implemented for credentials/`Secret`s as of #1772 -- merged just earlier today.

If we're going the annotation route, what's left of this is only a UI task.

Removing API and CLI labels.

**Comment by krancour** [comment]
There is a lot of UI work remaining for v0.6.0. I'm making the decision that this is some of the less critical UI work and am deferring it to v0.7.0.
