### ISSUE TITLE
cli: add --no-headers flag

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1751]
`kubectl` has a useful `--no-headers` flag that you can use on any get operation. It is enormously useful when you're going to pipe the output into `grep`, `awk`, etc.

Without `--no-headers`:

```shell
$ kubectl get namespaces | head -n 5

NAME                 STATUS   AGE
kube-system          Active   6h52m
kube-public          Active   6h52m
default              Active   6h52m
kube-node-lease      Active   6h52m
```

With `--no-headers`:

```shell
$ kubectl get namespaces --no-headers | head -n 5

kube-system          Active   6h52m
kube-public          Active   6h52m
default              Active   6h52m
kube-node-lease      Active   6h52m
cert-manager         Active   6h52m
```

I'd love to see us add a `--no-headers` flag to the `kargo` CLI as well.

**Comment by webstradev** [comment]
Happy to take a crack at this one @krancour , seem manageable

**Comment by webstradev** [comment]
Jus to double check:
Are we only adding this to the `kargo get` command specifically

**Comment by hiddeco** [comment]
I would add this to any command making use of `printers.NewTablePrinter`, which [accepts a `PrintOptions` that takes a `NoHeaders` boolean value](https://pkg.go.dev/k8s.io/cli-runtime/pkg/printers#PrintOptions). At present, this only is `kargo get` and its sub-commands.

Given this, I would not make it a `kargo` global "persistent" flag (for now, at least). However, it _could_ be "persistent" for `kargo get`.

**Comment by hiddeco** [comment]
Regarding the structure of the refactored code... If you would set it on `kargo get` as a persistent flag, you can retrieve the value of the flag in a sub-command's `complete()` method using something like `cmd.PersistentFlags().GetBool(option.NoHeadersFlag)`.

**Comment by webstradev** [comment]
So just a bit of a sanity check to see if I am on the right traack.

in the get command we have a function called printTable (which is used by all subcommands to prints the resources).
This already supports printing with no headers by passing a printeroption NoHeaders.
I tested this locally to see if it indeed does as what we want it to do:
`	return printers.NewTablePrinter(printers.PrintOptions{NoHeaders: true}).PrintObj(printObj, streams.Out)`.

So my thought is now to add a boolean argument to the printTable function and then in each subcommand pass the persistent flag value there (or false if its nil).

**Comment by krancour** [comment]
Yes. You're 100% on the right track.
