### ISSUE TITLE
proposal(ui): allow Freight to be clickable to select Stage (subscribers) to promote to

### ISSUE THREAD

**Issue by hiddeco** [akuity/kargo#1756]
At present, to initialize the promotion of Freight to (subscribers of) a Stage a user has to click on an icon on the left or right side of the applicable Stage. Once they do this, they can select the Freight which should be promoted. As @krancour describes it, this makes sense for an ops person, as:

> stages might be your babies and you think "oh, i want to put this stage in a certain state"

However, as a developer this may actually feel counter-intuitive, as:

> a piece of freight with changes you worked hard on might be your baby and you think, "oh, i want to move this state to a certain stage"

To provide a better and more intuitive user-experience for the second persona. My proposal is to see if we can introduce a flow in which clicking on a Freight in the freightline of a Project initializes the promotion process, allowing you to select the (subscribers of) the Stage you want the Freight to be promoted to.

Optionally, we could also allow the "hover" state which changes the color of the Stages where the Freight is already current to remain active once clicked, to provide additional visual guidance around potential Stages of interest for promotion.

**Comment by rbreeze** [comment]
@hiddeco How about we add a "Promote" action to this dropdown to trigger the mode you're describing? 

![CleanShot 2024-04-04 at 14 31 04@2x](https://github.com/akuity/kargo/assets/6250584/721e5113-b19b-4d3e-b806-d54fc93f4ec6)

**Comment by hiddeco** [comment]
While this would absolutely be a step in the right direction, I feel this would not nail the user-experience as it's not as obvious as just clicking the Freight box itself.

But I do understand there may be technical challenges in making that happen, or it conflicting with and/or complicating the "copy alias" feature.

**Comment by krancour** [comment]
> as it's not as obvious as just clicking the Freight box itself

Clicking the freight box now opens an expanded Freight view with live state and such, so that particular trigger is taken.

**Comment by hiddeco** [comment]
I had missed this recent enhancement, then I guess the next best thing is indeed the dropdown menu.
