### ISSUE TITLE
Signing commits when writing changes to Git

### ISSUE THREAD

**Issue by zhenya-khvan-form3** [akuity/kargo#1758]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

## Proposed Feature

Kargo to support signing commits when writing changes to a Git repository. There are three currently supported mechanisms[^1][^2]:

- GPG
- SSH
- S/MIME

## Motivation

Organizations that want to enforce [commit signing](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-signed-commits) on all repositories and branches wouldn't be able to leverage Kargo without adding exceptions for stage-specific branches.

## Suggested Implementation

Depending on which signing mechanisms Kargo wants to leverage, the complexity can vary. As an example for GPG signing, a potential approach could be:

- Update `kargo-render` image to include `gpg` and `gpg-agent`
- Add Name, Email and GPGPrivateKey to ~~Kargo's credential database type~~ a system-level Kargo identity
- Update Git authentication setup to configure commit signing with GPG and import the GPG private key

[^1]: https://git-scm.com/docs/gitformat-signature
[^2]: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by krancour** [comment]
This is a very good idea.

I'm not entirely sure about including the GPG key in credentials secrets, however.

GPG is usually used to identify a user/agent and is not usually repo/service specific. i.e. I sign all my commits, but I don't use a different key for different repos.

I think what we probably need here is the opportunity to specify a system-level GPG key that represents an instance of Kargo as an agent.

**Comment by krancour** [comment]
@zhenya-khvan-form3 absolutely!
