### ISSUE TITLE
ui: Indicate whether auto-promotion is enabled for nodes in DAG view

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#1764]

**Comment by jessesuen** [comment]
Perhaps like Argo CD auto-sync, promoting into the stage is not allowed when auto-promotion is enabled. And so we could grey out the target icon with a tooltip explaining why?

**Comment by krancour** [comment]
> Perhaps like Argo CD auto-sync, promoting into the stage is not allowed when auto-promotion is enabled.

At first I was thinking this should be a separate issue and then I realized the suggestion is really that the greyed out target icon _is_ the visual indicator.

I'm of the mind that auto-promotion and manual promotion are not mutually exclusive. I can imagine cases where a user consciously wishes to return to a previous state after an unfavorable auto-promotion has occurred.

**Comment by rbreeze** [comment]
Closing in favor of #961
