### ISSUE TITLE
AnalysisRun status.message should carry over to Stage verificationInfo

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1767]
# Proposed Feature

Currently, when verification fails, we don't have any indicator of why it failed. We only see a broken red (!) in the verifications tab but nothing else. AnalysisRuns have `status.message` that would give a better reason. e.g.:

```yaml
status:
  message: Metric "test-fail" assessed Failed due to failed (1) > failureLimit (0)
```

We should carry this message over to Stage status so that UI can show this as a column in verifications and users can understand more quickly why verification failed

**Comment by krancour** [comment]
Deferred to v0.7.0
