### ISSUE TITLE
UI: Pop up detail should not cover the Yes / No button

### ISSUE THREAD

**Issue by wanghong230** [akuity/kargo#1773]
![image](https://github.com/akuity/kargo/assets/2680725/87b9a32e-46b2-4985-a11f-ea3fb6f94b9f)

I prefer the pop up detail to be moved down, not to cover the YES / NO button.

**Comment by krancour** [comment]
I agree with @wanghong230, but want to add that I don't think pop-up context needs to be moved down _only_ during promotion when it obscures the yes/no buttons. imho, it should _always_ be shown under the freightline. Here is an example of me _not_ actively promoting, but still having important details (namely the contents of the freight) obscured by the pop-up:

<img width="451" alt="Screenshot 2024-04-05 at 11 28 00 AM" src="https://github.com/akuity/kargo/assets/1821014/9f3c5ced-7fbd-4223-9fb4-3b01edb9b7fa">
