### ISSUE TITLE
Unable to run make hack-build-cli

### ISSUE THREAD

**Issue by webstradev** [akuity/kargo#1789]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

**This isn't a bug in Kargo just in the Makefile so only relevant for developers/contributors**

When running make hack-build-cli I encounter the following error:

`docker run -it --rm -v gomodcache:/home/user/gocache -v /Users/webstradev/development/personal/kargo/:/workspaces/kargo -v /workspaces/kargo/ui/node_modules -w /workspaces/kargo kargo:dev-tools sh -c 'GOOS=darwin GOARCH=arm64 make build-cli'
CGO_ENABLED=0 go build \
        -ldflags "-w -X github.com/akuity/kargo/internal/version.version= -X github.com/akuity/kargo/internal/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -X github.com/akuity/kargo/internal/version.gitCommit= -X github.com/akuity/kargo/internal/version.gitTreeState=" \
        -o bin/kargo-darwin-arm64 \
        ./cmd/cli
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
make: *** [Makefile:109: build-cli] Error 1
make: *** [hack-build-cli] Error 2
webstradev@Eriks-MacBook-Pro kargo % 
`

When I add -buildvcs - false, as the error message suggests it works just fine.

Running make build-cli (without the hack) also works as intended.

# Screenshots

# Steps to Reproduce

switch to main branch, run make hack-build-cli

# Version

```
Paste the output from `kargo version` here.
```

not applicable as I can't successfully build the CLI

# Logs

```
Paste any relevant application logs here.
```
See description.

**Comment by webstradev** [comment]
Just to add to this I have just run into a similar issue when running make hack-lint-go:

<img width="721" alt="image" src="https://github.com/akuity/kargo/assets/82543732/05873c8c-9748-402a-a9b5-787f297edee5">

**Comment by krancour** [comment]
@webstradev can you try deleting the Docker volume named `gomodcache`?

I believe anyone who contributed prior to #1517 might be encountering this and that is a one-time fix that seems to work.

**Comment by webstradev** [comment]
So I had already done this as Christian pointed it out in discord. I was experiencing another issue also cause bij #1517.
I have again deleted the docker volume but still encountering this issue.

**Comment by krancour** [comment]
Hmm. Ok will look at this close during the week.

**Comment by webstradev** [comment]
I'm on a m2 Macbook Pro with Ventura 13.5.2
Docker: Current version: 4.27.1 (136059)
Go: go version go1.22.2 darwin/arm64

Also something that I noticed, hack-build-cli fails, hack-lint-go fails with the same error but hack-unit-test passess just fine.

**Comment by webstradev** [comment]
Some additional logging from adding -v to the build command

State=" \
        -o bin/kargo-darwin-arm64 \
        -v \
        ./cmd/cli
# cd /workspaces/kargo; git status --porcelain
fatal: detected dubious ownership in repository at '/workspaces/kargo'
To add an exception for this directory, call:

        git config --global --add safe.directory /workspaces/kargo
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.

**Comment by webstradev** [comment]
Is that because you set version related information via ldl flags anyways and you don't need the vcs metadata?

**Comment by krancour** [comment]
> Is that because you set version related information via ldflags anyways and you don't need the vcs metadata?

It's not strictly _because_ of it, but at some point when first developing those automations, we must have encountered this same issue and decided that we _could_ forgo the VCS metadata without worry due to what we were doing with the ldflags already.

My search history shows I first looked up this issue 8 months ago!

**Comment by krancour** [comment]
> FYI I have just checked out the commit before https://github.com/akuity/kargo/pull/1517 and make hack-build-cli does work properly there so it is likely to be something that changed in that PR

I agree this seems likely.

**Comment by hiddeco** [comment]
Can you try erasing the node modules directory and then rerunning the command?

**Comment by webstradev** [comment]
> Can you try erasing the node modules directory and then rerunning the command?

I have nothing in there as I just recloned the whole repo.

**Comment by webstradev** [comment]
Anything else you would like me to try here, or alternatively i can make a pr to add -buildvcs=false to the goflags

**Comment by krancour** [comment]
> or alternatively i can make a pr to add -buildvcs=false to the goflags

We're already passing all necessary version info in through other means, so I think I would find this acceptable.

Thank you!
