### ISSUE TITLE
Upgrade all golang dependencies to 1.22

### ISSUE THREAD

**Issue by webstradev** [akuity/kargo#1790]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

I noticed a bit of discrepancy between go version. The linter is on 1.20 the ci images are on 1.22 and the go mod itself is still on 1.21.

Suggestion would be to bring everything to 1.22. Happy to pick this up myself, but thought I'd open an issue first as I'm not sure if you have a certain way for keeping go version up to date.

# Motivation

Consistency

# Suggested Implementation

N/A

**Comment by webstradev** [comment]
Is there any discussion needed for this @krancour or can I pick it up.

**Comment by krancour** [comment]
@webstradev feel free.

It _might_ be the only the linter settings that are inconsistent at the moment. Dependabot was busy yesterday.
