### ISSUE TITLE
UI: ability to rerun the verification of a Stage's current Freight

### ISSUE THREAD

**Issue by hiddeco** [akuity/kargo#1792]
# Proposed Feature

We should make it possible to rerun the verification of a Stage's current Freight from the UI, as is currently possible using the CLI:

```console
$ kargo verify stage --project=my-project my-stage
```

# Motivation

You may want to retry a terminated (#1771) verification at a later moment, or simply be assured that things are still working as expected at any given time.

# Suggested Implementation

**Comment by krancour** [comment]
@jessesuen checking on whether you wanted this in v0.5.1.
