### ISSUE TITLE
Kargo should reflect both the health and sync state

### ISSUE THREAD

**Issue by wanghong230** [akuity/kargo#1817]
<img width="305" alt="image" src="https://github.com/akuity/kargo/assets/2680725/7a99d7f2-464d-48cc-a393-a40b827a262d">

Kargo showed everything is fine

<img width="921" alt="image" src="https://github.com/akuity/kargo/assets/2680725/e471cfd8-6bb7-4c6f-8611-ef4198f3ec3e">

Argo CD is showing OutOfSync and SyncError

**Comment by wanghong230** [comment]
It might be addressed by https://github.com/akuity/kargo/commit/2d9101eebdbe4ddb1b121f2cdbe885a42721e1c4

**Comment by krancour** [comment]
This is the same issue as #1451 and as you guessed @wanghong230, it is indeed fixed by #1807, which introduced a conditions check that was previously not part of the health check logic.
