### ISSUE TITLE
Event: Move event recording in ValidatingWebhook to controller

### ISSUE THREAD

**Issue by devholic** [akuity/kargo#1844]
### Background

As @hiddeco pointed out, recording Events on ValidatingWebhook doesn't guarantee that the given event is _really_ happened or not because other ValidatingWebhook in cluster can affect the result of validation.

### Proposal

Instead of recording events in ValidatingWebhook,

1. MutatingWebhook annotates event payload to target resources
1. Controller records event in initial phase of reconciliation loop if payload presents in annotation and clear from annotations

### References

- [Admission Control Phases](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#admission-control-phases)

**Comment by krancour** [comment]
Agreed.

**Comment by krancour** [comment]
@devholic I'll leave it up to you whether this needs to be changed in the v0.6.0 timeline or if the current behavior is acceptable _for now_, making this lower priority. Your call.

**Comment by devholic** [comment]
@krancour Focusing on event tracking itself has higher priority for v0.6.0, so I think we can do this after v0.6.0 is released.
