### ISSUE TITLE
Kargo initiated Argo CD syncs do not emit Events

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1845]
# Proposed Feature

When Kargo performs an Argo CD sync on an application, it does so by setting the `.operation` field of the Application (the same way that Argo CD API and controller do)

However, because we set this operation ourselves, it misses the logic that the argocd-application-controller and argocd-server currently have to emit the corresponding Kubernetes Event, which users rely on for audit records.

When Kargo is the one initiating the sync, it should also emit this Event. 

# Motivation

Without this, the sync will not show up in event history

# Suggested Implementation

Emit a Kubernetes event in the same format as Argo CD during sync.

**Comment by krancour** [comment]
@jessesuen I'm guessing you have some specific rationale for this approach, but I am wondering if you can elaborate on why we wouldn't fix this in Argo CD so that emission of this event doesn't come from the API server, but only from the controller.

**Comment by jessesuen** [comment]
Hmm, I had assumed there was a technical hurdle where the Argo CD API server had more information to enrich the event that wasn't available in the controller, but after just checking, it does seem like what you are saying would be possible. That said, it would be a larger effort to improve this upstream and the improvement may not make its way to the desired downstream versions of Argo we want to support.

> if we took Kargo out of the picture entirely, and you or I annotated an Application to trigger an operation, there would be no record of that.

What you are saying is true, but since AFAIK, no other tools are really setting `operation` like this programmatically (since it's not as straightforward as setting an annotation) and so, this is really of importance to Kargo, but not much else.

**Comment by krancour** [comment]
> That said, it would be a larger effort to improve this upstream and the improvement may not make its way to the desired downstream versions of Argo we want to support.

That makes sense to me. Just wanted to make sure we hadn't overlooked this possibility entirely.
