### ISSUE TITLE
ui: selectively display promotion buttons

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1857]
Follow-up to #1842

We used to allow promotion to "control flow" Stages, but such promotions always succeeded instantly without actually doing anything.

#1842 removes the ability to create such promotions.

We need a complementary UI change to:

1. Not display the target button on the left of a control flow Stage.
2. Not display the truck button on the right of a control flow Stage if _all_ its downstreams are control flow stages.

**Comment by jessesuen** [comment]
Duplicating this to https://github.com/akuity/kargo/issues/1867
