### ISSUE TITLE
UI: checkbox to hide managedFields

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1858]
# Proposed Feature

UI should have a checkbox for hiding the `metadata.managedFields` stanza. 

# Motivation

The `metadata.managedFields` is for bookkeeping for backend services, but largely an annoyance for end users, and people don't care to see it. kubectl and Argo CD already hides this by default

# Suggested Implementation

Checkbox that special cases the removal of managedFields in the live object view.

**Comment by rbreeze** [comment]
Closing in favor of https://github.com/akuity/kargo/issues/1988
