### ISSUE TITLE
IAM auth to ECR support

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1885]
# Proposed Feature

Kargo needs to support IAM auth to ECR

# Motivation

ECR is a common container registry and we should have native support for it.

# Suggested Implementation

Follow guidelines here:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html

**Comment by jessesuen** [comment]
I think it may be possible to workaround this limitation until Kargo natively supports ECR, with a CronJob that periodically updates an image repository Secret that Kargo understands.

https://linuxhandbook.com/auto-update-aws-ecr-token-kubernetes/
https://skryvets.com/blog/2021/03/15/kubernetes-pull-image-from-private-ecr-registry/

Will try and formulate an official workaround.

**Comment by joebowbeer** [comment]
Can only a service account be used for ECR authentication? This is needed for IRSA or the newer Pod Identity method, and avoids the need for secrets.

For IRSA, an `eks.amazonaws.com/role-arn` annotation would be added to Kargo's service account.
For Pod Identity, the association would be pre-configured in AWS.

Keel implements a cache:

https://github.com/keel-hq/keel/blob/master/extension/credentialshelper/aws/aws.go

**Comment by krancour** [comment]
@joebowbeer I don't think this is something that can realistically be handled at the pod level.

Kargo's credentials are managed at the Project level. This means that two Projects can use two different sets of credentials (with entirely different permissions) for talking to the same registry. It also means Projects that have no business talking to that registry cannot, for lack of credentials. This is essential to Kargo's tenancy model.

If credentials were handled at the pod level, all Projects, even those that do not need them, would have identical permissions on the registry and this would seem to undermine the tenancy model.

**Comment by joebowbeer** [comment]
@krancour I interpret what you're saying to mean that, in Kargo, some inherent container identity can't be used to obtain the AWS creds.

I'm saying that there should be some method other than the less secure secretRef to obtain the creds.

ESO, for example, can obtain AWS credsFromSecretRef or credsFromServiceAccount (arn annotation)

https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/auth/auth.go

There's an open issue to support pod identity directly, which has collected comments similar to yours:

https://github.com/external-secrets/external-secrets/issues/2951

A workaround involving two associated roles is described here:

https://containscloud.com/2024/03/24/integrating-aws-secrets-manager-to-eks-using-external-secrets/

Paraphrasing in the context of Kargo:

> We will create two IAM roles and a policy and associate them with the EKS cluster using [EKS Pod Identity Agent](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html). The first role will be associated with the [Kargo] service account and has no policy associated with it while the second role is configured in the [Kargo Project] resource and will be assumed exclusively in this context, thus following the concept of least privilegies.

Reference:

https://securitylabs.datadoghq.com/articles/eks-pod-identity-deep-dive/

**Comment by joebowbeer** [comment]
Even as a highest common factor, I hope it is possible to obtain access without the use of Kubernetes secrets.

**Comment by yevgeniyo-ps** [comment]
ESO Used Generator for it: https://external-secrets.io/main/guides/generator/#reference-custom-resource
