### ISSUE TITLE
Add `--wait` to promotion command

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#1888]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Add a `--wait` option to `kargo promote` so the CLI won't return until the promotion succeeds or fails

Example:

`kargo promote --project kargo-demo --freight-alias frisky-wookie --stage test --wait`

# Motivation

Some users may opt to script (or use `kargo` cli in a CI process) and need the promote operation to be a blocking operation.

# Suggested Implementation

No suggestions but something to keep in mind is other places where a `wait` should be implemented. There should also be a timeout condition like in `kubectl` so it won't wait indefinitely (like `--timeout=300s`)

**Comment by hiddeco** [comment]
This has likely become more important since #1613, as Promotions can be long(er) running now.
