### ISSUE TITLE
Apply Warehouse Git subscription path filters to all CommitSelectionStrategy types

### ISSUE THREAD

**Issue by maksimstankevic** [akuity/kargo#1896]
This was raised by @krancour: "I only just noticed this now and didn't notice in [#1477](https://github.com/akuity/kargo/pull/1477) -- does this path filtering only work with the NewestFromBranch commit selection strategy? That appears to be the case and I'm now wondering why that is. (We can open a separate issue for this if we determine this was a mistake.)"

I started implementation of path filters aimed at only the NewestFromBranch CommitSelectionStrategy. Now after rethinking I believe it should not be restricted to the mentioned CommitSelectionStrategy but instead apply to all of the strategies. No matter if tag filters are used in a Git subscription - that should not prevent the option of additionally using path filters. In fact having both filtering types combined makes it more flexible in my opinion.

@krancour @hiddeco what do you think? If approved I'll take it.

**Comment by krancour** [comment]
@maksimstankevic agreed.

**Comment by maksimstankevic** [comment]
Sent https://github.com/akuity/kargo/pull/1918
