### ISSUE TITLE
kargo-admin/viewer missing privileges for events

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1905]
# Description

PR https://github.com/akuity/kargo/pull/1871 did not add the necessary read privileges for events. 

https://github.com/akuity/kargo/blob/main/charts/kargo/templates/api/cluster-role.yaml#L26-L35

This causes the error: `events is forbidden: list is not permitted` for SSO users.

# Screenshots

![image](https://github.com/akuity/kargo/assets/12677113/987cbd22-fd76-40a2-9e05-8cf42a702cb4)

# Steps to Reproduce

SSO users are affected, but I think `admin` user is not.

# Version

```
prerelease v0.6.0 (main as of today)
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by hiddeco** [comment]
We should probably think about adding something that makes this more likely to happen, or easier to test, on a local development environment. As I had the same happen to me not too long ago with another permission.
