### ISSUE TITLE
Promotions should be sorted lexicographically

### ISSUE THREAD

**Issue by hiddeco** [akuity/kargo#1930]
The ~~UI~~ API server appears to order Promotions for a Stage by their Phase and creation timestamp. However, as the creation timestamp does not include nanoseconds, this approach will fail when multiple Promotions are (programmatically) created within a short period.

To address this issue, it should use the ULID in the Promotion name, which allows it to be lexicographically sorted beyond the creation timestamp of the Promotion.

**Comment by webstradev** [comment]
Is this done by parsing the promotion name "shortName.ulid.shorthash" (maybe making a helper function on the Promotion struct for that) and sorting on that instead of the creation time?

**Comment by hiddeco** [comment]
It would not require parsing, the ULID component in the name would make any list entry sortable by default.

**Comment by hiddeco** [comment]
To clarify: as far as I am aware this is a frontend issue which would not require any changes to the backend.

**Comment by hiddeco** [comment]
See also: https://github.com/akuity/kargo/blob/769d1fc1e5b47cedd7b6a8f9032e30e25b354f7c/ui/src/features/stage/utils/sort.ts#L3

**Comment by webstradev** [comment]
> It would not require parsing, the ULID component in the name would make any list entry sortable by default.

Ah I see I didn't realize we are always dealing with the same prefix (stage name) so we can indeed just sort on the Name.

Are you sure we should be sorting this in the frontend and not in the api though. (would be a simple change)

**Comment by webstradev** [comment]
Maybe doing so doesn't solve the issue you originally raised, as you still have some more "advanced" sorting in the frontend with running promotions versus non running. But it would I believe still make sense to change this in the API as well, to ensure we are returning properly sorted results there as well.

**Comment by krancour** [comment]
Agree it's ideally a back end change. Re-labeling accordingly.

**Comment by webstradev** [comment]
Ill work on this.

**Comment by krancour** [comment]
Thank you!
