### ISSUE TITLE
Add sorting to Projects list page.

### ISSUE THREAD

**Issue by ed-boykin** [akuity/kargo#1945]
With Kargo 0.5.2, the Projects list page doesn't appear to sort the list of projects. The order will change apparently randomly each time a user returns to the list page. 

We are up to 26 project in Kargo and will be potentially doubling that soon. With the order changing, it's frustrating to have to hunt for the desired project.

We would like to see a sort applied and preference would be alphabetically.  Another option, would be to provide a 'sort' menu with sort options, such as A-Z, Z-A, etc.

**Comment by krancour** [comment]
Already fixed in `main` and `release-0.6` as of #1810
