### ISSUE TITLE
UI still shows objects as refreshing

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1968]
# Description

In v0.6.0, we no longer clear `kargo.akuity.io/refresh` annotation. Instead, we record the value into status `lastHandledRefresh` to indicate that it refreshed. The UI needs to adapt to this change, because it constantly shows resources as refreshing.

<img width="227" alt="image" src="https://github.com/akuity/kargo/assets/12677113/c79f3e99-715c-4a7e-af8e-a40d03f35b54">

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  annotations:
    kargo.akuity.io/refresh: "2024-05-07T17:22:27Z"
  creationTimestamp: "2024-05-07T00:50:04Z"
  generation: 1
  name: kargo-demo
  namespace: kargo-demo
  resourceVersion: "6053436"
  uid: 70cc1244-cd5a-4d02-a6ae-521e90f12d54
spec:
  subscriptions:
  - image:
      imageSelectionStrategy: SemVer
      repoURL: nginx
      semverConstraint: ^1.24.0
status:
  lastFreight:
    images:
    - digest: sha256:9f0d283eccddedf25816104877faf1cb584a8236ec4d7985a4965501d080d84f
      repoURL: nginx
      tag: 1.26.0
    name: 7108dff8f88f66318b3a1b8adb7519198d5d2cce
  lastHandledRefresh: "2024-05-07T17:22:27Z"
  observedGeneration: 1
```

# Steps to Reproduce

Refresh a Warehouse, probably others

# Version

```
v0.6.0-rc.2
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
Not sure if this affects CLI as well

**Comment by hiddeco** [comment]
It does not affect the CLI. The problem is that the frontend is looking at the wrong (non-existing) field, causing the value to always mismatch which spawns the loader.

It's being used correctly everywhere else.
