### ISSUE TITLE
Hide managed fields in UI doesn't work

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1988]
# Description

UI feature to hide managed fields doesn't work. Also, why is it showing the raw `Fieldsv1` instead of the json? I think this means it's not using the new RAW option in API.

# Screenshots

![image](https://github.com/akuity/kargo/assets/12677113/5486abc3-9f7a-4d5f-84b2-838b7b8a4cce)

# Version

```
v0.6.0
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by rbreeze** [comment]
@rpelczar Have you started this? If not I can pick this up

**Comment by rpelczar** [comment]
@rbreeze I have a fix for it.

> Also, why is it showing the raw Fieldsv1 instead of the json? I think this means it's not using the new RAW option in API.
@jessesuen That's correct. We don't use the new RAW option here, because we're getting Stage from Stages list. We can change it, but we will have additional requests.
