### ISSUE TITLE
proposed feature: more flexibility in "kustomize edit set image"

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2001]
From #1981:

> @Brightside56 Kargo Render passes images to the Argo CD Repo Server (which it uses as a library) i the form `url=tag`. Somewhere under the covers, the Argo CD Repo Server executes a `kustomize edit set image url=tag`. For Kargo's built-in Kustomize support, Kargo executes `kustomize edit set image url=tag` more directly...
>
> I see your issue is that the image URL varies from Stage to Stage.
>
> I believe your case can be addressed by adding more options to both Kargo Render and to Kargo's built-in Kustomize support such that the resulting command resembles this: `kustomize edit set image placeholder-url=stage-specific-url:tag` where `placeholder-url` and `stage-specific-url` are both things you specific in your promotion mechanisms on a Stage-by-Stage basis, which will leave the tag as the only part of the Freight that is applied from one Stage to the next.

**Comment by danielloader** [comment]
Would this permit adding a prefix to the image registry? We operate an ECR pull through cache in production but GHCR in staging, so that would be nice to be able to have the ability.

**Comment by krancour** [comment]
> Would this permit adding a prefix to the image registry?

I'm afraid I'm not entirely clear on what you are asking.

The proposal would permit the equivalent of `kustomize edit set image url1=url2:tag` where you would have full control over the values of `url1` and `url2` and `tag` would come from the Freight that is being promoted.

**Comment by danielloader** [comment]
Sorry for being unclear.

What you describe should do the required functionality.

**Comment by krancour** [comment]
v0.9.0 promotion steps address this and it's addressed for legacy git-based promotion mechanisms as well.
