### ISSUE TITLE
UI: Add more info to Stage details page

### ISSUE THREAD

**Issue by rbreeze** [akuity/kargo#2021]
Currently, at the top level Stage View, we only show Subscriptions. We also have tabs for Promotions, Verifications, and the Live Manifest.

There's a lot of information in the Live Manifest which would be useful to surface at the top level too, to prevent the need to parse the large and hard to read manifest. 

In addition, I think there's a better way to present Promos and Verifications, perhaps withinin the same tab (there's a lot of wasted space on virtually useless info, for example the Verification ID)

**Comment by krancour** [comment]
I'm going to close this because I feel the Stage view has improved since this was opened and I think we can open new issues if there are specific items we discover are missing or would be helpful.
