### ISSUE TITLE
Workload Identity auth to Google Artifact Registry

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2029]
# Proposed Feature

Kargo should support workload identity auth to GCR.

This issue is the GCR equivalent of https://github.com/akuity/kargo/issues/1885.

# Motivation

Users wish to avoid using long-lived static credentials to GCR.

**Comment by krancour** [comment]
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr
