### ISSUE TITLE
UI: add more details in Freight information panel

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#2045]
# Proposed Feature

Add information about images/git commit shas to the sliding panel that is shown when the user clicks on the Freight. 

# Motivation

In real life, image URLs are quite long and even tag does not fit into the tile or Freights panel:

<img width="378" alt="image" src="https://github.com/akuity/kargo/assets/426437/0967fef2-15c5-4ead-9f8b-f85f6f7aca1f">
(The actual tag is `0.13.1-0.20240518010429-d249393ea9c2`. )

The tooltip is the only way to see the tag. Adding full image URLs/git shas to the Freight panel would improve user experience.

# Suggested Implementation

**Comment by rbreeze** [comment]
Fixed in https://github.com/akuity/kargo/pull/1979
