### ISSUE TITLE
Cache headers for static resources

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#2056]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

Add cache headers to enable browsers to cache static assets.

# Motivation

Kargo UI loads quite heavy static resources: ~5.3 mb of Javascript, and ~ 0.5 mb of CSS + fonts. Adding cache header would reduce load time and improve user experience. 

# Suggested Implementation

Cache headers needs to be added in dashboard hander: https://github.com/akuity/kargo/blob/da05fa797ba9b594711e4aecd8463df9ed7a0169/internal/api/server.go#L269

**Comment by krancour** [comment]
@rbreeze tentatively assigning to you. I think you are probably more familiar with the appropriate headers for a SPA than I am.
