### ISSUE TITLE
Promotion with multiple Git changes only completes one.

### ISSUE THREAD

**Issue by BenHesketh21** [akuity/kargo#2064]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I have ran kargo using the hack-kind-up command.
I have created a simple project, warehouse and stage, included below. My stage has 2 images to update in a GitRepo and it completes one of them in the commit but not the other even though both have changed and the commit message even says it should have changed it.

# Screenshots

![df046321-aec9-4b83-9d73-23bb166e8f2e](https://github.com/akuity/kargo/assets/55387271/c1e32aee-f22f-47c7-ad09-de1c75a10746)

# Steps to Reproduce

All the Kargo manifests are in the repo in the Kargo Pipelines folder: https://github.com/BenHesketh21/gitops-release-branches-argo/

# Version

main

# Logs

The Kargo controller from the logs didn't seem to encounter an error. Please let me know if theres any other logs that would be useful.

```
time="2024-05-27T19:50:09Z" level=debug msg="begin promo" namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172
time="2024-05-27T19:50:09Z" level=info msg="began promotion" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main
time="2024-05-27T19:50:09Z" level=debug msg="found associated Stage" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main
time="2024-05-27T19:50:09Z" level=debug msg="executing promotion mechanisms" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main
time="2024-05-27T19:50:09Z" level=debug msg="executing Git-based promotion mechanisms" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main
time="2024-05-27T19:50:09Z" level=debug msg="executing Helm promotion mechanism" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main
time="2024-05-27T19:50:09Z" level=debug msg="obtained credentials for git repo" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 repo="https://github.com/BenHesketh21/gitops-release-branches-argo" stage=tenant1-test-main
time="2024-05-27T19:50:10Z" level=debug msg="done executing Helm promotion mechanism" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main
time="2024-05-27T19:50:10Z" level=debug msg="done executing promotion mechanisms. aggregated status: Succeeded" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main
time="2024-05-27T19:50:10Z" level=debug msg="done executing promotion mechanisms. aggregated status: Succeeded" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main
time="2024-05-27T19:50:10Z" level=debug msg="promotion Succeeded" freight=107b172076375975fde424f982458b2fc81ed3eb namespace=test-main promotion=tenant1-test-main.01hyxsmt4cfks0sqk7vc0tk65t.107b172 stage=tenant1-test-main targetFreight=107b172076375975fde424f982458b2fc81ed3eb
```

**Comment by BenHesketh21** [comment]
Hi @krancour. Thank you for getting back to me. My mistake you are right, getting rid of the `.` fixed it. And looking closer, I can see it didn't work for the one in the screenshot it just removed the new line. I'm happy to close the issue. Is there an issue for documenting/having helm examples? I'm happy to help with that if it's not there already.

**Comment by krancour** [comment]
Glad you're back in business.

> Is there an issue for documenting/having helm examples? I'm happy to help with that if it's not there already.

Thanks @BenHesketh21. There isn't an open issue for it yet. There should be.

The CRDs are very "deep," so it would be an exhaustive effort to provide examples of _everything_ Kargo can do, which is why we link to the CRD docs, since the hope is that they give broad coverage to the full gamut of options...

With that said, we definitely do need to have _proper_ docs for common use cases. And help would indeed be most welcome!

I think we're probably overdue for creating two new branches in the doctree -- "User Reference" and "Operator Reference" -- and that the docs you have proposed fit somewhere under "User Reference."

Wondering if @christianh814 would be willing to help with plotting a sensible approach to expanding the docs.
