### ISSUE TITLE
add docs about argocd-update step and Argo CD sync windows

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2078]
# Description

Kargo replicates the Argo CD server sync logic, but I believe misses out on the sync window check:

https://github.com/argoproj/argo-cd/blob/ef37b3975406ac58bd527990d247071f38198963/server/application/application.go#L1812-L1814

Kargo should honor the sync window of an AppProject, since users often use this to prevent deploys at a certain time.

# Steps to Reproduce

Promote a Stage backed by an Argo CD application and where the AppProject itself is in a window

# Version

```
v0.6.0
```

**Comment by jessesuen** [comment]
I think https://github.com/akuity/kargo/issues/1328 may supersede this.

**Comment by krancour** [comment]
I agree. At this point we've isolated about 90% of Kargo's integration with Argo CD to the argocd-update step and the goal is to eventually get that to 100%. So a solution that doesn't rely on other parts of Kargo being tightly coupled to Argo CD is preferable. I'll close this in favor of #1328

**Comment by jessesuen** [comment]
Reopening based on user feedback where #1328 would not be sufficient. For this user, not everything will be managed by kargo pipelines they already heavily use argo cd sync windows. They do not want some things to be managed by kargo windows and others to be managed by an Argo CD window. So they prefer to rely solely on Argo CD windows and Kargo to just honor it.

This is how I think the feature should work: today, we blindly set the `.operation` on an application without considering the Argo CD window. Instead, we should consult the window before setting the operation. If the window is closed, the step will remain in a Running phase until the window is open. As a result, the Promotion will also remain `Running` indefinitely, which I would argue is the expected behavior.

This should satisfy the requirement that argo cd logic is still mainly isolated to the `argocd-update` step.

**Comment by krancour** [comment]
Ah. This makes sense. When we spoke offline, I was questioning how Kargo was supposed to honor Argo CD sync windows when Kargo _isn't_ managing an App. I see now that the real desire is to manage sync windows entirely in one place, _regardless_ of whether Kargo manages the App or not. Makes perfect sense. And easy to do.

**Comment by krancour** [comment]
We can do this in v1.2.

**Comment by krancour** [comment]
I'm reclassifying this as an enhancement. This wasn't a bug. It was just functionality we hadn't built.

**Comment by krancour** [comment]
Argo CD has fixed this as of v2.11 so that the AppController enforces sync windows instead of only relying on the API server to do so.

I'm going to keep this issue open, but re-categorize it as a doc issue.

I'll update docs to note that sync windows are respected only if using Argo CD v2.11+ and that if you anticipate encountering an active deny window, you should set the timeout on your `argocd-update` step accordingly.
