### ISSUE TITLE
bug?: github prs may not be working for github enterprise

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2080]
I know @jessesuen had intended for PRs to GitHub Enterprise to work, as evidenced by the predicate used when registering the GitHub implementation of the `GitProviderService` interface:

https://github.com/akuity/kargo/blob/2d4aaf579625fd723ea4b3941c226ec9bea23d5e/internal/gitprovider/github/github.go#L22-L32

However, this function is used several places throughout that implementation and appears that an error will result for any URL not beginning with `https://github.com`:

https://github.com/akuity/kargo/blob/2d4aaf579625fd723ea4b3941c226ec9bea23d5e/internal/gitprovider/github/github.go#L149-L156

**Comment by jessesuen** [comment]
yuck. definitely looks like a bug to me. Probably should switch to using golang's `url.Parse` instead of the regexp and extract the paths parts. By the time we've gotten here, we've already decided the host is github/github enterprise and don't care about the hostname.

**Comment by krancour** [comment]
Happy to fix it.
