### ISSUE TITLE
OIDC sub isn't cast as a string and thus Service Account can't apply with a numeric sub value

### ISSUE THREAD

**Issue by danielloader** [akuity/kargo#2120]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I can't apply a helm chart with oidc configured for subs since I'm using zitdel as my IdP. I propose we stringify this value for the service account object.

# Steps to Reproduce

Use zitadel and have int64 sub values.

# Version

0.7.0-rc.2

**Comment by krancour** [comment]
Nice find. I think this is also a problem for Entra (formerly AAD). Groups can also be numeric.

**Comment by danielloader** [comment]
Thanks a lot for the help.
