### ISSUE TITLE
Error on latest `kargo-render-action` GitHub action

### ISSUE THREAD

**Issue by hoopty** [akuity/kargo#2131]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

Bug report from https://github.com/akuity/kargo-render-action/issues/5 posting here for visibility

# Screenshots

See https://github.com/akuity/kargo-render-action/issues/5

# Steps to Reproduce

See https://github.com/akuity/kargo-render-action/issues/5

# Version

```
uses: akuity/kargo-render-action@v0.1.0-rc.39
```

# Proposed Fix 

I have submitted a fix PR at https://github.com/akuity/kargo-render-action/pull/6

**Comment by blakepettersson** [comment]
Fixed by akuity/kargo-render-action#6
