### ISSUE TITLE
UI: Warehouse hide/show button think's it's a promote button. 

### ISSUE THREAD

**Issue by dhpup** [akuity/kargo#2137]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.
* [X] I've pasted logs, if applicable.

# Description

When hovering over the Warehouse's show/hide button, it shows the tooltip to promote to a stage. 

# Screenshots

<img width="460" alt="warehousebutton" src="https://github.com/akuity/kargo/assets/21094282/761abd6b-711d-4396-a02b-0494f43ac47f">

# Steps to Reproduce

Hover over Warehouse hide/show button.

# Version

```
Server Version: fix/ci, Latest
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by krancour** [comment]
Including this in v0.8.0 only because it's exceptionally small.
