### ISSUE TITLE
ui: intent of approved by column in promotions view is unclear (bug?)

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2146]
#2089 added a new "Approved By" column to a Stage's Promotions view.

1. What was this meant to reflect? Approval of _what?_ It has the appearance of showing _who approved a Promotion_, but short of a Promotion involving a pull request, Promotions don't _have_ approvers.

2. It seems to be populated with a value (if one exists) from the `kargo.akuity.io/create-actor` annotation.

    This is how that annotation is used:

    https://github.com/akuity/kargo/blob/9aa396b898227ed56cca7be92c72e2425ef90324/api/v1alpha1/annotations.go#L6-L9

    It appears to me that this column will actually show who _created_ the Promotion. Was that, perhaps, the actual intent behind it and "Approved By" is merely a poor column heading?

@rbreeze you reviewed #2089. Do you have any insight into this?

**Comment by rbreeze** [comment]
@krancour I believe you are correct that the intent is to display who created it - I'll update the header
