### ISSUE TITLE
bug: failed promotions are no longer showing why they failed

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2162]
The `status.message` field seems as if it is no longer being set.

**Comment by krancour** [comment]
Emphasis on _failed_, which is a different phase from _errored_.

I am going to dig deeper. I think it may be one specific scenario that triggers this.

**Comment by krancour** [comment]
It seems this occurs when the Argo CD promotion mechanism fails because the App had an error syncing.

**Comment by hiddeco** [comment]
Fixed by #2179.
