### ISSUE TITLE
UI: Stage Timestamp shows freight creation date, not freight promotion date.

### ISSUE THREAD

**Issue by dhpup** [akuity/kargo#2171]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate feature request.
* [X] I've pasted the output of `kargo version`, if applicable.
* [X] I've pasted logs, if applicable.

# Proposed Feature

Right now the Timestamp shows the freight creation date, would it make more sense to show when the promotion occured? 

This came as I tested multiple Stages with auto-promote enabled. But left a Stage lingering in a progressing state for a long while (verification). Once the verification was complete, it showed the next Stage with a timestamp that wasn't recent which was what I expected.

<img width="455" alt="Screenshot 2024-06-14 at 9 44 24 AM" src="https://github.com/akuity/kargo/assets/21094282/97547e30-5afd-49c9-bf6c-eea6a531e5fb">

# Motivation

Clarity in the UI for end users.

# Suggested Implementation

Should it show promotion date instead?

**Comment by krancour** [comment]
@rbreeze this needs a small back-end change as well.

We need to start recording the time that a Stage's current promotion transitions to become its last promotion.

I propose this to be a new `CompletionTime` field in the `PromotionInfo` struct (which I think could stand to be renamed as `PromotionReference` while we are at it, as that is more consistent with `FreightReference`).

cc @hiddeco for a sanity check.
