### ISSUE TITLE
CLI download links from UI

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2176]
# Proposed Feature

The UI should provide convenience links to download the `kargo` CLI for each architecture that we support from GitHub releases.

# Motivation

A user we were helping did not know where to download the kargo CLI.

# Suggested Implementation

Release links can be formulated from version, os, and architecture. e.g:

https://github.com/akuity/kargo/releases/download/v0.7.1/kargo-darwin-amd64

**Comment by krancour** [comment]
Where would we tentatively put these? I'm thinking of a new tab on the home page. The home page is currently just the list of all Projects, but a tabbed interface would be nice. I expect we'd eventually be needing a tab for system-level settings and/or RBAC as well.
