### ISSUE TITLE
Don't show old freights in freights line

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#2185]
# Checklist

* [x I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

It seems like the freight line keeps showing all the freights it's ever discovered . The UI is getting slower and slower with each new freight. Some way to cleanup old freights that belong to no stage is required.

# Steps to Reproduce

Keep using Kargo and see how freights never disappear from freight line. 

# Version

```
v0.7.0
```

**Comment by jessesuen** [comment]
Discussed offline and it's an issue specific to our setup. Closing.

**Comment by krancour** [comment]
@jessesuen @alexmt lmk if you think changes to the default gc settings are in order.
