### ISSUE TITLE
proposal: ui: hide truck icon when not useful?

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2247]
@rbreeze is it feasible to hide the truck icon on a Stage when it has _only one_ Stage immediately downstream?

If we have A --> B, clicking the truck on A or the target on B have the same effect.

What I'm hoping for here is that the function of the truck icon becomes more clear if it is contextually displayed only when useful.

**Comment by rbreeze** [comment]
@krancour Yeah that should be possible!

**Comment by rbreeze** [comment]
I just realized that this has already been solved, I think. The original issue was here: https://github.com/akuity/kargo/issues/1867

Locally, running tip of main, I don't see the promote subscribers button if there is only one downstream subscriber. Going to close this for now, feel free to reopen if you find a situation where this isn't true

**Comment by krancour** [comment]
I'm not sure what branch I must have been looking at when I opened this.

Checking the tip of the multi-pipelines feature branch, it does indeed appear to have been addressed.

Sorry for the noise.

**Comment by krancour** [comment]
Ah! Found it.

![Screenshot 2024-07-08 at 10 07 24 PM](https://github.com/akuity/kargo/assets/1821014/ea6674bb-c73a-43ac-9d8b-74682512eea5)

My best guess is that the two edges are incorrectly being counted as "two downstream Stages," leading to the appearance of the truck icon.

**Comment by krancour** [comment]
Note that this doesn't need to be fixed for v0.8.0. There are higher priority fixes to work on, so I'll add this to the v0.9.0 milestone.

**Comment by rbreeze** [comment]
Oh good catch, thank you! This should be a straightforward fix

**Comment by krancour** [comment]
@rbreeze if it's that simple, we can still sneak it into 0.8. It's your call.

**Comment by krancour** [comment]
Closed by #2274
