### ISSUE TITLE
Create commits with graphql API

### ISSUE THREAD

**Issue by shmargum** [akuity/kargo#2310]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Proposing that Kargo can create and push commits/prs with graphql API.

# Motivation

Creating commits with the graphql API will sign them with GitHub's gpg key, so a separate gpg key does not need to be generated and associated with a real user.

# Suggested Implementation

https://github.blog/changelog/2021-09-13-a-simpler-api-for-authoring-commits/

**Comment by krancour** [comment]
This is something we won't do directly, but as the promotion steps introduced in v0.9.0 become extensible over the coming releases, this will become something that could be addressed by a third-party step.
