### ISSUE TITLE
cleanly reinstalled cluster & kargo, after performing sso login, kargo is in a loop refreshing page

### ISSUE THREAD

**Issue by lknite** [akuity/kargo#2359]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I login and the page redirects to:
https://kargo.vfp-admin.k.home.net/token-renew?redirectTo=/

Then it redirects to:
https://kargo.vfp-admin.k.home.net/

Then it repeats without end

# Screenshots

![image](https://github.com/user-attachments/assets/79284e01-ed13-4936-9dad-55a6f45b849d)

# Steps to Reproduce

# Version

helm chart 0.8.1

# Logs

```
[kargo-api-6f69f9749c-9kt4b] time="2024-07-28T20:47:34Z" level=info msg="finished unary call" connect.duration="11.52µs" connect.method=GetPublicConfig connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2024-07-28T20:47:34Z"
[kargo-api-6f69f9749c-9kt4b] time="2024-07-28T20:47:36Z" level=info msg="finished unary call" connect.duration="22.993µs" connect.method=GetPublicConfig connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2024-07-28T20:47:36Z"
```

# attempt to fix
- went back to helm chart 0.7.1 and things started working, so maybe this is an oidc/login issue with 0.8.1?
- i enabled log level DEBUG and didn't see anything new

**Comment by stephaneetje** [comment]
+1 , same problem here

**Comment by krancour** [comment]
@rbreeze is this possible related to https://github.com/akuity/kargo/pull/2282?
