### ISSUE TITLE
UI: Link to ArgoCD from stage includes "/argocd"

### ISSUE THREAD

**Issue by BasJ93** [akuity/kargo#2370]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.
* [X] I've pasted logs, if applicable.

# Description

When clicking on the link to ArgoCD shown in the Stage UI, the generated link results in a "not found" state in ArgoCD. This appears to be because Kargo generates a link in the format `<argocd.host>/applications/argocd/<app-name>` while ArgoCD it self uses the format `<argocd.host>/applications/<app-name>`.

# Steps to Reproduce

Using Kargo V0.7.0 and ArgoCD v2.10, click the `ArgoCD` link in a stage UI.

# Version

kargo V0.7.0
ArgoCD v2.10

**Comment by krancour** [comment]
The link is actually not of the form `<argocd.host>/applications/argocd/<app-name>`, rather it is of the form `<argocd.host>/applications/<app-namespace>/<app-name>` and as far as I can see, that is correct, but maybe someone better versed in Argo CD than myself can comment on whether there are circumstances under which that is _not_ the correct path for an Application.

@rbreeze I figure you will probably know?

**Comment by rbreeze** [comment]
@krancour Yep you're correct, that is the path for an Argo CD app. Given that this was due to config, going to close out this issue... @BasJ93 feel free to reopen if you feel it's necessary
