### ISSUE TITLE
Request: Allow anonymous read-only access to Kargo demo 

### ISSUE THREAD

**Issue by mubarak-j** [akuity/kargo#2376]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

I tried to access to Kargo demo page (https://kargo.demo.akuity.io/) but received the following error after authorizing GitHub OAuth app for Dex
```shell
Internal Server Error
Failed to authenticate: github: user "mubarak-j" not in required orgs or teams
```

# Motivation

Similar to Argo CD demo page (https://cd.apps.argoproj.io/) it would help interested new users view Kargo capabilities and get familiar with it and what to expect before diving into implementation.

# Suggested Implementation

Unless, this is inationally restricted for security reasons (which I'd understand) I think show casing Kargo potential to new users would help drive adoption, interest and more community discussion :)

**Comment by krancour** [comment]
@mubarak-j that URL is indeed for Akuity's own, private use.
