### ISSUE TITLE
GitHub App as Image Registry-Specific Authentication Option

### ISSUE THREAD

**Issue by joaoestrela** [akuity/kargo#2383]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

Support GitHub App auth as Image Registry-Specific Authentication Option

# Motivation

Some users might be using GHCR as their image registry, currently it is only possible to use Kargo with public ghcr.io or use username/password which isn't a best practice for machine to machine auth

**Comment by Dhouib-Mohamed** [comment]
@krancour If possible I would like to take this issue
Can you provide me with more information about the related files to start with since this is my first contribution

**Comment by krancour** [comment]
@Dhouib-Mohamed it _might_ be as simple as a small change here to allow this helper to work for image repos in addition to git repos:

https://github.com/akuity/kargo/blob/a01f04939e8632c67c144be2e263d719b481d6c0/internal/credentials/kubernetes/github/app.go#L59

You'll want to test it out a bit though to verify it works as intended in case I am overlooking something.

**Comment by krancour** [comment]
With major thanks to @Dhouib-Mohamed who did a fair amount of work on this issue in #2391, we have come to the conclusion that this requested feature is not technically possible at the moment.

Despite all appearances (a package permissions option when configuring a GitHub App), an App installation token simply cannot enable access to a private ghcr.io package repository.

And here is an existing, 2+ year old thread about this very topic:

https://github.com/orgs/community/discussions/34324

I am tentatively closing this issue, but if anyone knows something that we don't -- if you have seen this work or personally done it, please do feel free to share your experience or even re-open the issue.
