### ISSUE TITLE
ui intermittently shows current freight as empty

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#2384]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.

# Description
Looks like https://github.com/akuity/kargo/issues/2094 again. UI intermittently incorrectly shows that the stage has no freight. Browser refresh resolves it.

# Screenshots

<img width="1301" alt="Screenshot 2024-08-05 at 8 42 02 AM" src="https://github.com/user-attachments/assets/b37d4e52-53f0-4b67-8dca-2bc70b20c060">

# Steps to Reproduce

Issue sometimes happens after opening kargo UI, switching to the different tab and back.

# Version

```
v0.8.2
```

**Comment by rbreeze** [comment]
@alexmt I can't seem to reproduce this, can you attempt to reproduce in `main`? This way if it is fixed as I suspect we can isolate the portion that fixed it and back port it. `main` contains a large refactor/redesign PR which I believe fixed the issue so want to confirm this.

**Comment by danielloader** [comment]
Happens to me when I have kargo in a background idle tab, and multiple promotions have taken place in that state and then going back to the tab I can see the freight on the line but it just says empty on the stage - refreshing the page gives the correct information.
