### ISSUE TITLE
Option to only show running Freight in timeline

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2386]
# Proposed Feature

One simple UI feature I thought of while filing https://github.com/akuity/kargo/issues/2385, was a UI option to only show running freight in the UI.

# Motivation

User may not care to see non-running freight, or there is just so much freight to sift through.

# Suggested Implementation

Show a checkbox or toggle to only show running freight.

**Comment by jessesuen** [comment]
When hiding non-running freight, we should still show some indicator in the freight timeline that shows how many freight are between the running Freight. e.g:

<img width="651" alt="image" src="https://github.com/user-attachments/assets/da9d2c2b-2447-4f43-82c6-222826e6ee62">

**Comment by krancour** [comment]
This is similar to something else @rbreeze added recently where old Freight, no longer in use can be hidden -- but that obviously doesn't help much if the situation is more that you have a long string of Freight that aren't in use, book-ended by two that still are.

So I think the existing binary choice of show all / hide old could become a three-way choice of show all / hide old / hide unused.

**Comment by rbreeze** [comment]
I've been thinking about this since I introduced the "hide old freight" feature... and I think we can actually just _change_ the "hide old freight" button behavior to hide unused freight. In other words, it will still be a binary choice between **show all** and **hide unused**.

@krancour, @jessesuen thoughts? It seems rare that someone would want to hide _just_ old freight but not unused intervening freight.

**Comment by krancour** [comment]
> It seems rare that someone would want to hide just old freight but not unused intervening freight.

I feel uncertain of this.

Let F be newest and A be oldest.

I have F in dev, E and D currently unused, C in prod, and B and A currently unused.

E and D seem to me that they may still be candidates for promotion into some Stage(s) after dev, up to an including prod, whereas B and A seem like Freight I am just pretty much done with.

While I favor simplicity, I think we probably do need to accommodate all of:

1. Show me everything
2. Show me just what's in use (hide unused)
3. Show me what seems most relevant (hide old)
