### ISSUE TITLE
GitHub thinks kargo's writeBranch has related history to main

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2406]
# Proposed Feature

A source of confusion when kargo writes to another branch, is this message from GitHub

<img width="374" alt="image" src="https://github.com/user-attachments/assets/41f3002a-f61a-4585-bbd5-516d6efb887c">

I believe the way that we are creating the branch causes GitHub to think this. Other tools (like https://github.com/helm/chart-releaser-action and https://github.com/marketplace/actions/github-pages-action), generates a gh-pages branch that does not show this message, which makes me think it should also be possible to do with Kargo

# Motivation

This message confuses users into thinking the branches have shared git history, when they don't.

# Suggested Implementation

Do whatever https://github.com/marketplace/actions/github-pages-action does.

**Comment by hiddeco** [comment]
We likely need to use the `--orphan` option when creating the branch to detach it from any other branch.

**Comment by jessesuen** [comment]
I recall that [we already do this](https://github.com/akuity/kargo/blob/a5cf96248c20d5c4c287ea38fbdf49f6f90a2512/internal/controller/git/git.go#L374-L385). So something else seems to be at play. Hopefully it's not GitHub special casing a branch named `gh-pages`, but that wouldn't surprise me.

**Comment by hiddeco** [comment]
Any chance this branch originates from before Kargo started to do this? As based on the message from the screenshot, it does appear they do have commits in common.

I will double check the behavior with a dummy branch anyway.

**Comment by jessesuen** [comment]
> Any chance this branch originates from before Kargo started to do this? 

I checked the initial commit of a Kargo write branch, and it has no parents. So no.
https://github.com/jessesuen/kargo-advanced/commit/955a3d19976dfbc136623d28e779cd90ac34212f

It seems to be a known problem:
*  https://stackoverflow.com/questions/61949364/git-orphan-branch-this-branch-is-1-commit-ahead-n-commits-behind-master
* https://github.com/orgs/community/discussions/125555

I just tried an experiment. I created a new branch on a git repo that is even/derived from a `gh-pages` branch, but named it `gh-pagez`. 

The `gh-pagez` branch shows the message:

<img width="935" alt="image" src="https://github.com/user-attachments/assets/aab6b5a1-794a-4a7c-9ce1-044f258426e1">

But the original `gh-pages` does not.

**Comment by jessesuen** [comment]
Next I tried the opposite experiment. I created new branch derived from `main`, but made it 1 commit behind main and called the branch `gh-pages`. In this case, GitHub does *not* show a message about being behind the main despite having an almost identical history.

So this is definitely GitHub special casing a branch named `gh-pages`.

**Comment by jessesuen** [comment]
Closing this since there's nothing we can really do about this in Kargo, unfortunately.
