### ISSUE TITLE
Support Multi-cluster Argo CD and Argo Rollouts

### ISSUE THREAD

**Issue by charles-teese-telestream** [akuity/kargo#2425]
From what I can tell, right now the kargo controller can optionally connect to two other k8s clusters. One for a remote argocd cluster, and one for a cluster with remote kargo resources. And argo rollouts appears to be able to point at either of these clusters, but this part is still unclear to me. I figure that supporting multiple clusters will use the same implementation for all three of these use-cases so that's why I'm not making separate issues. We'd like to be able to have multiple argocd clusters for different environments and promote freight between them. It would also be useful to connect all of our clusters' argo-rollouts controllers for analysis templates to kargo. I assume the implementation could look similar to how argocd handles connecting to different clusters.

**Comment by krancour** [comment]
> I assume the implementation could look similar to how argocd handles connecting to different clusters.

Which is quite frowned upon on security grounds. A hub and spoke architecture wherein a centralized component has highly privileged credentials for multiple clusters makes that one component a high value target. If an Argo CD control plane manages multiple clusters and is compromised, all your clusters are compromised.

Kargo deliberately sought to avoid this weakness from the start.

With Kargo, you run one, centralized control plane, but you distribute your controllers around your clusters to be "near" your Argo CD control planes. (i.e. Typically one Kargo controller to one Argo CD control plane -- usually on the same cluster.) These distributed controllers all "phone home" to the Kargo control plane.

What you want to do is 100% achievable already -- just not in the way you were imagining it.

**Comment by krancour** [comment]
There are reasons I won't go into that this wasn't yet documented, but internally, the maintainers have now agreed that we will move forward with closing this documentation gap.

**Comment by kgtw** [comment]
Hi @krancour, apologies for commenting on a closed issue. Has there been any progress made on creating the documentation for this distributed architecture?
