### ISSUE TITLE
bug: not checking if app sources are synced correctly in some common cases

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2427]
Another entry in the saga that is #1922 #2390 #2402.

Prior to #2390, during promotion, for each `ArgoCDAppUpdate` promotion mechanism, we unconditionally checked whether we needed to "update" the corresponding Argo CD Application. Update includes a forced sync. Determining whether this was required involved looking at operation status and, if successful, determining whether Application sources were synced to desired revisions (for any artifact where the desired revision can be determined; i.e. for any artifact in the Freight). A specific benefit to this was that operations that weren't complete blocked the Promotion from being considered completed and if/when an Application was observed to have source(s) not synced to the desired revision, the sync would then be initiated because the App "must update."

#2390 and #2402 are variations on accounting for outlying cases where the desired revision of a source cannot be known. #2402, makes the mistake of equating an `ArgoCDAppUpdate` promo mechanism that has no child `ArgoCDSourceUpdate` mechanisms with the unknowability of desired revisions of each source. In such a case, an App sync is initiated and immediately considered complete with the presumption that we wouldn't know how to judge its completeness accurately even if we did wait.

https://github.com/akuity/kargo/blob/81d085e1823b16738ae234c08d482d1765c2704a/internal/controller/promotion/argocd.go#L138-L155

This ends up bypassing the process that could have determined desired revisions (despite the absence of any `ArgoCDSourceUpdate`s; if it's in the Freight, we know it). The result is that in a number of common cases, we prematurely, and possibly incorrectly, count Promotions as complete and successful when the underlying Application(s) sources correct revisions were knowable, but were not checked.

**Comment by jessesuen** [comment]
>  such a case, an App sync is initiated and immediately considered complete with the presumption that we wouldn't know how to judge its completeness accurately even if we did wait.
> The result is that in a number of common cases, we prematurely, and possibly incorrectly, count Promotions as complete and successful

It seems to me what needs to be added back is the "waiting" portion. Although we can't know what commit shas we should have synced to, what we **_can_** do is wait for the operation that we just initiated to finish. Do you think this might be a way to address both concerns (the unknowability of a revision but the need waiting for the sync to complete)?

**Comment by krancour** [comment]
Something like that. I think we basically need to rewind a bit to when we were doing just that and find a different strategy for determining if we need to "click sync" that won't pre-empt the assertions that sources have have synced to known desired revisions.
