### ISSUE TITLE
make it possible to restrict permission to read secrets to allowed namespaces

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#250]
In a conversation with @jessesuen today, he noted that some users will be reticent to grant cluster-wide read permissions on Secrets to Kargo.

We need to make is _possible_ to restrict Kargo's access to Secrets in particular namespaces, even if we elect not to make that the default.

This is relatively low priory at the moment.

**Comment by krancour** [comment]
@jessesuen I've been thinking about how to achieve this and it occurred to me that this might overlap with #558.

i.e. I was assuming #558 would be solved with a new controller that is less vulnerable to attack than the API server by virtue of not being exposed to the outside world. It would use broader permissions to orchestrate more narrow permissions for the API server...

Then it occurred to me that the API server doesn't touch secrets at all (at least not yet). Until/unless that is no longer the case, it is only the existing Kargo controller that can read secrets in all namespaces -- and that's the very same permission we'd have to give to the onboarding controller.

In a nutshell... I don't think there's anything to do here until/unless we need to start allowing the API server to access secrets in project namespaces.

wdyt?

**Comment by jessesuen** [comment]
Yep, I agree this is probably unnecessary.
