### ISSUE TITLE
docs: moving `kargo` to a `PATH` directory (minor)

### ISSUE THREAD

**Issue by fykaa** [akuity/kargo#2503]
### Checklist:
- [x] I've searched the issue queue to verify this is not a duplicate feature request.
---

### Proposed Feature:
In [documentation](https://kargo.akuity.io/quickstart/#installing-the-kargo-cli) at several places

Currently, the instructions say:

> Then move `kargo` to a location in your file system that is included in the value of your `PATH` environment variable.

To make it easier and more user-friendly for everyone, we can suggest a command such as:

```bash
mv kargo $(echo $PATH | tr ':' '\n' | grep -m 1 "")
```
or `export PATH=$PWD/bin:$PATH`

### Motivation: Convenience
Providing a ready-to-use command will simplify this process and reduce confusion. when users are setting up `kargo`, this command could save time

**Comment by nitishfy** [comment]
A simple fix is - `mv kargo /usr/local/bin/kargo`

**Comment by krancour** [comment]
I think we need to be careful here on a few different fronts:

1. `mv kargo $(echo $PATH | tr ':' '\n' | grep -m 1 "")` might be written more clearly as `mv kargo $(echo $PATH | tr ':' '\n' | head -n 1)`, but...

1. This doesn't seem ideal, necessarily. The `kargo` CLI will end up on whatever the _first_ `PATH` location is. On my system, that happens to be `/Users/krancour/Library/pnpm`. If I uninstall pnpm, that directory will most likely be removed. The most sensible place, `/usr/local/bin` is _way_ down the list.

1. The original proposed command only works on *nix OSes. We can and do assume _contributors_ using Windows are also using WSL, but be cannot make the same assumption of _users_. We would have to provide the equivalent command for PowerShell... I'd rather minimize the time we waste on such things.

1. The alternative proposal of `mv kargo /usr/local/bin/kargo` makes an assumption that `/usr/local/bin` is on the `PATH` and that feels _fairly_ safe, but I doubt universal.

I have to say that this is a case where I think the _best_ solution is to trust that whether they are a *nix or Windows user, someone apt to use Kargo in the first place knows how to move something onto their `PATH`.
