### ISSUE TITLE
fix: standardize configuration field naming

### ISSUE THREAD

**Issue by fykaa** [akuity/kargo#2518]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.

# Proposed Feature

Improve Consistency in Configuration Field names

We've noticed inconsistencies in the [naming of configuration fields](https://github.com/akuity/kargo/blob/main/charts/kargo/values.yaml). 

For example, `api.rollouts.integrationEnabled ` does not follow the same pattern as other fields like `.api.oidc.enabled` or `.api.adminAccount.enabled`. While there’s currently no immediate blocker, aligning these fields for better uniformity before GA would help improve the clarity and maintainability of the configuration.

**Comment by krancour** [comment]
Let's not limit this to the API, but audit this throughout the entire values.yaml file.

**Comment by krancour** [comment]
I am also moving this to v0.9.0 because with any sort of breakage, sooner is always better than later.
