### ISSUE TITLE
UI appears distorted when the project does not exist

### ISSUE THREAD

**Issue by nitishfy** [akuity/kargo#2527]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

If you delete the project and refresh the UI for the deleted project path, the UI will appear distorted.

# Screenshots

![image](https://github.com/user-attachments/assets/78fef2c8-dc46-409e-92f3-28c345854692)

# Steps to Reproduce

Go to the `/project/unknown-project` endpoint of the kargo and you'll see the UI a bit distorted.

# Version

```
Client Version: v0.8.7
Server Version: v0.8.7
```

**Comment by krancour** [comment]
When that Project view initially loads, I think there's an opportunity to perform a get project request and gracefully handle a 404.

That being said, the UI also periodically refreshes all elements, so if you delete a Project (using the CLI or something) and _don't_ refresh the Project view, I think you're still going to end up seeing all these individual errors that result _not_ from looking for a Project that doesn't exist, but result from looking for things like Warehouses, Stages, and Freight _belonging_ to a Project that no longer exists.

I'm not sure of the best way to deal with this.

cc @rbreeze @rpelczar you guys probably have much better insight into how to improve the UX here.
