### ISSUE TITLE
docs: Kargo's ability to adopt existing namespaces

### ISSUE THREAD

**Issue by fykaa** [akuity/kargo#2528]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate feature request.
To create a GitHub issue for adding documentation regarding the ability to adopt existing namespaces in Kargo, as suggested by krancour, you can use the following template:

---

There is a need to document the capability for Kargo projects to adopt existing namespaces that are labeled with `kargo.akuity.io/project: "true"`. This feature allows users to create namespaces with the necessary labels before defining the Kargo project, which also ensures compliance with security best practices.

## Motivation

Currently, users may not be aware that they can create a namespace with specific labels and then link it to a Kargo project. Documenting this process will help users streamline their workflow and adhere to security guidelines more effectively.

### Suggested doc content

1. **Introduction to namespace adoption**: can include what it means for a Kargo project to adopt an existing namespace and the benefits of this feature.
  
2. **Prerequisites for using this of Kargo's ability**: 
   - Users must define the namespace before defining the Kargo project. You could do it by defining them in the same YAML file with the namespace above the Project.
   - The namespace must include the label `kargo.akuity.io/project: "true"`.

3. **Use Cases**: Highlight scenarios where this feature is particularly beneficial, such as compliance with the External Secrets Operator (ESO) security practices.

**Comment by krancour** [comment]
@fykaa let's have this be a new page under "How-to Guides" called "Managing Projects." There will be other things to discuss apart from this. Some small bit of introductory info from the Overview page can either be copied over or linked to.

Longer term, this new page will move under "User Reference" when we split docs into separate reference guides for  users, operators, and contributors.
