### ISSUE TITLE
Allow signing commits using a GitHub Application

### ISSUE THREAD

**Issue by CCOLLOT** [akuity/kargo#2627]
### **Problem statement:**
When using a Github Application to write changes to git, commits are not signed.

Error message: 
```
remote: error: GH006: Protected branch update failed for refs/heads/main. remote: remote: - Commits must have verified signature
```

According to the documentation: 
```
Signature verification for bots will only work if the request is verified and authenticated as the GitHub App or bot and contains no custom author information, custom committer information, and no custom signature information, such as Commits API.
```

I tried setting `.Values.controller.gitClient.name` and `.Values.controller.gitClient.email` to `""` but it did not solve the issue.

After [looking at the code](https://github.com/akuity/kargo/blob/c10f4dc982f37094649656163b10804b452f7dcc/internal/controller/git/base_repo.go#L85), it seems that if those values are empty then Kargo will use default values.
I wonder if removing those default values would solve the issue

**Comment by krancour** [comment]
> no custom author information, custom committer information, and no custom signature information

I am perplexed by this, because unless I am very much mistaken a git commit _requires_ a name and email address.

@hiddeco any insight?

> I wonder if removing those default values would solve the issue

If author information is required, as I believe it might be, I'm not sure it would be sensible _not_ to have any default author information.

**Comment by hiddeco** [comment]
From what I have gathered, signing commits using a GitHub Application is only possible using [the GitHub API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#create-or-update-file-contents). As we make use of `git` to perform Git operations, this will not work even if we set the author name and email address to an empty string, as Git _requires_ these values to be present:

```console
$ cd $(mktemp -d)
$ git init
Initialized empty Git repository in /private/var/folders/wn/6bc13g_526zdvzvkhnl4fnpr0000gn/T/tmp.pQblIJ9x0I/.git/

$ git config user.name ""
$ git config user.email ""
$ touch README.md
$ git add .
$ git commit -m "This will fail"
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <>) not allowed
```
