### ISSUE TITLE
Ability to terminate a Running Promotion

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2662]
# Proposed Feature

When hitting https://github.com/akuity/kargo/issues/2661, it became apparent that we need the ability to terminate promotions since they might be long-lived, or bugs might cause them to get stuck running.

# Motivation

I no longer want a Promotion to run.

# Suggested Implementation

Introduce a `terminate` field in a Promotion, that would be set by API server by a user interaction:

```
spec:
  terminate: {}
```

Note that terminate is a struct instead of a boolean, because we might want different termination options, e.g. gracefully close PRs that were opened (SIGTERM), or do nothing like a `kill -9` (SIGKILL).

**Comment by hiddeco** [comment]
I am unsure if this should be declared in-spec, or be more like the [current abort annotation](https://github.com/akuity/kargo/blob/8d4e58e21e15f0a65a6dad5b3dac089b2285559f/api/v1alpha1/annotations.go#L23-L27) we have for the verification process of a Stage.

**Comment by krancour** [comment]
Verifications aren't themselves a CR, so an annotation on a Stage to kill a verification feels like it makes sense.

If we did go an annotation-based route here, couldn't we apply that annotation directly to the Promotion instead of on the Stage?

**Comment by hiddeco** [comment]
> If we did go an annotation-based route here, couldn't we apply that annotation directly to the Promotion instead of on the Stage?

Yes, that's actually what I was suggesting.

**Comment by hiddeco** [comment]
This is now possible using `kubectl`, `kargo` and the API thanks to #2479. The bit that's missing is the integration into the UI.
