### ISSUE TITLE
Add the option to set /.config/kargo, /etc/xdg/kargo location when login.

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#2663]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate feature request.
* [X] I've pasted the output of `kargo version`, if applicable.
Client Version: v0.8.8
Server Version: v0.8.8

# Proposed Feature

when login to the kargo API via the CLI it saves the file it needs in the user's home dir.
when running in non-privileged containers the user running the container is randomly selected and a path with specific permission needs to be set.

# Motivation

currently, this makes the cli not so useful in non-privileged pods 

# Suggested Implementation

add a flag in the cli command to specify where to save those files i.e.
--config-path <path/to/config> --xdg-path <path/to/xdg>

**Comment by krancour** [comment]
Why wouldn't you just set `XDG_CONFIG_HOME` appropriately?
