### ISSUE TITLE
kustomize-build step should support enable-helm option

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2707]
# Proposed Feature

With Kargo v0.9's `kustomize-build` step, we lost the v0.8 kustomize feature to support `--enable-helm`.

# Motivation

Many people deploy helm charts using kustomize's helm chart inflator feature.

# Suggested Implementation

Add enableHelm option to the kustomize-build step

NOTE: there may be other kustomize build options we need to support. But we should add them on a case-by-case basis, given there are security implications (e.g. `--load-restrictor=LoadRestrictionsNone`)

**Comment by krancour** [comment]
Didn't we do Kustomize and Helm options generically for Kargo Render? Doesn't Argo CD do it generically? i.e. Pass the options you want? Is that something we could get away with here?

**Comment by krancour** [comment]
To clarify... I support this. It is the "But we should add them on a case-by-case basis" part that I want to unpack.

**Comment by hiddeco** [comment]
> Doesn't Argo CD do it generically? i.e. Pass the options you want?

ArgoCD allows to some extent for the administrator to enable options, but not the user.

Putting the user in control over everything poses a security risk, as certain options allow you to escape from your sandbox as a tenant.

In addition, just blindly running `helm` (by Kustomize) causes there to be a shared cache as a by-effect. Which has implications on its own.

**Comment by hiddeco** [comment]
> Doesn't Argo CD do it generically? i.e. Pass the options you want?

ArgoCD allows to some extent for the administrator to enable options, but not the user.

Putting the user in control over everything poses a security risk, as certain options allow you to escape from your sandbox as a tenant.

In addition, just blindly running `helm` (by Kustomize) causes there to be a shared cache as a by-effect. Which has implications on its own.

**Comment by krancour** [comment]
Ah. You're right... I was misremembering the following as an Application field.

https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#kustomize-build-optionsparameters

**Comment by jessesuen** [comment]
> In addition, just blindly running helm (by Kustomize) causes there to be a shared cache as a by-effect. Which has implications on its own.

I didn't consider this. We may be able to solve this by setting helm env vars like HELM_HOME

**Comment by krancour** [comment]
@jessesuen I'm wondering if I jumped the gun assigning this to v1.0.0. Do you feel strongly that it is needed by then? This looks to be something that will take time to get right and it's not a capability we _lost_ in the v0.9.0 pivot. Would you be ok if this were bumped to the v1.1.0 milestone?

**Comment by krancour** [comment]
Actually @hiddeco corrected me that Kargo Render could do this and steps were meant to obviate the need for Kargo Render, so I guess this is a slight loss of capability.

**Comment by jessesuen** [comment]
Another note: I do understand that supporting `enable-helm` adds *back* the `helm` binary, which we just removed to improve the security posture of kargo. If we are insistent on avoiding bundling `helm` CLI, what we could do is invoke `kustomize build` with `--helm-command XXXX` flag, where XXXX would be our own binary, that is a small subset of `helm` CLI (just the `template`).

Or the `helm` binary could even just be a hard link to the kargo server binary that changes functionality based on what `args[0]` is (what busybox does). So it wouldn't even increase the image size.

**Comment by jessesuen** [comment]
> Do you feel strongly that it is needed by then?

Given that this was a loss of functionality and would blocking users from upgrading, I do think we should add this back. Even so far as backporting to v0.9 since v0.9 will be the *only* release they could use to transition to promotion mechanisms.

> This looks to be something that will take time to get right

I believe there is a quick fix, which would be to:
1. add back helm binary
2. Construct `krusty.MakeKustomizer` with helm option

**Comment by jessesuen** [comment]
> In addition, just blindly running helm (by Kustomize) causes there to be a shared cache as a by-effect. Which has implications on its own.

I think we are actually safe here. If you look at helm chart inflator implementation, they use temporary directories by default (i.e. when `HELM_CONFIG_HOME` is left unspecified):

https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/helmchartargs.go#L25-L34

```golang
	// ConfigHome defines a value that kustomize should pass to helm via
	// the HELM_CONFIG_HOME environment variable.  kustomize doesn't attempt
	// to read or write this directory.
	// If omitted, {tmpDir}/helm is used, where {tmpDir} is some temporary
	// directory created by kustomize for the benefit of helm.
	// Likewise, kustomize sets
	//   HELM_CACHE_HOME={ConfigHome}/.cache
	//   HELM_DATA_HOME={ConfigHome}/.data
	// for the helm subprocess.
	ConfigHome string `json:"configHome,omitempty" yaml:"configHome,omitempty"`
```
