### ISSUE TITLE
bug(ui): stage-attached promotion button does not allow selecting freights from all directly sourced warehouses

### ISSUE THREAD

**Issue by CCOLLOT** [akuity/kargo#2715]
I have:
- 2 warehouses, `A` and `B`
- 2 stages, `dev` and `prod`

- `dev` directly subscribes to `artifacts` from `A` and `B`
- `prod` subscribes to `artifacts` from `A` and `B` with `dev` as the source.

The UI displays warehouse `A`, in the same color as dev (red) and warehouse `B` in the same color as prod (blue).

When clicking on the "target-shaped" (🎯) promotion button on a stage's tile, the upper carrousel only offers to promote freights from warehouse `A`. It means I have to go back and do it the other way around and first select warehouse `B`, then find the freight, then click promote via the triple-dot menu before finally clicking on the "promote" button on the stage's tile

In this setup, I would expect:
- The promote (target-shaped) button of the `dev` stage to let me choose freights from any warehouse declared as a direct requestedFreight source.
- The UI to render the two warehouses with different colors (ex: yellow and green for warehouses, red and blue for environments), as I don't see why warehouses `A` and `B` would be respectively linked to `dev` and `prod`

**Comment by krancour** [comment]
I am having some trouble understanding... is this two separate issues? A screenshot or short recording would probably help a lot here.

**Comment by CCOLLOT** [comment]
The main issue is the "target" promote button does not let me pick freights from any directly sourced-warehouse.
The second issue (which may be related or not), is that, based on the color scheme, warehouse A seems linked to dev and warehouse B to prod) which can be either just confusing or the cause of the error itself.


![image](https://github.com/user-attachments/assets/e143df8e-15b7-4181-9ad2-1724d4ac2eb0)

could it be because warehouse A has subscriptions to images and warehouse B only has subscriptions to helm charts?

**Comment by Marvin9** [comment]
@CCOLLOT when you click on target, you have an option to select to which warehouse freights to show in timeline in order to promote. It can be achieved by click on the filter icon, left side of "Refresh" button in warehouses. 

To summarise, the UX can be improved by

1. Highlighting the warehouse selector for promotion to stages
2. Avoid overlaps of colour in warehouse and stages

**Comment by krancour** [comment]
As far as the colors are concerned, it's a persistent problem we haven't quite solved. There is a limited number of colors in the palette we're working with and colors are too often re-used. I can confidently assure you, however, that the colors are neither the root of your problem nor are they a reflection of some misoncfiguration on your part that is causing this.

@Marvin9 has mentioned the ability to filter the Freight timeline by Warehouse. I do notice that the little filter icon in your Warehouse "A" appears to be active. It seems to me that must be part of the issue, although in my attempts to reproduce this, I've seen any active filter automatically disabled when I begin the Promotion process. So I'm a little perplexed at how this is happening to you.

**Comment by CCOLLOT** [comment]
You are right, my bad! I had not seen the filter button. Thank you 🙏

**Comment by krancour** [comment]
Although I'm not clear on how you were able to have a filter applied to the Freight timeline during Promotion when I was unable to, I think this is safe to close now, but please do feel free to re-open if you feel otherwise.
