### ISSUE TITLE
Docs link should update to https://docs.kargo.io/

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2751]
# Description

The docs link in UI should be updated to https://docs.kargo.io/, which is already active and will be our permanent location

<img width="85" alt="image" src="https://github.com/user-attachments/assets/5d0dc5bc-24f3-49ff-ab95-a9eb1a83ed7b">

(currently it points to `kargo.akuity.io`, but that will eventually be a redirect to kargo.io, not docs).

# Version

```
v0.9
v1.0
```

**Comment by krancour** [comment]
Oh... and now that I check, already up to date in v0.9.1 as well.
