### ISSUE TITLE
Improve experience of working with freight containing many artifacts

### ISSUE THREAD

**Issue by Brightside56** [akuity/kargo#2756]
# Checklist

* [ ] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

Improve dev. experience of working with pipelines where freight may contain many artifacts (5+)

# Motivation

Some of applications I have - are legacy services, distributed monoliths, containing large number of different applications, but those applications have a common SDLC and in terms of promotion they're single unit of work, as @krancour says. They need to be promoted across different stages of pipeline at same time therefore they cannot be simply disassembled into separate pipelines or warehouses at the moment

# Suggested Implementation

- optimize the UI for working with a bigger number of artifacts
- it may be impossible to work with freight creation/freight containing big number of artifacts using auto-discovery, but work using "assemble freight" seems to be viable. However, when user needs to assemble a new freight where only one image from 10 changes - this requires selecting 10 artifacts each time. Probably it could make sense to create UI option/button for a freight - "create new freight like this", which redirects to new "assemble freight" page, which already contains all artifacts of source freight selected and user can select for a new freight just 1-2 artifacts he/she needs to change

**Comment by krancour** [comment]
This is an interesting idea. Need a small bit of clarification. You mentioned "auto-discovery" not working well for this scenario. Did you mean to say you just don't want Freight minted automatically by the Warehouse? Discovery still has to happen for Freight assembly. It's how the artifacts to choose from are found.

**Comment by Brightside56** [comment]
> Did you mean to say you just don't want Freight minted automatically by the Warehouse?

This. Auto-discovery is working, but often it may be not desired in cases when warehouse will produce insane number of freights and those freights will bloat freightline

My intent is to rely on existing freight (currently deployed on some stage) as a source of truth

**Comment by krancour** [comment]
Yes... I could see how that would be useful. When I sell things on eBay, I actually look first for someone else selling the same thing and click "I have one of these to sell." It clones their listing and I modify accordingly. It's much faster/easier than starting from scratch. You basically want the equivalent of that. 👍

**Comment by krancour** [comment]
Closed in favor of #2988
