### ISSUE TITLE
Admin Role cannot abort promotions

### ISSUE THREAD

**Issue by shmargum** [akuity/kargo#2790]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

The admin role cannot currently terminate promotions.
We can see that it does not have a role for `update` or `patch` here: https://github.com/akuity/kargo/blob/main/charts/kargo/templates/users/cluster-roles.yaml#L48

While we could perhaps just add a verb here, the comment about immutability makes me think that instead of an annotation, promotion termination could perhaps be done via status instead so that the `promotions/status` resource can be targeted distinctly from the promotion resource itself.

# Version

```
v1.0.0
```

**Comment by krancour** [comment]
It is really Stage and Freight references that are immutable. You cannot change what a Promotion is promoting or where it is being promoted to after-the-fact. Annotations are ok. We should just add patch.
