### ISSUE TITLE
docs: previous/next links at bottom of documents have unresolved characters

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2870]
![Screenshot 2024-10-29 at 10 13 46 AM](https://github.com/user-attachments/assets/f43633b7-cce9-4bb7-be85-354f516a4eea)

This is obviously wrong.

For comparison, here is docs.akuity.io:

![Screenshot 2024-10-29 at 10 15 59 AM](https://github.com/user-attachments/assets/935b85dd-e02f-4fdb-b5de-286d149ef91d)

You should be able to compare the two sites to determine how this might be fixed.

**Comment by krancour** [comment]
Indeed, it does appear correct locally, but it does not on the live docs site.

**Comment by krancour** [comment]
Re-opening.

Inexplicably, the preview build of #2871 at https://deploy-preview-2871.docs.kargo.io/ showed the problem resolved, but the problem is not resolved in production or edge docs (published from main), nor is resolved in more recent preview builds.

Logs confirm that the desired version of Node is being used.

**Comment by Marvin9** [comment]
sounds like cache issue - https://answers.netlify.com/t/cache-issue-on-netlify/8238

**Comment by krancour** [comment]
@Marvin9 I will check that. Thanks!

I had cleared it once before while we were troubleshooting this, but probably not since we actually solved it.
