### ISSUE TITLE
allow for ingress controller (not individual ingress resources) that terminates ssl

### ISSUE THREAD

**Issue by hghtwr** [akuity/kargo#2920]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

We are running nginx ingress controller that terminates TLS. Within the cluster we don't use TLS. I want to connect with MS AzureAD using Dex. 

To expose Kargo on the ingress controller, I've set the following settings in `values.yaml`

```
api.tls.enabled: false
api.ingress.enabled: true
api.ingress.tls: false
api.oidc.enabled: true
api.oidc.dex.enabled: true
api.oidc.dex.connectors: [<MS AzureAD connector settings]
```
### Mixed Content
On the login screen, Kargo tries to load insecure resources `http:<host>/dex/.well-known/openid-configuration` which is blocked and results in an error message

To fix this, I edited the configmap `kargo-api` to update the issuer to https prefix.
https://github.com/akuity/kargo/blob/c0d47e05abc053505a9e4a53467d31a271212e05/charts/kargo/templates/api/configmap.yaml#L47

### Issuer Mismatch
After fixing this, it shows `response body issues does not match expectedIssues` which needs the same fix in the dex-server secret
https://github.com/akuity/kargo/blob/c0d47e05abc053505a9e4a53467d31a271212e05/charts/kargo/templates/dex-server/secret.yaml#L16

# Screenshots
![image](https://github.com/user-attachments/assets/877998e5-0e53-4bea-87cd-d4aa6cadbe25)
![image](https://github.com/user-attachments/assets/ac7dc788-d06f-4fd6-94eb-54a4266adb20)

# Steps to Reproduce

1. Use nginx ingress controller to expose Kargo.
2. Make sure TLS is terminated on Nginx ingress
3. Use the above mentioned tls settings in the helm chart
4. Use AzureAD connector with Dex

# Version

```
/ $ kargo version
{
  "Version": "v1.0.3",
  "BuildDate": "2024-10-23T07:31:54Z",
  "GitCommit": "bb7afaad9750dfff61f47dd6c5288acbcdb6bce2",
  "GitTreeDirty": false,
  "GoVersion": "go1.23.2",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

**Comment by krancour** [comment]
> `api.ingress.tls: false`

> We are running nginx ingress controller that terminates TLS.

These statements seem at odds... unless...

Does your ingress controller have just one wildcard cert and it's terminating TLS _before_ routing?

**Comment by hghtwr** [comment]
Correct. It's using a wildcard cert and nginx ingress is holding this wildcard certificate. 
In-cluster encryption is handled differently that's why we terminate it at ingress level.

**Comment by tsmalls93** [comment]
I am running into the same issue. My configuration is a little different though and I'm sure it is atypical as well. I have an A10 load balancer with a wildcard cert that terminates the SSL and connects to a single node port on my cluster. I would expect manually setting the issuer URL in the dex config to override the automatic configuration, but I see the helm chart doesn't use that value.
