### ISSUE TITLE
Credentials secret with regex incompatible with container registry on custom port

### ISSUE THREAD

**Issue by Gio-R** [akuity/kargo#2928]
# Description
I created a Warehouse pointing to an image on a private registry, exposed on a custom port. The image url was `my.registry.url:10000/path/to/image`. I created a generic credentials Secret with `repoURLIsRegex: "true"` and `repoURL: "my.registry.url:10000/.*"`, expecting Kargo to associate the credentials to the image, but it was not so.

I temporarily solved the problem by changing the regex to "my.registry.url.10000/.*", as I suspect that the normalizations done [here](https://github.com/akuity/kargo/blob/aa66473ce09aba024d2d6088fd77176cf05f6526/internal/credentials/kubernetes/database.go#L165) change the examined image url to `my.registry.url/10000/path/to/image`, causing the original regex to not match.

# Steps to Reproduce

0. Set Kargo log level to debug
1. Create, in a Kargo Project, a Warehouse with a subscription to an image with url `my.registry.url:10000/path/to/image`
2. Create a credentials Secret for such Warehouse with `repoURLIsRegex: "true"` and `repoURL: "my.registry.url:10000/.*"`
3. See how Kargo logs "found no credentials for image repo" when refreshing the Warehouse
4. Change the repo url in the Secret to `repoURL: "my.registry.url.10000/.*"`
5. See how Kargo correctly refreshes the Warehouse

# Version

Kargo v1.0.3

**Comment by krancour** [comment]
@Gio-R the regex was a red herring, but your intuition about the normalizations being involved in the problem was spot on.
