### ISSUE TITLE
undesired behavior from promotion step retries

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#3052]
We may have missed the mark on promotion step retries. I am seeing infinite retries of a `wait-for-pr` step where the PR was merged without being closed, which is a failure condition. This step _does_ default to an infinite number of attempts, but no amount of retries will resolve this failure.

Note: We do _not_ need to go down the rabbit hole of distinguishing between technical errors and logical failures. We also do not need to distinguish between recoverable and unrecoverable errors. Although these are things we will get around to, I believe there is a more fundamental problem with our current implementation of retries.

There are two different scenarios retries need to address:

1. You want to retry when an unanticipated error occurs.

2. You want to _cap_ the retries when no error has occurred, but you've been waiting a long time for something that might never happen, such as waiting for a PR to be merged.

We got no.1 right. If an error/failure occurs and max attempts isn't exhausted, we downgrade the error/failure to "running." The promotion will be requeued and the step will be re-attempted on the Promotion's next reconciliation attempt. The system-wide default used by most built-in steps is one attempt -- no retries.

No.2 is where we seem to have two separate problems:

* The logic that checks if max attempts have been exhausted is only ever triggered by a step that returned an error/failure. i.e. Even with a finite cap on attempts, retries are _effectively_ infinite unless an error occurs.

* Steps that wait for something to happen, such as waiting for a PR to be merged, default to infinite attempts. This makes sense. It can take a long time for a PR to be merged. But the logic that worked so well for case no.1 will downgrade an infinite number of errors/failures to "running," as if the step is just waiting. In fact, even _without_ infinite attempts, any number of attempts greater than one could result in undesired retries after an unrecoverable error/failure.

I can't really spot a way to logic ourselves out of this without adding additional options. I believe the solution may be to define the max number of _total_ attempts and, separately, an error/failure threshold. A good default for _all_ existing steps would be infinite total attempts (as long as the step says its still running/working/waiting) with immediate failure after a single error/failure.

Related: I think a configurable timeout would make sense as well. It could default to no limit for all existing steps, but users could indicate, for instance, that a `wait-for-pr` step fails if the PR isn't merged within 48h. This is a nice-to-have that could be handled in a follow-up.

I'm happy to do the legwork on this issue if my analysis seems accurate and the approach seems sensible to @jessesuen and @hiddeco.

**Comment by hiddeco** [comment]
> I can't really spot a way to logic ourselves out of this without adding additional options. I believe the solution may be to define the max number of total attempts and, separately, an error/failure threshold. A good default for all existing steps would be infinite total attempts (as long as the step says its still running/working/waiting) with immediate failure after a single error/failure.

In my opinion, defining the number of total attempts does yield minimal value in the case of (non-erroneous) polling, as the interval at which the polling occurs may not be visible to the user (or hidden) and it would thus be hard to determine what a good number of attempts looks like. In most (if not all) cases, I think users would simply like to set a duration.

> I am seeing infinite retries of a `wait-for-pr` step where the PR was merged without being closed, which is a failure condition. This step does default to an infinite number of attempts, but no amount of retries will resolve this failure.

I also think there is no proper way to solve this _other_ than having some elevated error that marks the step as "terminal", causing the engine to stop making further attempts straight away. I also think this one may be the easiest to solve, as we can temporarily add an internal error type for these types of errors within the "polling" steps (`git-wait-for-pr` and `argocd-update`), and expand on this later.

**Comment by krancour** [comment]
> In my opinion, defining the number of total attempts does yield minimal value in the case of (non-erroneous) polling, as the interval at which the polling occurs may not be visible to the user (or hidden) and it would thus be hard to determine what a good number of attempts looks like. In most (if not all) cases, I think users would simply like to set a duration.

I agree with this, and it was actually the impetus for this suggestion:

> Related: I think a configurable timeout would make sense as well. It could default to no limit for all existing steps, but users could indicate, for instance, that a wait-for-pr step fails if the PR isn't merged within 48h. This is a nice-to-have that could be handled in a follow-up.

The reason I didn't jump straight to this is one we've previously discussed in other contexts. There's no native duration type in JSON, so we'd be forced to use a string representation of a duration and that had _seemed_ like a difficult thing to validate using JSON schema.

Upon further research, it's not at all as bad as I thought, mostly because there are no complex rules in go duration parsing that make something unconventional like `2m10h` invalid. It's valid and directly equivalent to `10h2m`. `10h10h` is the same as `20h`. With this realization, the regex `(?:\d+(?:ns|us|µs|ms|s|m|h))+` suffices.

So we are now aligned on this. 👍 

> I also think there is no proper way to solve this other than having some elevated error that marks the step as "terminal", causing the engine to stop making further attempts straight away. I also think this one may be the easiest to solve, as we can temporarily add an internal error type for these types of errors within the "polling" steps (git-wait-for-pr and argocd-update), and expand on this later.

I'm not sure any of that is necessary if we just allow a failure threshold to be defined. Think of it just like a liveness or readiness probe failure threshold -- the number of _consecutive_ failures before we give up.

When a step like `argocd-update` or `wait-for-pr` is still waiting for some conditions to be met, it doesn't present that as an error/failure. It presents it as "running," which will make it subject to the clock instead of the failure threshold.

**Comment by krancour** [comment]
> My suggestion for this was more related to the scenario where a PR was closed instead of merged, in which cause I think continuing to poll might be strange.

Ah. I see.

But with a failure threshold of one, it would not continue.

**Comment by hiddeco** [comment]
No, but that would also mean it wouldn't continue for _other_ (more recoverable) errors?

**Comment by krancour** [comment]
Correct, but we're not yet distinguishing between recoverable and unrecoverable errors.

Were we, now or later, to start doing that, we'd simply fail on all unrecoverable errors and the remaining ones would be subject to the threshold.

**Comment by krancour** [comment]
So for now, I'd default the failure threshold to 1 across the board.
