### ISSUE TITLE
GitHub Apps Credentials - error decoding private key, cannot figure out correct format

### ISSUE THREAD

**Issue by jeffmccune** [akuity/kargo#3055]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Following [GitHub App Authentication](https://docs.kargo.io/how-to-guides/managing-credentials/#github-app-authentication) docs, I can't convince Kargo to accept the credentials.

# Screenshots

<img width="821" alt="Screenshot 2024-12-04 at 12 46 21 PM" src="https://github.com/user-attachments/assets/f4c8b99e-46ca-4956-9420-bc3d9ee1cc8d">

# Steps to Reproduce

1. Create and install a GitHub App as described at [GitHub App Authentication](https://docs.kargo.io/how-to-guides/managing-credentials/#github-app-authentication)
2. Follow the [Kargo Quickstart](https://docs.kargo.io/quickstart/#your-first-kargo-project) to configure the Project, Warehouse, and Stages
3. Create a secret as described in the GitHub App Authentication doc.

Take care to ensure the string values don't have trailing newlines and the base64 pem encoded key is the value:

```bash
kubectl get secret -n kargo-demo github-app-creds -o json \
  | jq --exit-status '.data | map_values(@base64d)'
```

```json
{
  "githubAppID": "1099999",
  "githubAppInstallationID": "57999999",
  "githubAppPrivateKey": "-----BEGIN RSA PRIVATE KEY-----\nMIIE\nREDACTED\n-----END RSA PRIVATE KEY-----",
  "repoURL": "https://github.com/jeffmccune/bank-of-holos.git"
}
```

# Version

```
v1.0.3
```

# Logs

```
failed to run step "git-clone": error getting credentials for https://github.com/jeffmccune/bank-of-holos.git: error getting installation access token: error decoding private key: illegal base64 data at input byte 0
```

**Comment by hiddeco** [comment]
I suspect your private key is not base64 encoded as a literal Secret value (i.e. encoded twice).

**Comment by jeffmccune** [comment]
@hiddeco Do you mean the pem file GitHub provides needs to be base64 encoded a second time?  PEM encoding is Base64 encoding so I figured the Kargo documentation was saying to take care to provide the pem contents.

If Kargo requires double base 64 encoding for some reason, it might be worth an update the docs to clarify.

I just tried to double encode it and appear to have gotten a bit further along.

**Comment by jeffmccune** [comment]
It's also especially confusing because k8s also base64 encodes the `stringData` field, so this field end up being base64 encoded 3 times...

**Comment by jeffmccune** [comment]
Solution: wrap the pem file GitHub provides in a second layer of base64 encoding and provide to the `stringData` field so k8s wraps the data in a _third_ layer of base64 encoding.

**Comment by hiddeco** [comment]
> It's also especially confusing because k8s also base64 encodes the stringData field, so this field end up being base64 encoded 3 times...

I agree, and we could not really tell why we made this a requirement. I raised #3059 to make this easier in the future.

**Comment by krancour** [comment]
Reopening this for visibility until #3059 closes it.

**Comment by Utwo** [comment]
I can still reproduce this one on 1.2.0.

**Comment by krancour** [comment]
@Utwo thanks for reporting. I've spotted the bug. Fix incoming.

**Comment by Utwo** [comment]
> @Utwo thanks for reporting. I've spotted the bug. Fix incoming.

That was fast, thank you very much!
