### ISSUE TITLE
broken link for "Manually Trigger a Deployment"

### ISSUE THREAD

**Issue by fykaa** [akuity/kargo#3064]
The "[Manually Trigger a Deployment](https://app.netlify.com/sites/docs-kargo-akuity-io/deploys)" netlify link on the [Release Procedures](https://docs.kargo.io/contributor-guide/release-procedures) page is broken and redirects to a "Page Not Found" error.

**Comment by krancour** [comment]
Nice catch. When we moved to the docs.kargo.io domain about a month or two ago, we actually created a new site and the old one has since been deleted.

The correct link should be: https://app.netlify.com/sites/docs-kargo-io/deploys
