### ISSUE TITLE
setting up predefined variable for username who who did the promotion

### ISSUE THREAD

**Issue by creeram** [akuity/kargo#3194]
# Proposed Feature

Currently, I see only the `project`, `stage`, and `promotion` predefined variables, which provide convenient access to the details of a Promotion. which can be referenced using `ctx.projec`,`ctx.stage`,`ctx.promotion`.

I am looking for a variable like `ctx.username` or `ctx.triggeredby` or `ctx.promotedby`.

# Motivation

I'm using HTTP post message to post information of the promotion to a slack channel and i want to include the detail of that person who did the promotion.

**Comment by Sebast1aan** [comment]
Looks to be the same use case as in #3081

**Comment by krancour** [comment]
@Sebast1aan yep. Closing as a duplicate.
