### ISSUE TITLE
Backend protocol ingress with helm

### ISSUE THREAD

**Issue by valkiriaaquatica** [akuity/kargo#3198]
# Checklist

* [ X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X ] I've included steps to reproduce the bug.
* [ X] I've pasted the output of `kargo version`.
* [X ] I've pasted logs, if applicable.

# Description
First thanks for this awesome work!
Second, using the helm installation as described here: https://docs.kargo.io/how-to-guides/installing-kargo/   if  you deployed it using nginx and tls enabled (as shown in the steps)  and try to access through the domain https://kargo.example.com/  the web service returns 400 error and no web servcie is loaded.
To solve this problem I've added nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  to the annotations, and problem resolved.  The error comes i think from the kargo-api service that just accets HTTPS connections, so that annotation as a walkaround.

# Screenshots

No necessary, with logs is enough

# Steps to Reproduce

1. Execute the above
```
helm install kargo \
  oci://ghcr.io/akuity/kargo-charts/kargo \
  --namespace kargo \
  --create-namespace \
  --set api.ingress.enabled=true \
  --set api.ingress.ingressClassName=nginx \
  --set api.host=kargo.example.com \
  --set api.adminAccount.passwordHash='$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm' \
  --set api.adminAccount.tokenSigningKey=iwishtowashmyirishwristwatch \
  --wait
```
2. Try to access https://kargo.example.com  
3. A 400 error wil be returned in the nginx svc and in the web explorer 

----------
To solve this error (withoud modifyng service or pod):
1. Execute the above
```
helm install kargo \
  oci://ghcr.io/akuity/kargo-charts/kargo \
  --namespace kargo \
  --create-namespace \
  --set api.ingress.enabled=true \
  --set api.ingress.ingressClassName=nginx \
  --set 'api.ingress.annotations.nginx\.ingress\.kubernetes\.io/backend-protocol=HTTPS' \
  --set api.host=kargo.example.com \
  --set api.adminAccount.passwordHash='$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm' \
  --set api.adminAccount.tokenSigningKey=iwishtowashmyirishwristwatch \
  --wait

```
# Version

```
appVersion: v1.1.2
version: 1.1.2
```

# Logs
nginx-ingress svc logs:
```
 ingress-nginx-controller-6d8d79d8d5-h8jtd 2024/12/30 00:02:39 [error] 1761#1761: *56857 recv() failed (104: Connection reset by pe │
│ er) while reading upstream, client: 127.0.0.1, server: kargo.example.com, request: "GET / HTTP/2.0", upstream: "http://10.42.0.43: │
│ 8080/", host: "kargo.example.com" 
```
kargo-api svc logs
```
 kargo-api-79c97b8d6d-ff6rz 2024/12/30 00:02:39 http: TLS handshake error from 10.42.0.24:44688: client sent an HTTP request to an HTTPS server
```

If you want me to open a pr to add that info as a comment on the values.yaml or another similar solution... 
Thanks!

**Comment by krancour** [comment]
`kubernetes.io/ingress.class: nginx` is mentioned as an example value for the `api.ingress.annotations` field. I'm not really of the opinion that our chart needs to document configuration for specific ingress controllers at the level of detail you're proposing.

Docs on `api.ingress.enabled` mention ingress being "advanced" configuration -- which was our succinct way of saying, "If you're going to do this, please know what you're doing because we're not holding your hand."

I'm not sure there is anything actionable here. It certainly isn't a bug.
