### ISSUE TITLE
StageSet

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#339]
Future idea - not a fully thought out idea but adding a place holder issue to collect use cases.

We may need to consider a higher level object to an Stage into a higher-order CRD, which I'll call StageSet.

## Why would this be useful?

The main use case would be to automatically generate environments and generate relationships between these environments. 

Another would be to logically group multiple existing environments into a higher level object, for which actions could be performed (e.g. Promotions across a set of environments)

**Comment by krancour** [comment]
Not stale. Want to keep this around.

**Comment by krancour** [comment]
Not stale

**Comment by krancour** [comment]
I'm going to close this in favor of #2827.

Although something like a hypothetical StageSet, would make it easier to define things that should be _common_ among several similar Stages, the _new_ difficulty, both in terms of implementation and UX, would be handling the elements of similar Stages that are _different_ -- such as what Warehouses or upstream Stages they request Freight from.

With 1.1's introduction of expression language support within promotion steps, well-written, user-defined promotion processes can become _more similar_ (even identical) from Stage to Stage.

#2827 proposes `PromotionTemplate` as a top-level resource that defines promotion processes, parameterized through EL, and re-usable by reference. This would DRY up similar Stages quite nicely, leaving each to focus only on the elements that _differ_ from one Stage to the next. 

This seems, overall, a cleaner approach than the notion of a StageSet.
