### ISSUE TITLE
Using Connect for API server

### ISSUE THREAD

**Issue by devholic** [akuity/kargo#352]
I think we may use [Connect](https://connect.build/) instead of [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) or raw gRPC server. By using Connect, we don't have to generate client code with OpenAPI schema and we can serve both gRPC and HTTP in a single server.

WDYT? @krancour @rbreeze @rpelczar

**Comment by rpelczar** [comment]
From the frontend perspective, this is a very good idea. I like the Web integration, especially with react-query.
@rbreeze, that's what I wanted to have.

**Comment by krancour** [comment]
As discussed earlier today, I'm on board with anything that's easy and meets the needs of web clients.
