### ISSUE TITLE
generic yaml promotion mechanism

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#424]
We have built-in support for `kargo edit set image` and for updating Helm `Chart.yaml` and `values.yaml` files.

If I am not mistaken, Argo CD, through plugins/extension, can support additional configuration management tools.

We should introduce a more generic YAML-based promotion mechanism. This could conceivable replace the Helm promotion mechanisms (or we could leave those be), but more importantly, it would open the door to compatibility with a wider range of config management tools -- like ytt, for example.

**Comment by krancour** [comment]
@akselleirv, I think this is a separate concern from a generic YAML-based promotion mechanism largely because dealing with YAML is easy and the capability mostly already exists within Kargo and we just need to expose it.

What you're requesting is something even _more_ generic than what is described in this issue.

I'm re-opening your issue #527 because I think that's the right place for this particular conversation to continue.

**Comment by krancour** [comment]
Not stale, but not a high priority.

**Comment by jmgilman** [comment]
Is the goal here to replicate the Custom Management Plugin interface of Argo? It seems that would unlock the most value considering there are dozens of them out there.

**Comment by krancour** [comment]
Closing due to similarity with #1250
