### ISSUE TITLE
repoURL in Environments

### ISSUE THREAD

**Issue by vfarcic** [akuity/kargo#451]
What should be a value used in `Environment` `.spec.subscriptions.repos.images[].repoURL`? The examples in the docs use `nginx` so I thought that it should be any valid container image but when I put something like `c8n.io/vfarcic/kargo-demo` it fails to pass the CRD regex for that field which does not allow `-` or  `/`.

**Comment by krancour** [comment]
@vfarcic the regex is likely too restrictive. I'll take a look as soon as I'm able, but we'd also welcome a PR if you want to take crack at it.

**Comment by morey-tech** [comment]
The regex validation is here: https://github.com/akuity/kargo/blob/5cf88168aa00bb2678d74a34ef136e4d0d6239b5/api/v1alpha1/stage_types.go#L115
