### ISSUE TITLE
flaky test might be signaling a real issue

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#517]
There is a test named `TestRandStringFromCharset` that is sometimes failing.

This test generates a lot of random strings and asserts that each new random string it generates is unlike any it has generated this far.

Sometimes there's a match.

This could be a flaw in the test's design OR it could be a sign that the strings we generate are actually insufficiently random.

We should look into this.

**Comment by gdsoumya** [comment]
I ran the test and modified it a bit to see which particular `i` values are having the collisions and it seems the `i` = `minLen` = `10` is the one that almost always has the collision while rest of the larger `i` values rarely have any even if I increase `j` to a large value like `60,000` rounds.  I think it comes down to pure probability in this case for (i,"abc") input where i=10 the no. of possible unique values if 3^10 (I think it's right ?) and as `i` increases for eg. to 20 the unique count also increases drastically (3^20) so the chances of collision drops. We should either increase the charset to use the value we use in kargo (`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`) or start `i` from a larger value like 20 or 30.

**Comment by krancour** [comment]
> We should either increase the charset to use the value we use in kargo (abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ)

Unless I am missing something, I think the test is already using that exact charset, so even with a `i == 10`, the probability of duplication should be 1/52^10.

And that's what is making me suspicious that there isn't adequate entropy in these strings.

Did I miss something and the test is using a different charset than I had thought?

**Comment by gdsoumya** [comment]
No it isn't using the default charset it just uses "abc" https://github.com/akuity/kargo/blob/427d50020f17757bb19c257cb3d5c459636aaefb/internal/cli/login/login_test.go#L82

**Comment by gdsoumya** [comment]
I'll update it to use the default charset and it'll probably fix the issue as I didn't see any collisions in my local when usign the full charset.

**Comment by krancour** [comment]
🤦 idk how I missed that.

It was supposed to read `str, err := randStringFromCharset(i, charSet)`

Thanks for finding this!
