### ISSUE TITLE
Support generic GitRepoUpdate mechanism

### ISSUE THREAD

**Issue by akselleirv** [akuity/kargo#527]
I have my configuration file written in CUE which describes which "addons" or helm charts which should be deployed to a cluster. The version of the helm chart is specified within this custom structure.

For example:

```CUE
package clusters

cluster: "p-my-cluster": {
	environment:     "prod"

	addon: {
		"ingress_nginx":  {
			values: "0.1.0": { 
				hello: "world"
			}
		}
	}
}
```

When I want to do a promotion I need to update the version in `cluster."p-my-cluster".addon."ingress_nginx".values`:
```CUE
package clusters

cluster: "p-my-cluster": {
	environment:     "prod"

	addon: {
		"ingress_nginx":  {
			values: "0.2.0": { 
				hello: "world"
			}
		}
	}
}
```

The `GitRepoUpdate` config only supports Kustomize and Helm, however, I want to update this custom structure. 

Suggestions:
1. Use a regex and do a replacement of the match. This can be a bit flaky.
2. Use a plugin system which allows for other custom ways of updating a file stored in Git.

**Comment by akselleirv** [comment]
I just found issue #424. Closing this one

**Comment by krancour** [comment]
Re-opening per [this comment](https://github.com/akuity/kargo/issues/424#issuecomment-1669891473)
