### ISSUE TITLE
command to open ui in default browser

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#549]
Low priority, but it would be very convenient to have a CLI command that opens the UI in the system's default browser if you are already logged in to a server.

**Comment by krancour** [comment]
Keep this open. I'll take it.

**Comment by webstradev** [comment]
Question about this.

Currently we only store the API url in the config. Does this mean we also need to store a separate UI url in the config. Or is there a way to get to the UI from that URL.

**Comment by krancour** [comment]
Great question. They are usually the same. The API server serves the SPA from the `/` endpoint.

It's only _not_ the same when running in Tilt because for development only, we split the front end and back end into two separate services. (That allows front end devs to enjoy the benefits of vite live-reloading modified code.)

**Comment by webstradev** [comment]
> Great question. They are usually the same. The API server serves the SPA from the `/` endpoint.
> 
> It's only _not_ the same when running in Tilt because for development only, we split the front end and back end into two separate services. (That allows front end devs to enjoy the benefits of vite live-reloading modified code.)

Thanks for clearing that up. Does this ticket encompass both production and development or is this goal mainly aimed at production.

**Comment by krancour** [comment]
I think just handling the common case (api server also serves SPA) is good for now.

It is a fairly recent phenomenon that we're splitting those into two services at dev time. There are a few wrinkles still to iron out. I intend to make the API server proxy the separate SPA service when running in this configuration, and then everything will just work.

**Comment by webstradev** [comment]
Sounds good, I'm happy to take a look at this over the weekend and see how for I get.

**Comment by krancour** [comment]
Much appreciated. Thank you so much!

**Comment by krancour** [comment]
Note this issue: https://github.com/akuity/kargo/issues/1163

Due to how chaotic the CLI already is, however you approach this will be fine. i.e. I'm not super opinionated about `kargo dashboard` vs `kargo open dashboard`, etc., etc.

The whole command tree will get reorganized at some point, so as long as the functionality is there, this is a win.

fwiw, https://github.com/bacongobbler/browser is the lib we're already using to pop the browser open during `kargo login ... --sso`. It should work well for this also.
