### ISSUE TITLE
Kargo Project onboarding

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#558]
In Kargo, a project is really just a Namespace under the covers. But along with a Project, we might need to create other standard Kargo things inside that namespace, or do other conveniences. For example:

* Create some common, pre-defined Kargo-specific RBAC, such as an kargo "admin", "viewer", Role/RoleBinding/ServiceAccount.
* Give the `kargo:kargo-api` ServiceAccount permissions necessary access to the namespace, such as impersonating a ServiceAccount in the namespace (for the purposes of SSO)
* Maybe some default PromotionPolicies?
* Others?

This issue is about creating a convenience command or API to do wrap up all the things we want to do in a Kargo Project into a single command/API.

The motivation is to improve the user experience by reducing the amount of repetitious steps during project onboarding

**Comment by jessesuen** [comment]
For project onboarding, Kargo API server might not be the best place to do everything from a security standpoint.

We might need to split this out into a dedicated controller that reconciles Kargo Namespaces, and has the necessary permissions to onboard. This controller could then be more effectively secured (e.g. removing network access)

**Comment by krancour** [comment]
> Give the kargo:kargo-api ServiceAccount permissions necessary access to the namespace, such as impersonating a ServiceAccount in the namespace (for the purposes of SSO)

Just making a note that this particular concern is going away since we've got another way (WIP) for the API server to act on a user's behalf without requiring impersonation.

**Comment by krancour** [comment]
See [this comment](https://github.com/akuity/kargo/issues/894#issuecomment-1868146957) it is possible these two issues may be combined.
