### ISSUE TITLE
Control-Flow Stages

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#622]
In my view, stages will not always correspond to something like an environment that needs to be updated, an Argo CD app, etc.... Consider the following deployment DAG:

```
                    /---> [usw1]---\   /---> [usw2]
[test] -> [staging]-----> [use1]--->[X]----> [use2]
                    \---> [euw1]---/   \---> [euw2]
```

The `[X]` Stage is what I'll call (for lack of a better word) a control-flow stage, which is basically just a stage that I want to use as an interaction point in the UI/API.

My use case is the following:
* The [X] stage is subscribed to three stages
* Once a state makes it past (any or all) of usw1, use1, euw1, I'd like for a way to manually simultaneously promote to usw2, use2, euw2 (using the [PromoteSubscribers feature](https://github.com/akuity/kargo/pull/612))

The way I think this could work is: we could make it possible for the promotion mechanism of this to be simply passthrough of what it is subscribed to, then immediately make that state it available in the history to subscribers. As a future improvement, we could extend this with additional user defined rules, such as requiring that the state appeared in all upstream stages history.

But the main point is not how it works, but to call out the need for a Stage as less as a thing to affect an environment but as a control flow to the overall pipeline.

**Comment by krancour** [comment]
Notes from discussion earlier today:

> Once a state makes it past (any or all) of usw1, use1, euw1

The current focus is on the "any" and not the "all."

I will address this by removing the constraint that every stage must have at least one promotion mechanism specified.
