### ISSUE TITLE
Stage/Freight Health is not always applicable

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#623]
If there's no way/reason to assess health (e.g. no associated Argo CD App), we should simply omit health entirely instead of populating the state with `Unknown`. Another use case when I'm using a Stage [for control-flow purposes](https://github.com/akuity/kargo/issues/622), health doesn't make sense either. Since `Unknown` is generally considered an "bad" state. It would be better not to show anything at all when it is not applicable.

Currently we **_require_** an Argo CD health status in a state, in order for that state to be made available to subscribers. Which means Kargo has a hard requirement with Argo CD.

I think there are two things needed:
1. controller should ~not populate Unknown~ populate `N/A` if there is nothing to assess (e.g. no Argo CD app). The state should appear in the history and as an availableState to subscribers
2. UI ~can't assume health is always there~ should not display any health if it is `N/A`

**Comment by krancour** [comment]
Note to self: NA is a kind of pseudo-healthy.

**Comment by krancour** [comment]
I will address this in the course of completing work on #205.

**Comment by jessesuen** [comment]
@krancour is this fixed by https://github.com/akuity/kargo/pull/685?

**Comment by krancour** [comment]
@jessesuen if you're happy with nil Health as opposed to the N/A state that was originally proposed, then yes.

**Comment by jessesuen** [comment]
Yep I think nil is actually my preference especially since health is now more of a reflection of Argo CD app health..
