### ISSUE TITLE
Rename state to freight

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#624]
A while back, we talked about how the term state was quite generic and overloaded word. Keeping with the shipping/cargo/transport theme, we agreed that "Freight "was a good substitute.

> * [freight](https://www.merriam-webster.com/dictionary/freight)
> 2 a : goods to be shipped : [CARGO](https://www.merriam-webster.com/dictionary/cargo)
> The freight arrived by steamboat.

I think we're at the point where we need to make this switch. It'll just be more and more painful the further off we put this.

**Comment by krancour** [comment]
I will handle this on the back end, but I'll be doing at a time when I expect it will be least disruptive.

Assigning this collectively to myself (back end), @rbreeze and @rpelczar (front end).
