### ISSUE TITLE
UI: Stages should reference currently `Running` promotion

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#639]
Stages can only have a single promotion running at a time. The rest are queued.

If there is a currently running promotion, a Stage's status should reference it by name. The presence or absence of the promotion will allow the UI to show a progressing icon when a Stage is in the middle of a promotion.

**Comment by krancour** [comment]
Great idea. Easy enough to do.

Maybe the Promotion reconciler makes the new freight the Stage's current freight at the _beginning_ of the Promotion process instead of the end and sets its health to a new state "Promoting."

wdyt?

**Comment by jessesuen** [comment]
I thought the semantics of currentFreight was that it would only be updated after successfully passing the promotion. And so, it made sense to me that it would occur at the end (once the promotion was Successful).

I'm not convinced Promoting is technically part of a health state machine (I think of it similar to an Argo CD sync operation). So I think for this issue we should just have a simple status field to reference the running promotion, which will have no bearing on the health of the stage.

**Comment by krancour** [comment]
> I thought the semantics of currentFreight was that it would only be updated after successfully passing the promotion.

That's currently true, although I think it could change if we saw fit and there may be a good argument for that...

_During_ a promotion, a Stage is actually _between_ two freights, but we don't currently make that very clear. Current freight still _looks_ like it's the "from" state. This makes the information in that field already less than accurate.

If current freight holds the "to" freight _during_ the transition and its health denotes the transition is still in progress, I think the overall snapshot of the Stage's status becomes more clear. History will already show what you're transitioning _from_ and for the first time we'd have information that says what the Stage is actively transitioning _to_ and it would be very clear that the transition is still in-progress.

**Comment by krancour** [comment]
Ok... we talked in today's meeting. Capturing what we decided:

CurrentFreight will stay the way it is now, but Stage status will gain more than a mere reference to the active promotion -- we will add enough information so that the freight the Promotion is transitioning _into_ the Stage is readily evident in the Stage's status without having to follow up with a get Promo request.

**Comment by jessesuen** [comment]
Backend/controller work completed in https://github.com/akuity/kargo/pull/687. So remaining work is to show in UI

**Comment by alexmt** [comment]
Working on it
