### ISSUE TITLE
UI: image repository table

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#643]
Separate from the [freightline](https://github.com/akuity/kargo/issues/642), to the right of the DAG we will show repository-specific list of freight content, starting with image repositories (in the future we support helm repository and git repository).

When a user selects an image repository, we will show all the tags of the image repository and color-coded Stages that are currently running that tag.

<img width="463" alt="image" src="https://github.com/akuity/kargo/assets/12677113/f1583548-038e-4fa0-b4d6-78f3f5c62629">

```[tasklist]
### Tasks
- [ ] https://github.com/akuity/kargo/issues/643
```

**Comment by jessesuen** [comment]
NOTE: I consider the history toggle a separate, optional feature in the above mockup. I think history should be done as a separate effort.

**Comment by alexmt** [comment]
working on it
