### ISSUE TITLE
UI: Enrich freight with more git metadata information

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#665]
When choosing to promote a git commit from the UI, it would be nice to know **_what exactly_** I'm promoting rather than just the git commit hash:

<img width="444" alt="image" src="https://github.com/akuity/kargo/assets/12677113/7b0be7b6-a6d2-4de9-b0ad-e9ca905874ec">

Although I can open the link to the commit in a different tab to see more details of the commit, it'd be better to do so without leaving the UI.

How I think this should work: at the time when we introduce the freight to the Stage, we should also capture the git commit message and store it as extra metadata.

Then, the UI will show this additional information in addition to the commit hash.

NOTE: I consider this as a stopgap until https://github.com/akuity/kargo/issues/631, which would allow us to store more metadata about Frieight, among solving other problems.

**Comment by krancour** [comment]
@jessesuen should this have been closed by #671?

**Comment by jessesuen** [comment]
Since UI work is not yet done, I'll convert it to a UI issue

**Comment by krancour** [comment]
> Since UI work is not yet done...

Gotcha. I had overlooked that.
