### ISSUE TITLE
Project CRD

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#667]
The project list view is a bit sad:

![image](https://github.com/akuity/kargo/assets/12677113/c33a4770-c445-406c-b207-eb4505ff3444)

I wonder if we could fill out the project information with things like:
* number of stages
* aggregate health
* whether there is a promotion is in progress

Unfortunately, we need this information to be populated/cached/stored somewhere for the UI to be efficient.

Options I see:
* dedicated cache (like redis)
* annotation in project namespace (requires patch privileges to namespaces)
* ProjectMetadata CRD (which would be a child of a namespace)
* Project CRD (which would be an owner of a namespace)

**Comment by jessesuen** [comment]
Thinking about this more, the approach has has some overlap with https://github.com/akuity/kargo/issues/558. We may need to seriously consider creating cluster-scoped Project CRD, which creates Namespaces, among other things needed in https://github.com/akuity/kargo/issues/558.

**Comment by krancour** [comment]
This will probably be consolidated with #558 into a new issue.
