### ISSUE TITLE
Separate current health of stage+freight from freight's promotability to next stage(s)

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#676]
In #673, @jessesuen wrote:

> we have been equating promotability with argo cd app health. But at the same time, we've been continuously mirroring the currentFreight health with Argo CD app health changes. And we have been presenting these changes in UI as living health.
>
> It seems to me that we need to separate the concept of Argo CD health from Freight being "promotable." This is what I propose:
>
>    Health status should be a living assessment of the underlying Argo CD app(s) associated with the Stage. Health can flap, and would have all of the Argo CD health statuses (Healhty, Degraded, Progressing, Unknown). Health is not applicable on Stages that have no Argo CD app association. Health is also not applicable to Freight. It is simply a mirror of Argo CD app health.
>
>    We introduce a new binary status of a Freight: Qualified vs. Unqualified. A qualified freight has gone through the necessary checks to be promotable to the next stage. If a Stage has an Argo CD app(s), it simply means the apps at one point in time became healthy with that freight. If there is no associated Argo CD app, then Freight is immediately qualified for downstream stages. Once a Freight has been qualified in a Stage, it will never become unqualified.

I would like to work on this issue if that's ok.

**Comment by jessesuen** [comment]
> I would like to work on this issue if that's ok.

SGTM!
