### ISSUE TITLE
UI: DAG should not show promote button if there is nothing to promote

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#691]
<img width="764" alt="image" src="https://github.com/akuity/kargo/assets/426437/e24b97c0-0eab-4ee4-8789-32e82fc948ac">

**Comment by jessesuen** [comment]
Actually, I think the whole promote experience needs some changes based on discussions @rbreeze and I had. The idea I thought we discussed was:
1. when the user clicks on PromoteSubscribers, the freight line would get filtered to only the freight in the Stage's history.
2. then the user could choose from the options in the filtered freightline before promoting

Currently, PromoteSubscribers button can only promote the **_current_** freight of the selected stage. But it should be possible to promote **_anything_** in the history.
