### ISSUE TITLE
Stage health should be populated even if there is not current freight

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#692]
We've agreed to separate stage health and freight promotability. So even if stage don't run any  freight it still should have health

**Comment by krancour** [comment]
I believe in https://github.com/akuity/kargo/issues/623, @jessesuen indicated that stage health being nil was equivalent to stage health being inapplicable.

Wouldn't _nothing_ being in the stage make any assessment of health inapplicable?

**Comment by jessesuen** [comment]
Health should be applicable if there is an Argo CD app. It shouldn't matter if it has current running frieght.

**Comment by krancour** [comment]
Amending with info from most recent meeting:

Part of "health" assessment is whether the Argo CD (apps) are synced with respect to the current freight. This informs the freight's suitability for further promotion.

If there is no current freight, that cannot be checked. We'll just skip that... after all if there's no current freight, the question of the current freight's suitability for further promotion is moot.

**Comment by krancour** [comment]
This is basically part of #570
