### ISSUE TITLE
Stage panel is not showing current freight information

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#698]
We need current freight tab, otherwise it is impossible to say what is running currently

**Comment by alexmt** [comment]
working on it

**Comment by krancour** [comment]
@alexmt I know you were working on this. Did it get fixed and we forgot to close this? Or is it still outstanding?

**Comment by alexmt** [comment]
It is still outstanding

**Comment by krancour** [comment]
> We need current freight tab, otherwise it is impossible to say what is running currently

Cannot recall if we have a tab in the Stage view, but the pipeline with all of its color coding, Freight IDs, labels, etc. is very clear about what is running where.

I think we can safely close this.
