### ISSUE TITLE
bug: "enum" values don't look right in the ui

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#707]
I'm not sure if this is a UI problem or more of a problem with our protobuf definitions.

Here's a "live manifest" from a Stage:

![Screenshot 2023-09-11 at 8 09 26 PM](https://github.com/akuity/kargo/assets/1821014/9280f174-b119-439d-a926-d5e885a01bd3)

The `status` field _should_ read `Healthy`.

Comparing to the CLI, `Healthy` is what you would see, _but_ the CLI is doing type conversions from the protobuf types back to the same v1alpha1 types used by the controller. I suppose the UI is not doing that.

Do we need to add that to the UI, or are we just not using enums properly in the protobuf definitions?

cc @jessesuen @devholic 

Note: Disregard the other values that are all caps. They're junk related to a different PR I'm working on.

__Edit:__ I wonder if there's any real reason that can't be a string field over the wire. It would make type conversions easier and I feel it would be no less safe, because only controllers ever set status values anyway.

**Comment by jessesuen** [comment]
I think the way we are getting live objects is flawed. We do this conversion of kubernetes types to gRPC types which has been proven error prone (e.g. forgetting to include `apiVersion` and `kind` in our proto types.

IMO, I wish we did not do this conversion in our API and would return the native kinds, **_as-is_**.

**Comment by krancour** [comment]
@jessesuen and I spoke and it looks like https://github.com/kubernetes/gengo might be a replacement for gogoproto that could allow us to work with native types over the wire.

**Comment by jessesuen** [comment]
Actually k8s hasn't moved off gogoproto. But we should do a stop-gap measure to return a string instead of a enum as you suggested. @devholic can you take this one?

**Comment by krancour** [comment]
This is adequately addressed by #714 and there's a separate issue open (#708) for the rest of it. Closing.
