### ISSUE TITLE
Add generated CRD reference page.

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#719]

**Comment by krancour** [comment]
@christianh814 @morey-tech looking for someone who can possibly own this item. Any takers?

**Comment by morey-tech** [comment]
Short-term solution: https://doc.crds.dev/github.com/akuity/kargo
Long-term solution: Generate it ourselves with some tool, ideally from the Go code.

**Comment by krancour** [comment]
@morey-tech oh... that is nifty.

I, for one, would be happy with that as an interim solution.

**Comment by krancour** [comment]
I'm going to close this. I think this is fine until such time that we decide #1194 is no longer good enough and we can open a new issue then.
