### ISSUE TITLE
Add concepts for the "freight line" and what is promotable.

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#720]
Explain what the freight line in the UI is and how it works. Explain when a freight is available for promotion, and what the promotion looks like on the freight line.

**Comment by krancour** [comment]
With the "Freight line" (now called "Freight timeline") being only a UI feature, and one you can't really get very far in Kargo with without having been exposed to it, this is probably best addressed in the quickstart, and I believe #2521 has this covered.
