### ISSUE TITLE
Continuous freight verification (e.g. tests/analysis)

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#756]
There are two schools of thought with regard to how to perform Freight qualification in the future:

1. Continuous
2. Imperative

For continuous, the idea is that freight is constantly coming and going within a Stage. As Freight comes, if the qualification checks were never run against the freight, then qualification checks would **_just happen_** against new freight (in accordance with some rules set in the Stage). No user interaction would be necessary. We wouldn't care what caused the freight to come in (e.g. if it was due to a promotion). 

For imperative, the idea is that only through the action of a promotion, would we would run the qualification checks. This might be because we include those checks as part of the promotion job itself (e.g. the Promotion job might run for a long time because it's running the test). 

It is important to note that even today, we already do a mini form of async continuous qualification. How it works today:
1. Promotion happens
2. Freight is added to `status.currentFreight`
3. Since the Stage is associated with an Argo CD app, we do not want to set `.Qualified: true` unless the app reaches healthy status with that freight.
4. Stage reconciler is watching the Argo CD app
5. As soon as the app reaches healthy, we mark the freight as qualified

The above process is asynchronous. The Stage might get "interrupted" with new freight, and so the previous freight would never get qualified, but that's perfectly fine.

@krancour mentioned:
> kargo does check if revisions on apps match what it thinks is current freight and if they don't agree, it does surface as a health problem for the stage.

**Comment by jessesuen** [comment]
> This might be because we include those checks as part of the promotion job itself (e.g. the Promotion job might run for a long time because it's running the test).

So, I initially felt that analysis and testing should be part of the Promotion job. But after some discussion, I think I have come around to the approach where currentFreight is automatically qualified as it enters the Stage as a separate process from Promotion. So I think the  logic during stage reconciliation would be:

1. New currentFreight detected!
2. If no, Is the Argo CD app healthy yet? 
3. Did user define any verification checks we need to run against this freight? 
4. If yes, have we already run them?
5. If no, kick off the tests (this may take a while and so this is async). I will insist that we re-use Rollout's AnalysisRun.
6. Upon a future reconciliation, if the AnalysisRun Succeeded, mark the Freight qualified.

**Comment by krancour** [comment]
This is another that I think was addressed by #1259
