### ISSUE TITLE
Record who initiated promotion with requestor

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#793]
During a promotion, we could record who initiated the promotion in the Promotion job itself. This might be added via API server, or could be done by our webhook (via ServiceAccount).

When it comes time to actually execute the promotion, we would use that information in the git operation. e.g.: make the commit as that user, or incorporate the user in the commit message. This would make commit messages more interesting/useful.

**Comment by krancour** [comment]
Closed in favor of #1742
