### ISSUE TITLE
More Kargo examples should be made available

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#797]
We need to provide the community with a set of examples (beyond the quickstart) that address common patterns. Either in the `kargo` repo or in a separate `kargo-examples` repo in the `akuity` org (I'm favouring the latter). We can take some examples from [krancour/kargo-examples](https://github.com/krancour/kargo-examples).

**Comment by krancour** [comment]
I will attempt to formalize my examples and bundle them into the Kargo repo and docs.

**Comment by krancour** [comment]
#2772 seems to encompass this, so I'm closing this one.
