### ISSUE TITLE
helm chart doesn't support enough control over the api ingress tls settings

### ISSUE THREAD

**Issue by robbert229** [akuity/kargo#802]
Hello, as a consumer of the helm chart I would like to have more control over the ingress. More specifically, currently the api ingress tls settings are derived from a number of other values, and not fully configurable.

Inside of `charts/kargo/templates/api/ingress.yaml` we can see that the tls settings for the ingress are derived exclusively from the `.Values.api.host`, and `.Values.api.ingress.tls.enabled`. This restriction means that I need to disable the ingress, and manually create my own.

```
  {{- if .Values.api.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.api.host }}
    secretName: kargo-api-ingress-cert
  {{- end }}
```

Ideally though the ingress would support the same level of configuration that the helm chart for argocd supports

source: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/ingress.yaml
```
  {{- with .Values.server.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
```

EDIT: 
another good example of ingress settings can be found here: 

https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch#traffic-exposure-parameters

**Comment by krancour** [comment]
Hi @robbert229! Happy to entertain this idea, but I have some curiosity about what you want to do differently with that TLS section. Checking the reference docs, it seems the only two things you could do differently in that spot are add additional hostnames or reference a different secret.

**Comment by krancour** [comment]
@robbert229 just noting that I'm still curious about what you want to do differently with that TLS section.

**Comment by krancour** [comment]
We never got clarification on the use case for this.

**Comment by mmclane** [comment]
I want to be able to use a different certificate for sure.  I am having to do some slightly weird things to get it up and running.  But mostly its because the way you have it is a bit black box and not very standard.

**Comment by krancour** [comment]
@mmclane can you explain what is preventing you from using a cert of your choosing?
