### ISSUE TITLE
Error for Invalid promotion caused by a subscription loop is not surfaced to the user

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#806]
When attempting to promote an invalid update that would form a subscription loop, the promotion appears successful, but nothing happens. Only once the user clicks into the stage will they know it failed due to this error.

What the user will see (`Stage "test" has been promoted.`):
![Xnapper-2023-09-20-10 36 10](https://github.com/akuity/kargo/assets/4213435/a4e636cd-f557-4712-b9fc-a1f58e5c240e)

What they need to find to understand that the promotion failed:
![Xnapper-2023-09-20-10 36 24](https://github.com/akuity/kargo/assets/4213435/4e373b35-89bc-4777-8a6b-6f773b9f54f9)

This error should surfaced on the main page instead of only on the stage's page, possibly with an icon on the stage or a pop-up message.

**Comment by krancour** [comment]
I think the main trouble here is that the current pop up makes it appear that the `Promotion`, succeeded, when really it is just acknowledging the _request_ to promote. (The actual promotion is carried out asynchronously.)

I think a quick band-aid here could be to change the language in the current pop up and bit and use an icon that is more reflective of a _pending_ state.

> possibly with an icon on the stage

Longer term, I like this suggestion of something that makes it obvious, at a glance, that a Stage's most recent Promotion has failed.

**Comment by krancour** [comment]
Tentatively assigning to @rbreeze. Feel free to tackle or pass.

**Comment by rbreeze** [comment]
I'm going to solve this specific issue by updating the banner content as @krancour suggested. 

Then will continue to track the larger issue of surfacing promotion failures in this issue: https://github.com/akuity/kargo/issues/1207
