### ISSUE TITLE
optionally constrain git repo subscriptions by tags

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#816]
Subscriptions to Git repos are currently very different from subscriptions to image or chart repos.

With images, it's possible, but unlikely that every commit to your source code repo results in a new release of the image. For most cases, a recent _batch_ of changes will be deemed release-worthy and the corresponding image(s) will be built and published to the image repo.

Similar is true for charts (consumed from chart repos; not charts consumed directly from Git). It's possible, but unlikely that every commit to a chart's own source code repo results in a new release of the chart. For most cases, a recent _batch_ of changes will be deemed release-worthy and the corresponding chart will be built and published to the chart repo.

But if you subscribe a stage to the `main` branch of a Git repo containing manifests, _every_ commit to that branch enters your pipeline. Speaking personally, I don't love that. As with images and charts, I'd like to decide that a recent _batch_ of changes is release-worthy and then release it into my pipeline.

I think this is easy-ish to do using semantics similar to those used by the image subscriptions (which are borrowed in their entirety from Argo CD Image Updater). I'm not advocating that manifests need to be tagged with semantic versions, but suppose they were. It's easy to see that you _could_ then subscribe to manifests with a version constraint like `^1.24.0`. Again... using all the same semantics as Image Updater, we could support a broad range of sensible schemes ranging from "just give me the newest" to "give me the last in a lexical ordering of all tags matching this pattern."

To be clear... this would all be optional, but the end result would be a way to prevent _every. little. change._ from entering your pipelines if that isn't what you want.

cc @jessesuen

**Comment by jessesuen** [comment]
> this would all be optional, but the end result would be a way to prevent every. little. change. from entering your pipelines if that isn't what you want.

Yes, I can see the Freightline being deluged with inconsequential commits to things like README.md and other things. Also, the concept of tagging freight came up in the webinar, so leveraging existing git mechanisms is extremely attractive to me.

In general, having rules on when to produce new freight is going to be important to limit the UI to only useful promotable things. Another idea that you just inspired me with, is the idea of only producing new Freight based on changes to certain *directories* or file types. e.g. You only care if `.yaml` changed, or `.yaml` inside `base/` or `env/*` directories
