### ISSUE TITLE
Links on image subscriptions are broken in the UI

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#831]
![Xnapper-2023-09-22-11 48 37](https://github.com/akuity/kargo/assets/4213435/56a6aa2a-bd8f-481b-8ae1-91ea9f159547)

UI seems to assume that the image URL can be accessed directly.

**Comment by krancour** [comment]
I'm not sure a _browsable_ URL can be universally inferred from image URLs.

* Docker Hub _official images_ example: https://hub.docker.com/_/nginx
* Docker Hub in general: https://hub.docker.com/repository/docker/krancour/kargo/general
* Quay: https://quay.io/repository/christianh814/kargo-demo-app
* GHCR: https://github.com/akuity/kargo/pkgs/container/kargo

@jessesuen do you think in the absence of something general, we should build support for handling these four cases at least?

**Comment by krancour** [comment]
@rbreeze are you thinking we add it in the back end and have the UI just display it? Or implement it as a UI feature?

**Comment by rbreeze** [comment]
I think it can probably be just a UI feature, as I can't think of any reason the backend would need fully formed URLs
