### ISSUE TITLE
Extract information from git subscriptions as Freight metadata

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#836]
Spawned from https://github.com/akuity/kargo/issues/832

A user who is only using git subscriptions, doesn't have much visibility into what is being promoted. Today they can only see the title of the git commit, and are forced to click around links in github to understand the details of the payload.

We could make this easier for them. For example, we should provide a way to surface image tags out of the YAML in git, and then present those image tags to the UI.

But why stop there? We could also provide users with customized ways to extra other information (e.g. jq query). All of this would be surfaced to the UI so that very easily, users could see exactly *what* is being promoted.

**Comment by jaimin001** [comment]
Hello @jessesuen,
I was trying to work on this issue and was breaking a problems into smaller steps:

1. So we need to modify the `buildValuesFilesChanges` function to extract image tags from the YAML and include them in the `changesByFile` map. (for this we'll have to implement a function to extract image tag from YAML)
2. Then we can update the UI to display the extracted tags with the git commit title.

Is this correct? (sorry, I am new to this 😅)

**Comment by jessesuen** [comment]
Another use case is to extract umbrella chart versions from git (https://github.com/akuity/kargo/issues/1256)

**Comment by krancour** [comment]
@jaimin001 sorry... I just noticed your comment from quite some time ago.

> So we need to modify the buildValuesFilesChanges function to extract image tags from the YAML and include them in the changesByFile map. (for this we'll have to implement a function to extract image tag from YAML)

You are talking about the promotion process. i.e. _Making_ commits to a git repo, while @jessesuen is talking about _subscriptions_. Extracting information _from_ a commit in a git repo to which a Warehouse is subscribed. Those commits it reads won't usually have been written by Kargo. So, fundamentally, these are two unrelated concerns.
