### ISSUE TITLE
always canonicalize git repo URLs

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#838]
See #807

There's _at least_ one place where git repo URLs were not canonicalized before comparison.

I will seek out and fix those.

I am also considering updating the webhooks to ensure such URLs are canonicalized on their way in the door.

**Comment by krancour** [comment]
This is a good first issue, so I am un-assigning myself and labeling it correctly.

I will re-assign myself if we get close to the v0.2.0 and this isn't handled yet.

**Comment by mdshack** [comment]
Hey @krancour, looking to pick up this issue. Should be able to dig into the codebase some time this week and begin working on a PR. 

Do you happen to have any preferences on how we cannoncalize the URLs (such as add trailing slashes or remove trailing slashes, stripping protocol or standardizing protocol, etc)?

**Comment by krancour** [comment]
Nevermind... I was searching for "canonicalize" and I should have been searching for "normalize"

`git.NormalizeGitURL` borrowed from `github.com/argoproj/argo-cd/v2/util/git`

**Comment by krancour** [comment]
@mdshack are you still planning to work on this or should I re-assign it?
