### ISSUE TITLE
image subscription repoURL does not allow `.` in the image name

### ISSUE THREAD

**Issue by moensch** [akuity/kargo#846]
The current regular expression to validate `repoURL` only allows a dot (`.`) in the host part, but not the image name.

For example, this here should be a valid image name: `docker.io/someuser/some.repo/other-image`

Since a `.` can be used in any part of an image name, the regex should be updated:

https://github.com/akuity/kargo/blob/f3cc86511854ab1755f24ae705ea19b08c9750fa/api/v1alpha1/stage_types.go#L154-L159

See: https://docs.docker.com/engine/reference/commandline/tag/#description

> The path consists consists of slash-separated components. Each component may contain lowercase letters, digits and separators. A separator is defined as a period, one or two underscores, or one or more hyphens.

**Comment by krancour** [comment]
@moensch thanks for reporting!
