### ISSUE TITLE
Kargo `get` should have `--all-projects`

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#864]
When running `kargo get` it would be nice to be able to see everything by passing `--all-projects` (maybe `-P` to match Kubernetes' version of `--all-namespaces` with the shorthand of `-A`)

**Comment by krancour** [comment]
Totally.

Note to whoever works on this, there may be special considerations for this operation with respect to whatever we end up doing for SSO user --> cluster SA mappings.

**Comment by krancour** [comment]
> Note to whoever works on this, there may be special considerations for this operation with respect to whatever we end up doing for SSO user --> cluster SA mappings.

This can be ignored for the moment, which makes this a relatively small change -- good for hacktoberfest.

**Comment by maksimstankevic** [comment]
Hi! I submitted https://github.com/akuity/kargo/pull/1143 for this.

**Comment by maksimstankevic** [comment]
I'm closed #1143 as it looks like now #1098  is standing in the way and it's not clear "--all-projects" option for get commands will live.

**Comment by krancour** [comment]
> closed https://github.com/akuity/kargo/pull/1143 as it looks like now https://github.com/akuity/kargo/issues/1098 is standing in the way

#1148 actually

Closing as explained [here](https://github.com/akuity/kargo/pull/1143#issuecomment-1821009018).
