### ISSUE TITLE
relax regex for git repo urls

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#870]
From #867

The regex for git repo URLs needs to be relaxed.

```
one or more objects failed to apply, reason: Stage.kargo.akuity.io "develop" is invalid: [spec.promotionMechanisms.gitRepoUpdates[0].repoURL: Invalid value: "https://gitea-http.gitea.svc/gotham/gotham-cd": spec.promotionMechanisms.gitRepoUpdates[0].repoURL in body should match '^((https?://)|([\w-]+@))([\w\d.]+)(:[\d]+)?/(.)$', spec.subscriptions.repos.git[0].repoURL: Invalid value: "https://gitea-http.gitea.svc/gotham/gotham-cd.git": spec.subscriptions.repos.git[0].repoURL in body should match '^((https?://)|([\w-]+@))([\w\d.]+)(:[\d]+)?/(.)$'].
```

**Comment by krancour** [comment]
@tal-hason it would be great if you were interested in making this change.

**Comment by tal-hason** [comment]
@krancour , do you mean to fix it in the code and create a PR?

**Comment by krancour** [comment]
Yes

**Comment by tal-hason** [comment]
First thing, thanks for the trust.

Second my knowledge in go is none😏

Third I tried to find it in the code but without seccess.

**Comment by tal-hason** [comment]
@krancour , can you point me to the file/area where this is located?

**Comment by krancour** [comment]
https://github.com/akuity/kargo/blob/main/api/v1alpha1/stage_types.go#L141

Note that generated code needs to be re-generated after changing this.

make hack-codegen

That will run codegen in a container that already has all the required tools, but someone recently mentioned the Dockerfile.dev for building the image containing all those tools may be having an issue.

I will look at that on Monday to make sure it's not going to trip you up.

**Comment by rumstead** [comment]
Should we account for Azure DevOps HTTPS clone URLs while we are at it?

```
https://<tenant>@dev.azure.com/<tenant>/<project>/_git/<git repo>
```

**Comment by tal-hason** [comment]
i will test it as well. NP

**Comment by tal-hason** [comment]
> Should we account for Azure DevOps HTTPS clone URLs while we are at it?
> 
> ```
> https://<tenant>@dev.azure.com/<tenant>/<project>/_git/<git repo>
> ```
> 
> EDIT: if we don't care about capture groups, something like this `^((git|ssh|http(s)?)|(git@[\w\.-]+))(:(//)?)([\w\.@\:/\-~]+)(/)?$`

you want to add ssh? as a support option? in the docs it remarked that only HTTPS is supported right-now

**Comment by krancour** [comment]
ssh should not be allowed because other parts of the system cannot yet accommodate that.

Even http should not be allowed at this time. There's a separate issue open for that because there are broad security implications to be considered.

**Comment by rumstead** [comment]
The regex was something I have used in the past with ado and GitHub repos. Please augment to fit the requirements

**Comment by tal-hason** [comment]
So:

> ^((https://)|([\w.-@]+@))([\w.-]+)(:[\d]+)?(/(.*))?$

this should work with the Azure sample and allow "." in the domain name

**Comment by krancour** [comment]
Just PR it... It's easier for me to visually compare that way than to hunt down the original to compare.

Did you run this through any kind of regex tester?

**Comment by tal-hason** [comment]
> Just PR it... It's easier for me to visually compare that way than to hunt down the original to compare.
> 
> Did you run this through any kind of regex tester?

yes yes I tested it in regex 101, and now I will spin my personal git and try

**Comment by moensch** [comment]
@tal-hason I was working on a fix in the same area and lumped your regex in with it https://github.com/akuity/kargo/pull/915

**Comment by tal-hason** [comment]
> @tal-hason I was working on a fix in the same area and lumped your regex in with it #915

I saw NP, I used the time to work on a personal project 😊
