### ISSUE TITLE
add webinar video to readme and doc home page

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#871]

**Comment by dhanusaputra** [comment]
hi, can I help with this please? thanks

**Comment by krancour** [comment]
@dhanusaputra sure! Just to be clear, we want the video embedded, not just a link.

@christianh814 or @morey-tech does one of you have the URL for the video?

@dhanusaputra can work on embedding it in the README and docs.

Thanks again for volunteering @dhanusaputra!

**Comment by morey-tech** [comment]
@dhanusaputra, here's the link to the webinar! For reference, you can check out [this PR](https://github.com/akuity/kargo/pull/765/files), where an embedded video was removed.

```
https://youtu.be/yaZc0DdeLKk
```

**Comment by krancour** [comment]
Thank you @morey-tech!
