### ISSUE TITLE
Support git repos with http/non-ssl URL

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#872]
From #867

Support for git repos with http/non-ssl URL has been requested.

fwiw, I think there are a lot of security implications to consider before deciding to proceed with this.

**Comment by krancour** [comment]
Discussed with @jessesuen.

My initial concern here was that I don't want to see credentials passed over an insecure connection. The counterpoint is that devs may sometimes run local git servers without SSL. I was reluctant to enable the latter by opening the door to the former.

The middle ground we agreed on is similar to what Kubernetes does -- allow non-SSL connections, but refuse to pass credentials over them.

So implementation here looks like:

* Relax a few regexes
* Make the credential DB log a warning and return nil if/when it looks up creds for a URL beginning with `http://`

This is sufficiently easy that I'm adding this to hacktoberfest.

**Comment by hiddeco** [comment]
> Make the credential DB log a warning and return nil if/when it looks up creds for a URL beginning with `http://`

If taken literally (i.e. without taking the type into account), this would appear to have an effect on Helm repositories as well. As it seems HTTP endpoints are currently allowed here: https://github.com/akuity/kargo/blob/ba55091734a723b0d53dc4610b826ed1cbdb7e36/api/v1alpha1/warehouse_types.go#L193

While I do not necessarily think this would be bad (the same logic around _not_ wanting to pass credentials over an insecure wire could apply here), it would be breaking.

**Comment by krancour** [comment]
> it would be breaking

Breaking changes are ok for the time being, but that may end soon.

We're in "get 'em in while you still can" territory.
