### ISSUE TITLE
promote with curl

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#878]
if I want to promote from one stage to another, with a curl command, what is the body, or even a sample command will be awesome

**Comment by krancour** [comment]
@tal-hason not possible. I am curious how you'd envision something like that working. Can you give an example?

My initial thought is that promoting using curl sounds more imperative than declarative. It doesn't sound like gitops.

**Comment by jessesuen** [comment]
I think he might be asking about what is the API to do it and how could he do it via kargo CLI?

**Comment by jessesuen** [comment]
If so, it'd be something like:

```
curl 'https://kargo.demo.akuity.io/akuity.io.kargo.service.v1alpha1.KargoService/PromoteStage' \
  -H 'authorization: Bearer <token>' \
  --data-raw '{"project":"kargo-guestbook","name":"dev","freight":"6ddc6f381820053cf3e0d4dfe5f44b8a3282882b"}' 
```

However, I would suggest you stick with the CLI until we stabilize the API payload / response. e.g.

```
kargo stage promote (PROJECT) (NAME) [(--freight=)freight-id]
```

**Comment by krancour** [comment]
Ohhhh. I mistook this for referencing a hypothetical curl-based promotion mechanism.

Is curling a grpc API actually possible? Protobufs are binary, right?

**Comment by jessesuen** [comment]
Although our API definitions are protobuf, we use [Connect](https://connectrpc.com/), which is protobuf-backed gRPC +  server. It supports both binary gRPC and HTML. 

Unfortunately, Connect doesn't generate REST like semantics, so I grabbed the above example from copying an interaction from my browser. But generating clients from connect is supposed to be a easy and our UI has benefitted greatly from it.

**Comment by krancour** [comment]
Ah. Hasn't understood that Connect aspect of it. Thanks.

**Comment by tal-hason** [comment]
Thanks Guys
