### ISSUE TITLE
Enable nightly builds

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#880]
Especially in these early days, it will be helpful for users to try pre-release builds of kargo for testing and getting early access to fixes and features, without having to build an image themselves. I know @christianh814 was looking for a fix in an unreleased version of kargo. We discussed, and we both thought having nightly builds via a github cron would be a good/easy way to get fixes in the hands of users.

```[tasklist]
### Tasks
- [ ] https://github.com/akuity/kargo/issues/880
```

**Comment by krancour** [comment]
Like this idea.

Presumably this doesn't translate to a nightly release or the releases page will get cluttered.

Maybe CLI binaries and SBOMs go to an s3 bucket instead and images and charts go to alternate OCI registries/repos so we don't clutter the official ones?

wdyt?

**Comment by krancour** [comment]
@kencochrane I am wondering if this is something you might want to look at. If not, no worries.

**Comment by kencochrane** [comment]
@34fathombelow can you take a look

**Comment by jessesuen** [comment]
> Presumably this doesn't translate to a nightly release or the releases page will get cluttered.

Right. We shouldn't pollute the release page, and I would even propose using a different image repository as to not cluster the ghcr.io/akuity/kargo repository. Something like: `ghcr.io/akuity/kargo-unstable`.

**Comment by krancour** [comment]
Perfect... also want a separate/unstable registry for the chart.

**Comment by krancour** [comment]
Another thing that probably shouldn't happen nightly is the recently added job for uploading CLI schema to Fig.

**Comment by 34fathombelow** [comment]
Completed.. I will open another issue to document on how to use the nightly builds.
