### ISSUE TITLE
Add a comment/commit message when promoting in the UI or CLI when promoting a frieght

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#885]
add an optional comment to the user when creating a promotion step.

in the cli:
```Bash
kargo stage promote {{project}} {{stage}} --freight-id={{XXXX}} --message="some text here"
```

**Comment by krancour** [comment]
I think this is a worthwhile idea.

> Add a comment/commit message when promoting

Not all promotions will involve a git commit. I've been trying to imagine what we do with that message if there is no commit involved, or whether we just silently ignore the message in that case even...

Then it occurred to me that a commit isn't the only reasonable place to stash a message like this. The Promotion resource itself, _for instance_, could be another good place where a message of this nature could be stored.

I'll keep thinking about this, and more detail on how you imagined this working would also be helpful.

**Comment by tal-hason** [comment]
@krancour , yes, in any case, a user message should be an option when promoting, store it in the promotion resource will be great, and also when showing the promote in the UI when hovering it the message will pop, so when checking to promote the user will have the option to explain in a free text the reason or a notion of this promotion.

and when there is a commit use the user message as the commit message.

it can also be an icon on the stage that have the promoted freight so the message will be much more transperant
