### ISSUE TITLE
No Binary for x86_64 Mac

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#892]
The following is not working on an x86_64  Mac:

```
curl -sSL -o kargo https://github.com/akuity/kargo/releases/latest/download/kargo-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)
```
It is resolved in https://github.com/akuity/kargo/releases/latest/download/kargo-darwin-x86_64 which does not exist

**Comment by krancour** [comment]
I fired up my very old Mac and can confirm this is an issue. I expected `uname -m` to return `amd64` on an Intel Mac.

We can script around this.

**Comment by krancour** [comment]
Needs some testing, but this would probably work:

```shell
arch=$(uname -m)
[ "$arch" = "x86_64" ] && arch=amd64
curl -sSL -o kargo https://github.com/akuity/kargo/releases/latest/download/kargo-$(uname -s | tr '[:upper:]' '[:lower:]')-${arch}
chmod +x kargo
```

**Comment by krancour** [comment]
Tested that script. Easy PR if someone wants to copy/paste.
