### ISSUE TITLE
Ability to do a phased rollout/deployment rings across many clusters

### ISSUE THREAD

**Issue by aaronmell** [akuity/kargo#907]
# Checklist

* [x] I've searched the [docs](https://kargo.akuity.io/) and issue queue for an answer.
* [N/A] I've pasted the output of `kargo version`, if applicable.
* [N/A] I've pasted logs, if applicable.

# Question

We run a setup where we have many production clusters, and we use a bespoke phased rollout/deployment rings approach today. We randomize the order of our production environments (with some rules) into multiple phases, with a delay between phases. 

Is this a usecase that kargo would be able to support in some fashion?

**Comment by wanghong230** [comment]
> We randomize the order of our production environments

I like this pattern. :)

**Comment by rumstead** [comment]
Similar use case as above. 

We have 200+ production clusters where different clusters will receive a promotion in a waved fashion. It allows for some users to get early access to features as well as give stability to users who require it. [Progressive Syncs](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/) don't quite capture the use case but are a step in the right direction.

**Comment by aaronmell** [comment]
reopen
