### ISSUE TITLE
all commits look like they came from bookkeeper

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#927]
Starting with #381, when we started re-using Bookkeeper's `git` package, all commits made by Kargo look like they were made by "Bookkeeper" / "bookkeeper@akuity.io" even when Bookkeeper wasn't involved.

The fix will involve Bookkeeper changes as well (and fwiw, Bookkeeper will be re-branded as something like "kargo-render"), but we should probably make the username and email address used for commits configurable.

**Comment by tal-hason** [comment]
Just Pointing that #885 is some how connected to this...

**Comment by krancour** [comment]
Not very connected.

**Comment by krancour** [comment]
The fix for #957 can also fix this.

**Comment by krancour** [comment]
I believe #957 took care of this.
