### ISSUE TITLE
Add Promotion Policy flag to stage in UI

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#961]
# Checklist

* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.
* [x] I've searched the issue queue to verify this is not a duplicate feature request.

# Proposed Feature

currently, in the UI, there isn't any indication of the promotion Policy of the stage (manual, automatic), so unless you know the YAMLs there isn't any indication that the user of this stage will auto promote or needs a user action

# Motivation

Make the promotion Policy more transparent to the users via the UI

# Suggested Implementation

Add a small icon at every stage with that indicates the stage promotion policy

**Comment by krancour** [comment]
This is a good idea. @rbreeze what do you think?

**Comment by rbreeze** [comment]
Agreed!
